___

<a href="https://lms.clarusway.com/mod/lesson/view.php?id=8511&pageid=8142&startlastseen=no"><img align="left" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href=""><img align="right" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="100" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<img src=https://i.ibb.co/b5xXg11/used-cars1.jpg width="1100" height="100">

[Image Credit](https://myscriptneedshelp.com/2022/auto/buying-used-cars-in-tempe-is-easier-now/)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">The Capstone Project of Data Analytics Module</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:150%; text-align:center; border-radius:10px 10px;">Car Price Prediction EDA</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [IMPORTING LIBRARIES NEEDED IN THIS NOTEBOOK](#0)
* [PART-02 (HANDLING WITH MISSING VALUES)](#1)
* [THE EXAMINATION OF MISSING VALUES IN THE COLUMNS](#2)    
* [THE END OF MISSING VALUES (PART - 02)](#3)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Importing Libraries Needed in This Notebook</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

If you have NOT installed NumPy & Pandas so far, once you've installed them you can import them as a library and other libraries need in this analysis:

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt
from scipy import stats
from scipy.stats.mstats import winsorize

import warnings
warnings.filterwarnings("ignore")
warnings.warn("this will not show")

%matplotlib inline
# %matplotlib notebook

plt.rcParams["figure.figsize"] = (10, 6)
# plt.rcParams['figure.dpi'] = 100

sns.set_style("whitegrid")
pd.set_option('display.float_format', lambda x: '%.3f' % x)

pd.options.display.max_rows = 1000
# pd.set_option('display.max_rows', None)
pd.options.display.max_columns = 150

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">PART- 02 (Handling with Missing Values)</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [ ]:
df0 = pd.read_csv("clean_scout2022.csv")
df = df0.copy()

In [ ]:
df.head(3).T

,0,1,2
make_model,Mercedes-Benz A 160,Mercedes-Benz EQE 350,Mercedes-Benz A 45 AMG
make,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz
location,"P.I. EL PALMAR C/FORJA 6, 11500 PUERTO DE SAN...","APARTADO DE CORREOS 1032, 26140 LOGROÑO, ES","PORT. TARRACO, MOLL DE LLEVANT, Nº 5, LOC. 6-8..."
price,16950.000,80900.000,69900.000
body_type,Compact,Compact,Compact
type,Used,Pre-registered,Used
doors,5.000,4.000,5.000
warranty,24.000,24.000,12.000
mileage,120200.000,5000.000,18900.000
gearbox,Manual,Automatic,Automatic
fuel_type,Diesel,Electric,Benzine
seller,Dealer,Dealer,Dealer
seats,NaN,5.000,5.000
engine_size,NaN,1.000,1991.000
gears,NaN,9.000,8.000
co_emissions,NaN,0.000,NaN
drivetrain,NaN,NaN,4WD
cylinders,NaN,NaN,4.000
comfort_&_convenience,NaN,NaN,NaN
entertainment_&_media,NaN,NaN,NaN
safety_&_security,NaN,NaN,NaN
extras,NaN,NaN,NaN
empty_weight,NaN,NaN,NaN
full_service_history,No,No,No
upholstery,NaN,NaN,NaN
previous_owner,NaN,NaN,NaN
energy_efficiency_class,NaN,NaN,NaN
age,6.000,0.000,2.000
power_kW,NaN,215.000,310.000
power_hp,NaN,292.000,421.000
cons_avg,NaN,NaN,8.400
cons_city,NaN,NaN,10.900
cons_country,NaN,NaN,5.800

In [ ]:
df.shape

(28630, 33)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28630 entries, 0 to 28629
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   make_model               28630 non-null  object
 1   make                     28630 non-null  object
 2   location                 28630 non-null  object
 3   price                    28630 non-null  float64
 4   body_type                28630 non-null  object
 5   type                     28630 non-null  object
 6   doors                    28271 non-null  float64
 7   warranty                 13465 non-null  float64
 8   mileage                  28629 non-null  float64
 9   gearbox                  28382 non-null  object
 10  fuel_type                26843 non-null  object
 11  seller                   28630 non-null  object
 12  seats                    25505 non-null  float64
 13  engine_size              27227 non-null  float64
 14  gears                    18954 non-null  float64
 15  co_emissions             18594 non-null  float64
 16  drivetrain               16893 non-null  object
 17  cylinders                18852 non-null  float64
 18  comfort_&_convenience    25433 non-null  object
 19  entertainment_&_media    23644 non-null  object
 20  safety_&_security        25415 non-null  object
 21  extras                   23480 non-null  object
 22  empty_weight             17758 non-null  float64
 23  full_service_history     28630 non-null  object
 24  upholstery               18610 non-null  object
 25  previous_owner           14015 non-null  float64
 26  energy_efficiency_class  7804 non-null   object
 27  age                      28628 non-null  float64
 28  power_kW                 28058 non-null  float64
 29  power_hp                 28058 non-null  float64
 30  cons_avg                 23385 non-null  float64
 31  cons_city                20100 non-null  float64
 32  cons_country             20100 non-null  float64
dtypes: float64(17), object(16)
memory usage: 7.2+ MB

In [ ]:
class color:
    PURPLE = '\033[95m'
    CYAN = '\033[96m'
    DARKCYAN = '\033[36m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    END = '\033[0m'

def check_obj_columns(df):
    '''
    Returns NO PROBLEM or column/s which has/have mixed object types.
    '''    
    
    tdf = df.select_dtypes(include=['object']).applymap(type)
    for col in tdf:
        if len(set(tdf[col].values)) > 1:
            print("Column" + " " + color.BOLD + color.RED + col + color.END + " " + "has mixed object types." )
    else:
        if len(set(tdf[col].values)) == 1:
            print(color.BOLD + color.GREEN + " " + "NO PROBLEM" + " " + color.END + " " + "with the data types of Columns in the DataFrame.")

check_obj_columns(df)

Column gearbox has mixed object types.
Column fuel_type has mixed object types.
Column drivetrain has mixed object types.
Column comfort_&_convenience has mixed object types.
Column entertainment_&_media has mixed object types.
Column safety_&_security has mixed object types.
Column extras has mixed object types.
Column upholstery has mixed object types.
Column energy_efficiency_class has mixed object types.

### The Examination of Missing Values:

In [ ]:
missing_percentage = df.isnull().sum()*100 / df.shape[0]

In [ ]:
# miss_val = []

# [miss_val.append(column) for column in df.columns if any(df[column].isnull())]

# print("Columns that have missing values :")
# print("---"*11)

# print(f"{miss_val}\n\n{missing_percentage}")

In [ ]:
miss_val = []
[miss_val.append(column) for column in df.columns if any(df[column].isnull())]

# Burada bildiğiniz list comprehension yöntemi ile içinde bir tane bile missing value olan
# columnları bir liste içinde topladık.

missing_percentage = df[miss_val].isnull().sum()*100 / df[miss_val].shape[0]
print("Columns that have missing values :")
print("---"*11)
print(f"{miss_val}\n\n{missing_percentage}")

Columns that have missing values :
---------------------------------
['doors', 'warranty', 'mileage', 'gearbox', 'fuel_type', 'seats', 'engine_size', 'gears', 'co_emissions', 'drivetrain', 'cylinders', 'comfort_&_convenience', 'entertainment_&_media', 'safety_&_security', 'extras', 'empty_weight', 'upholstery', 'previous_owner', 'energy_efficiency_class', 'age', 'power_kW', 'power_hp', 'cons_avg', 'cons_city', 'cons_country']

doors                      1.254
warranty                  52.969
mileage                    0.003
gearbox                    0.866
fuel_type                  6.242
seats                     10.915
engine_size                4.900
gears                     33.797
co_emissions              35.054
drivetrain                40.995
cylinders                 34.153
comfort_&_convenience     11.167
entertainment_&_media     17.415
safety_&_security         11.229
extras                    17.988
empty_weight              37.974
upholstery                34.998
previous_owner            51.048
energy_efficiency_class   72.742
age                        0.007
power_kW                   1.998
power_hp                   1.998
cons_avg                  18.320
cons_city                 29.794
cons_country              29.794
dtype: float64

### The Examination of Duplicated Values:

In [ ]:
df.duplicated(keep=False).sum()

3887

In [ ]:
df[df.duplicated(keep=False)]

,make_model,make,location,price,body_type,type,doors,warranty,mileage,gearbox,fuel_type,seller,seats,engine_size,gears,co_emissions,drivetrain,cylinders,comfort_&_convenience,entertainment_&_media,safety_&_security,extras,empty_weight,full_service_history,upholstery,previous_owner,energy_efficiency_class,age,power_kW,power_hp,cons_avg,cons_city,cons_country
142,Mercedes-Benz A 45 AMG,Mercedes-Benz,"RONDA PONENT 62, 8201 SABADELL, ES",72890.000,Compact,Used,5.000,12.000,12900.000,Automatic,Benzine,Dealer,5.000,1991.000,8.000,NaN,4WD,4.000,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,1.000,310.000,421.000,8.400,10.900,5.800
237,Mercedes-Benz CL,Mercedes-Benz,"--, 77240 Vert St Denis, FR",39990.000,Compact,Used,5.000,NaN,8500.000,Automatic,Benzine,Dealer,5.000,1332.000,NaN,NaN,NaN,NaN,"Air conditioning, Armrest, Automatic climate c...","Digital radio, Hands-free equipment, On-board ...","ABS, Central door lock, Central door lock with...","Alloy wheels, Shift paddles, Sport package, Sp...",NaN,No,NaN,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN
253,Mercedes-Benz CL,Mercedes-Benz,"--, 77240 Vert St Denis, FR",39990.000,Compact,Used,5.000,NaN,8500.000,Automatic,Benzine,Dealer,5.000,1332.000,NaN,NaN,NaN,NaN,"Air conditioning, Armrest, Automatic climate c...","Digital radio, Hands-free equipment, On-board ...","ABS, Central door lock, Central door lock with...","Alloy wheels, Shift paddles, Sport package, Sp...",NaN,No,NaN,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN
263,Mercedes-Benz CL,Mercedes-Benz,"--, 77240 Vert St Denis, FR",39990.000,Compact,Used,5.000,NaN,8500.000,Automatic,Benzine,Dealer,5.000,1332.000,NaN,NaN,NaN,NaN,"Air conditioning, Armrest, Automatic climate c...","Digital radio, Hands-free equipment, On-board ...","ABS, Central door lock, Central door lock with...","Alloy wheels, Shift paddles, Sport package, Sp...",NaN,No,NaN,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN
276,Mercedes-Benz A 45 AMG,Mercedes-Benz,"RONDA PONENT 62, 8201 SABADELL, ES",72890.000,Compact,Used,5.000,12.000,12900.000,Automatic,Benzine,Dealer,5.000,1991.000,8.000,NaN,4WD,4.000,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,1.000,310.000,421.000,8.400,10.900,5.800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28253,Volvo V60 Cross Country,Volvo,"Via Ca' Baroncello, 32/B, 36061 Bassano Del G...",32500.000,Station wagon,Used,5.000,NaN,142000.000,Automatic,Diesel,Dealer,5.000,1969.000,8.000,143.000,4WD,4.000,"Air conditioning, Armrest, Automatic climate c...","Digital radio, Radio","Adaptive Cruise Control, Blind spot monitor, D...","Alloy wheels, Automatically dimming interior m...",NaN,No,Full leather,NaN,NaN,3.000,140.000,190.000,5.400,6.300,4.900
28556,Volvo S90,Volvo,"Von-Drais-Str. 2, 77855 Achern, DE",31488.000,Sedan,Used,4.000,NaN,84000.000,Automatic,Diesel,Dealer,5.000,1969.000,0.000,127.000,4WD,4.000,"Air conditioning, Automatic climate control, A...","On-board computer, Radio, USB","ABS, Adaptive headlights, Central door lock, D...","Alloy wheels, Catalytic Converter, Sport suspe...",1892.000,No,Full leather,NaN,efficient,5.000,173.000,235.000,4.800,5.700,4.300
28557,Volvo S90,Volvo,"Von-Drais-Str. 2, 77855 Achern, DE",31488.000,Sedan,Used,4.000,NaN,84000.000,Automatic,Diesel,Dealer,5.000,1969.000,0.000,127.000,4WD,4.000,"Air conditioning, Automatic climate control, A...","On-board computer, Radio, USB","ABS, Adaptive headlights, Central door lock, D...","Alloy wheels, Catalytic Converter, Sport suspe...",1892.000,No,Full leather,NaN,efficient,5.000,173.000,235.000,4.800,5.700,4.300
28593,Volvo V40,Volvo,"19 rue des Alliés, 57050 Metz, FR",18999.000,Sedan,Used,5.000,12.000,93257.000,Automatic,Diesel,Dealer,5.000,1969.000,NaN,108.000,NaN,NaN,"Armrest, Automatic climate control, 2 zones, A...",NaN,"ABS, Driver-side airbag, Emergency brake assis...",Emergency tyre,NaN,No,NaN,NaN,NaN,4.000,112.000,152.000,NaN,NaN,NaN
28595,Volvo V40,Volvo,"19 rue des Alliés, 57050 Metz, FR",18999.000,Sedan,Used,5.000,12.000,93257.000,Automatic,Diesel,Dealer,5.000,1969.000,NaN,108.000,NaN,NaN,"Armrest, Automatic climate control, 2 zones, A...",NaN,"ABS, Driver-side airbag, Emergency brake assis...",Emergency tyre,NaN,No,NaN,NaN,NaN,4.000,112.000,152.000,NaN,NaN,NaN

## User Defined Functions (DEFs) to fill the missing values

In [ ]:
# User Defined Function for first-looking to the features/columns

def first_looking(col):
    print("COLUMN NAME    : ", col)
    print("--------------------------------")
    print("per_of_nulls   : ", "%", round(df[col].isnull().sum()*100 / df.shape[0], 2))
    print("num_of_nulls   : ", df[col].isnull().sum())
    print("num_of_uniques : ", df[col].nunique())
    print("--------------------------------")
    print(df[col].value_counts(dropna = False))

In [ ]:
def fill_most_freq(df, group_col, col_name):
    
    '''Fills the missing values with the most existing value (mode) in the relevant column according to single-stage grouping'''
    
    for group in list(df[group_col].unique()):
        cond = df[group_col]==group
        mode = list(df[cond][col_name].mode())
        if mode != []:
            df.loc[cond, col_name] = df.loc[cond, col_name].fillna(df[cond][col_name].mode()[0])
        else:
            df.loc[cond, col_name] = df.loc[cond, col_name].fillna(df[col_name].mode()[0])
    
    print("COLUMN NAME    : ", col_name)
    print("--------------------------------")
    print("per_of_nulls   : ", "%", round(df[col_name].isnull().sum()*100 / df.shape[0], 2))
    print("num_of_nulls   : ", df[col_name].isnull().sum())
    print("num_of_uniques : ", df[col_name].nunique())
    print("--------------------------------")
    print(df[col_name].value_counts(dropna = False).sort_index())

In [ ]:
def fill_mode(df, group_col1, group_col2, col_name):
    
    for group1 in list(df[group_col1].unique()):
        for group2 in list(df[group_col2].unique()):
            cond1 = df[group_col1]==group1
            cond2 = (df[group_col1]==group1) & (df[group_col2]==group2)
            mode1 = list(df[cond1][col_name].mode())
            mode2 = list(df[cond2][col_name].mode())
            if mode2 != []:
                df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond2][col_name].mode()[0])
            elif mode1 != []:
                df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond1][col_name].mode()[0])
            else:
                df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[col_name].mode()[0])
    
    print("column name    : ", col_name)
    print("--------------------------------")
    print("per_of_nulls   : ", "%", round(df[col_name].isnull().sum()*100 / df.shape[0], 2))
    print("num_of_nulls   : ", df[col_name].isnull().sum())
    print("num_of_uniques : ", df[col_name].nunique())
    print("--------------------------------")
    print(df[col_name].value_counts(dropna = False))

In [ ]:
def fill_prop(df, group_col, col_name):
    
    '''Fills the missing values with "ffill and bfill method" according to single-stage grouping'''
    
    for group in list(df[group_col].unique()):
        cond = df[group_col]==group
        df.loc[cond, col_name] = df.loc[cond, col_name].fillna(method="ffill").fillna(method="bfill")
    df[col_name] = df[col_name].fillna(method="ffill").fillna(method="bfill")
    
    print("COLUMN NAME    : ", col_name)
    print("--------------------------------")
    print("per_of_nulls   : ", "%", round(df[col_name].isnull().sum()*100 / df.shape[0], 2))
    print("num_of_nulls   : ", df[col_name].isnull().sum())
    print("num_of_uniques : ", df[col_name].nunique())
    print("--------------------------------")
    print(df[col_name].value_counts(dropna = False).sort_index())

In [ ]:
def fill(df, group_col1, group_col2, col_name, method): # method can be either "mode" or "mean" or "median" or "ffill"
    
    '''Fills the missing values with "mode/mean/median/ffill/bfill method" according to double-stage grouping'''
    
    if method == "mode":
        for group1 in list(df[group_col1].unique()):
            for group2 in list(df[group_col2].unique()):
                cond1 = df[group_col1]==group1
                cond2 = (df[group_col1]==group1) & (df[group_col2]==group2)
                mode1 = list(df[cond1][col_name].mode())
                mode2 = list(df[cond2][col_name].mode())
                if mode2 != []:
                    df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond2][col_name].mode()[0])
                elif mode1 != []:
                    df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond1][col_name].mode()[0])
                else:
                    df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[col_name].mode()[0])

    elif method == "mean":
        df[col_name].fillna(df.groupby([group_col1, group_col2])[col_name].transform("mean"), inplace = True)
        df[col_name].fillna(df.groupby(group_col1)[col_name].transform("mean"), inplace = True)
        df[col_name].fillna(df[col_name].mean(), inplace = True)
        
    elif method == "median":
        df[col_name].fillna(df.groupby([group_col1, group_col2])[col_name].transform("median"), inplace = True)
        df[col_name].fillna(df.groupby(group_col1)[col_name].transform("median"), inplace = True)
        df[col_name].fillna(df[col_name].median(), inplace = True)
        
    elif method == "ffill":           
        for group1 in list(df[group_col1].unique()):
            for group2 in list(df[group_col2].unique()):
                cond2 = (df[group_col1]==group1) & (df[group_col2]==group2)
                df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(method="ffill").fillna(method="bfill")
                
        for group1 in list(df[group_col1].unique()):
            cond1 = df[group_col1]==group1
            df.loc[cond1, col_name] = df.loc[cond1, col_name].fillna(method="ffill").fillna(method="bfill")            
           
        df[col_name] = df[col_name].fillna(method="ffill").fillna(method="bfill")
    
    print("COLUMN NAME    : ", col_name)
    print("--------------------------------")
    print("per_of_nulls   : ", "%", round(df[col_name].isnull().sum()*100 / df.shape[0], 2))
    print("num_of_nulls   : ", df[col_name].isnull().sum())
    print("num_of_uniques : ", df[col_name].nunique())
    print("--------------------------------")
    print(df[col_name].value_counts(dropna = False).sort_index())

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">The Examination of Missing Values in the Columns</p>

<a id="2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### ⚠️ 🔥 SPECIAL NOTE:

Before we start our analysis and move forward, it is useful to underline one point.<br>
In this analysis, according to the **``Domain Knowledge``** we obtained, the **``make_model``** & **``body_type``** features will be referenced when filling in missing values, since these features are thought to have more or less influence on the formation of other features, either directly or indirectly.

So, at the begining we need to a close look at these features if they have missing values; if so, let us decide how to handle them:

In [ ]:
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

In [ ]:
df_notnull = df[df.columns[~df.isnull().any()]]
df_notnull.columns

Index(['make_model', 'make', 'location', 'price', 'body_type', 'type',
       'seller', 'full_service_history'],
      dtype='object')

In [ ]:
for col in df_notnull.columns:
    print(first_looking(col))
    print()

COLUMN NAME    :  make_model
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  611
--------------------------------
Renault Megane              863
SEAT Leon                   787
Volvo V40                   740
Dacia Sandero               730
Hyundai i30                 706
Volvo C70                   692
Opel Astra                  675
Ford Mustang                663
Peugeot 308                 537
Ford Focus                  495
Nissan Qashqai              490
SEAT Ibiza                  442
Fiat 500                    440
Fiat Tipo                   430
Renault Clio                417
Ford Fiesta                 400
Nissan Micra                390
Fiat 500X                   376
Skoda Octavia               371
Opel Corsa                  366
Volvo XC60                  364
Dacia Duster                349
Toyota Yaris                332
Volvo V60                   309
Opel Insignia               290
Peugeot 208                 262
Skoda Fabia                 251
Fiat 500C                   249
Volvo C30                   231
Toyota Auris                231
Peugeot RCZ                 220
Hyundai TUCSON              218
Peugeot 3008                217
Volvo XC90                  210
Ford Kuga                   210
Volvo V90                   208
Toyota Corolla              203
Volvo XC40                  202
Dacia Logan                 199
Peugeot 508                 194
Skoda Scala                 191
Skoda Superb                190
SEAT Ateca                  183
SEAT Arona                  170
Hyundai i20                 165
Fiat Coupe                  161
Renault Captur              157
Ford Mondeo                 156
Nissan 370Z                 154
Skoda Kodiaq                154
Toyota C-HR                 150
Skoda Karoq                 150
Peugeot 206                 150
Renault Talisman            144
Peugeot 207                 144
Peugeot 2008                144
Toyota MR 2                 141
Opel Grandland X            140
Renault Kadjar              129
Toyota Aygo                 128
Volvo S60                   126
Opel Cascada                125
Mercedes-Benz A 180         123
Nissan X-Trail              122
Nissan 350Z                 121
Fiat Panda                  120
Volvo S90                   117
Toyota Celica               117
Toyota RAV 4                115
Opel Adam                   114
Nissan Pulsar               113
Hyundai IONIQ               104
Opel                        103
Nissan Juke                 101
Toyota Land Cruiser          98
Fiat 124 Spider              96
Hyundai i10                  96
Peugeot 307                  95
Toyota Supra                 94
Fiat 500L                    93
Renault Twingo               92
Opel Crossland X             91
Renault ZOE                  89
Skoda Kamiq                  89
Volvo V90 Cross Country      88
Renault Laguna               88
Mercedes-Benz C 200          86
Dacia Jogger                 86
Mercedes-Benz A 200          86
Mercedes-Benz C 220          84
Toyota GT86                  84
Hyundai i40                  82
Nissan GT-R                  82
Peugeot 5008                 79
Peugeot 407                  78
Hyundai KONA                 78
Toyota Avensis               77
Opel Mokka                   75
Opel GT                      74
Skoda Rapid/Spaceback        73
Dacia Lodgy                  72
Mercedes-Benz A 45 AMG       72
Mercedes-Benz AMG GT         70
Peugeot 108                  67
Ford Puma                    66
Hyundai Coupe                64
Renault Arkana               64
Toyota Aygo X                63
Nissan Leaf                  61
Mercedes-Benz C 300          61
Mercedes-Benz E 220          61
Hyundai VELOSTER             59
SEAT Tarraco                 57
Skoda Citigo                 57
Dacia Dokker                 56
Mercedes-Benz C 63 AMG       55
Hyundai SANTA FE             52
Mercedes-Benz E 200          51
Nissan Townstar              50
Renault Koleos               49
Opel Tigra                   49
Fiat 500e                    49
Fiat Punto                   49
Nissan Note                  48
Mercedes-Benz E 300          48
Opel Calibra                 47
Mercedes-Benz C 180          47
Volvo V60 Cross Country      47
Renault Wind                 46
Mercedes-Benz E 400          45
Volvo V40 Cross Country      45
Hyundai iX20                 45
Mercedes-Benz A 250          44
Mercedes-Benz C 43 AMG       43
Volvo V70                    43
Mercedes-Benz E 350          42
Renault Alpine A110          41
Opel Mokka X                 40
Dacia Spring                 39
Mercedes-Benz CLA 200        37
Mercedes-Benz SLK 200        37
Mercedes-Benz GLC 220        36
Ford Ranger                  36
Toyota Yaris Cross           36
Hyundai BAYON                35
Nissan Primera               35
Nissan Skyline               35
Fiat Barchetta               33
Ford Edge                    33
Ford EcoSport                33
Volvo 480                    32
Toyota Prius                 32
Opel Crossland               32
Mercedes-Benz A 35 AMG       31
Mercedes-Benz                31
SEAT Mii                     31
Opel Grandland               30
Ford Ka/Ka+                  30
Volvo P1800                  30
Mercedes-Benz CL             30
Mercedes-Benz EQS            29
Mercedes-Benz C 400          29
Volvo XC70                   29
Peugeot 406                  29
Fiat                         28
Mercedes-Benz CLA 45 AMG     27
Hyundai Genesis              27
Nissan 300 ZX                26
Fiat 500 Abarth              26
Mercedes-Benz E 53 AMG       26
Hyundai ELANTRA              25
Mercedes-Benz CLS 350        25
Mercedes-Benz SL 500         25
Mercedes-Benz GLC 300        25
Hyundai iX35                 24
Volvo S40                    24
Nissan Murano                24
Mercedes-Benz S 500          24
Mercedes-Benz CLA 180        24
Mercedes-Benz GLC 63 AMG     23
Mercedes-Benz E 250          23
Mercedes-Benz E 63 AMG       22
Mercedes-Benz C 250          22
Volvo S80                    22
Volvo                        22
Toyota Hilux                 22
Opel Manta                   22
Nissan NV200                 21
Fiat Punto Evo               21
Nissan 200 SX                21
Mercedes-Benz GLC 43 AMG     21
Mercedes-Benz A 220          21
Peugeot 107                  21
Mercedes-Benz GLC 250        21
Mercedes-Benz S 63 AMG       20
Ford Mustang Mach-E          20
Toyota Verso                 19
Peugeot 205                  19
Opel Karl                    19
Nissan Navara                19
Ford                         19
Ford Tourneo Custom          18
Mercedes-Benz GLE 400        18
Mercedes-Benz S 350          18
Skoda Yeti                   18
Peugeot Rifter               18
Volvo 262                    18
Renault R 19                 17
Mercedes-Benz G 63 AMG       17
Skoda Enyaq                  17
SEAT Toledo                  17
Toyota                       16
Renault                      16
Mercedes-Benz A 160          16
Peugeot 306                  16
Mercedes-Benz EQC 400        16
Mercedes-Benz CLA 220        16
Mercedes-Benz S 400          16
Mercedes-Benz GLA 200        16
SEAT Alhambra                15
Mercedes-Benz S 580          15
Nissan Almera Tino           15
Mercedes-Benz SL 350         15
Hyundai IONIQ 5              14
Toyota Proace                14
Mercedes-Benz GLC 350        14
Nissan Almera                14
Opel Kadett                  14
Mercedes-Benz GLE 350        14
Hyundai                      14
Nissan Primastar             13
Ford Escort                  13
Renault Grand Scenic         13
Mercedes-Benz GLA 220        13
Volvo 240                    13
Mercedes-Benz CLS 400        13
Fiat Grande Punto            13
SEAT Altea XL                12
Ford Explorer                12
Fiat Dino                    12
Nissan                       12
Renault Twizy                12
Mercedes-Benz SLC 200        11
Fiat 850                     11
Mercedes-Benz EQE 350        11
Mercedes-Benz CLA 250        11
Fiat 124 Coupè               11
Fiat Fullback                11
Renault Trafic               11
Fiat New Panda               11
Mercedes-Benz GLC 200        11
Mercedes-Benz E 450          11
Mercedes-Benz GLE 300        11
Ford Transit Connect         10
Mercedes-Benz GLA 180        10
Volvo V50                    10
Volvo Amazon                 10
Mercedes-Benz GLC 400        10
Opel Speedster               10
Ford S-Max                   10
Mercedes-Benz G 500          10
Hyundai Getz                 10
Renault Alpine V6            10
Renault Kangoo               10
Renault Alpine A310          10
Nissan Terrano               10
Nissan 100 NX                10
Ford Thunderbird             10
Mercedes-Benz ML 350         10
Toyota iQ                    10
Fiat Freemont                10
Renault Spider               10
Ford Focus CC                10
Hyundai Genesis Coupe        10
Nissan NV300                  9
Renault Espace                9
Peugeot Partner               9
Fiat 130                      9
Mercedes-Benz GLS 400         9
Mercedes-Benz CLA 35 AMG      8
Toyota Mirai                  8
Mercedes-Benz S 560           8
Toyota Paseo                  8
Mercedes-Benz CLS 53 AMG      8
Mercedes-Benz CLS 450         8
Mercedes-Benz SL 63 AMG       8
Mercedes-Benz SLK 250         8
Fiat 595 Abarth               8
Fiat Qubo                     8
SEAT Altea                    8
Nissan Qashqai+2              8
Ford GT                       8
Nissan Pathfinder             8
Opel Monza                    8
Mercedes-Benz GLA 45 AMG      8
Mercedes-Benz G 350           8
Peugeot e-2008                7
Mercedes-Benz B 180           7
Hyundai ACCENT                7
Mercedes-Benz SLC 43 AMG      7
Opel Vivaro                   7
Nissan Patrol                 7
Mercedes-Benz B 200           7
Ford B-Max                    7
Ford Bronco                   7
Mercedes-Benz ML 63 AMG       7
Opel Vectra                   7
Toyota Camry                  7
Mercedes-Benz GLE 53 AMG      7
Mercedes-Benz CL 500          7
Mercedes-Benz C 350           7
Renault Alaskan               7
Mercedes-Benz GLE 63 AMG      7
Nissan Sunny                  7
Mercedes-Benz SLK 230         6
Mercedes-Benz 220             6
Fiat Bravo                    6
Toyota FJ Cruiser             6
Toyota Highlander             6
Mercedes-Benz E 43 AMG        6
Ford Streetka                 6
Peugeot 1007                  6
Renault Megane E-Tech         6
Mercedes-Benz EQB 350         6
Mercedes-Benz CLK 200         6
Peugeot 504                   6
Mercedes-Benz CLS 250         6
Opel Combo                    6
Mercedes-Benz CLS 500         6
Mercedes-Benz GLB 200         6
Hyundai Terracan              5
Mercedes-Benz SL 600          5
Dacia                         5
Mercedes-Benz G 400           5
Fiat 600                      5
Mercedes-Benz ML 500          5
Fiat Uno                      5
Mercedes-Benz SLK 55 AMG      5
Fiat Sedici                   5
SEAT Cordoba                  5
Opel Antara                   5
Fiat Spider Europa            5
Peugeot                       5
Ford Transit                  5
Ford F 150                    5
Opel Rekord                   5
Ford Tourneo Connect          5
Opel Zafira Life              5
Mercedes-Benz SLK 350         5
Peugeot e-208                 5
Mercedes-Benz EQE 43          5
Nissan Datsun                 5
Renault Scenic                5
Hyundai NEXO                  5
Mercedes-Benz GLS 350         5
Mercedes-Benz SL 280          5
Mercedes-Benz SL 300          5
Mercedes-Benz 190             4
Mercedes-Benz CLS             4
Mercedes-Benz C 160           4
Mercedes-Benz G               4
Nissan E-NV200                4
Volvo 780                     4
Renault R 5                   4
Mercedes-Benz V 250           4
Volvo PV544                   4
SEAT                          4
Renault R 9                   4
SEAT Exeo                     4
Volvo C40                     4
Mercedes-Benz ML 320          4
SEAT Arosa                    4
Mercedes-Benz S 450           4
Mercedes-Benz V 300           4
Nissan Silvia                 4
Opel Meriva                   4
Fiat 126                      4
Mercedes-Benz GLE 500         4
Mercedes-Benz EQA             4
Hyundai SONATA                4
Opel Corsa-e                  4
Mercedes-Benz GLE 250         4
Ford Tourneo Courier          4
Mercedes-Benz G 230           4
Fiat 131                      4
Mercedes-Benz GLB 35 AMG      4
Mercedes-Benz GLE 580         4
Fiat 128                      4
Mercedes-Benz GLE 43 AMG      4
Volvo 960                     4
Peugeot 106                   4
Mercedes-Benz GLE 450         3
Ford Cougar                   3
Toyota Coaster                3
Mercedes-Benz SL 320          3
Mercedes-Benz SL 400          3
Nissan Cube                   3
Ford Ranger Raptor            3
Ford Transit Custom           3
Toyota FJ40                   3
Nissan Figaro                 3
Nissan Titan                  3
Mercedes-Benz SLC 180         3
Mercedes-Benz 320             3
Mercedes-Benz SLK 280         3
Ford Probe                    3
Mercedes-Benz EQA 250         3
Mercedes-Benz GLA 250         3
Mercedes-Benz SLC 250         3
Mercedes-Benz S 300           3
Mercedes-Benz E 240           3
Mercedes-Benz 280             3
Mercedes-Benz ML 250          3
Mercedes-Benz A 150           3
Renault R 4                   3
Fiat Seicento                 3
Mercedes-Benz 500             3
Fiat Stilo                    3
Mercedes-Benz V 220           3
Mercedes-Benz GLB 250         3
Mercedes-Benz C 36 AMG        3
Peugeot 607                   3
Renault Fluence               3
Mercedes-Benz E 280           3
Fiat Croma                    3
Mercedes-Benz GLK 250         3
SEAT Leon e-Hybrid            3
Peugeot 404                   3
Mercedes-Benz SL 55 AMG       3
Skoda Felicia                 3
Peugeot Expert                3
Mercedes-Benz X 250           3
Mercedes-Benz E 500           3
Mercedes-Benz 230             3
Opel Commodore                3
Mercedes-Benz GLK 350         3
Mercedes-Benz GLK 220         3
Volvo S70                     3
Mercedes-Benz GL 350          3
Peugeot 309                   3
Renault Avantime              3
Mercedes-Benz CLS 63 AMG      2
Mercedes-Benz EQV 300         2
Renault Fuego                 2
Renault P 1400                2
Renault R 21                  2
Mercedes-Benz B 220           2
Mercedes-Benz B 250           2
Renault Kangoo Z.E.           2
Mercedes-Benz SLS             2
Opel Movano                   2
Nissan Stagea                 2
Volvo 850                     2
Opel Agila                    2
Ford Galaxy                   2
Ford Fairlane                 2
Volvo 945                     2
Ford M                        2
Mercedes-Benz E 230           2
Volvo 740                     2
Ford Mercury                  2
Nissan Evalia                 2
Opel Frontera                 2
Ford Sierra                   2
Ford Capri                    2
Opel Zafira                   2
Nissan Pixo                   2
Mercedes-Benz S 600           2
Ford Maverick                 2
Mercedes-Benz SL 65 AMG       2
Hyundai Atos                  2
Mercedes-Benz SLK 300         2
Hyundai STARIA                2
Mercedes-Benz GLK 200         2
Hyundai H-1                   2
Fiat X 1/9                    2
Mercedes-Benz CL 600          2
Fiat 127                      2
Fiat Ritmo                    2
Fiat Talento                  2
Hyundai S-Coupe               2
Hyundai Tiburon               2
Toyota Verso-S                2
Mercedes-Benz CLK             2
Mercedes-Benz GLB 220         2
Toyota Urban Cruiser          2
Mercedes-Benz CLK 55 AMG      2
Hyundai Excel                 2
Mercedes-Benz SLK             2
Mercedes-Benz GL 63 AMG       2
Fiat Fiorino                  2
Fiat Strada                   2
Ford C-Max                    2
Nissan 280 ZX                 2
Mercedes-Benz GL 500          2
Peugeot 4007                  2
Peugeot 305                   2
Peugeot Ranch                 2
Nissan Tiida                  2
Peugeot 4008                  2
Mercedes-Benz CLK 320         2
Toyota Corolla Verso          2
Peugeot Traveller             2
Mercedes-Benz CLK 500         2
Hyundai H 350                 1
Ford Grand Tourneo            1
Volvo 440                     1
Mercedes-Benz Viano           1
Hyundai Trajet                1
Ford Grand C-Max              1
Ford Gran Torino              1
Ford Transit Courier          1
Mercedes-Benz SL 560          1
Hyundai Lantra                1
Mercedes-Benz SL 380          1
Hyundai Grand Santa Fe        1
Hyundai KONA Elektro          1
Mercedes-Benz A 140           1
Hyundai Matrix                1
Opel Ampera                   1
Mercedes-Benz 250             1
Renault Latitude              1
Renault R 18                  1
Renault Grand Modus           1
Renault R 11                  1
Mercedes-Benz C 32 AMG        1
Mercedes-Benz Sprinter        1
Mercedes-Benz G 65 AMG        1
Mercedes-Benz ML 280          1
Mercedes-Benz 170             1
Mercedes-Benz GLS 63 AMG      1
Mercedes-Benz GL 320          1
Peugeot iOn                   1
Peugeot 304                   1
Mercedes-Benz GLB 180         1
Peugeot Bipper                1
Peugeot 505                   1
Peugeot 301                   1
Peugeot Boxer                 1
Mercedes-Benz EQB 300         1
Mercedes-Benz GL 420          1
Renault Safrane               1
Renault Grand Espace          1
Fiat Brava                    1
Renault Express               1
Mercedes-Benz 260             1
Opel Ascona                   1
Mercedes-Benz S 420           1
Mercedes-Benz EQE 500         1
Opel Monterey                 1
Mercedes-Benz E 320           1
Mercedes-Benz C 320           1
Opel Mokka-E                  1
Opel Zafira Tourer            1
Opel Combo Life               1
Opel Senator                  1
Mercedes-Benz S 55 AMG        1
Mercedes-Benz CLS 280         1
Mercedes-Benz C 280           1
Renault Coupe                 1
Mercedes-Benz Vito            1
Renault Super 5               1
Renault Alpine A610           1
Renault Master                1
Mercedes-Benz G 55 AMG        1
Mercedes-Benz GLA 35 AMG      1
Mercedes-Benz CLK 350         1
Toyota Aristo                 1
Mercedes-Benz CLS 320         1
Mercedes-Benz 450             1
Mercedes-Benz CLK 63 AMG      1
Mercedes-Benz CL 63 AMG       1
Mercedes-Benz 200             1
Nissan Ariya                  1
Mercedes-Benz CLK 230         1
Mercedes-Benz CLK 240         1
Nissan King Cab               1
Mercedes-Benz SL 450          1
Mercedes-Benz CLK 280         1
Nissan NV250                  1
Nissan Rogue                  1
Nissan NV400                  1
Nissan Gloria                 1
Mercedes-Benz SLR             1
Ford F 250                    1
Mercedes-Benz G 320           1
Mercedes-Benz SLC 300         1
Toyota Prius+                 1
Toyota Crown                  1
Mercedes-Benz ML 400          1
Toyota Sienna                 1
Fiat Cinquecento              1
Fiat Doblo                    1
Fiat Multipla                 1
SEAT Marbella                 1
Mercedes-Benz R 300           1
Mercedes-Benz ML 300          1
Mercedes-Benz ML 450          1
Skoda 105                     1
Skoda                         1
Dacia Break                   1
Mercedes-Benz E 50 AMG        1
Mercedes-Benz CLS 300         1
Mercedes-Benz S 65 AMG        1
Mercedes-Benz 350             1
Toyota Starlet                1
Toyota GR86                   1
Toyota Tacoma                 1
Toyota Tundra                 1
Toyota 4-Runner               1
Volvo 244                     1
Name: make_model, dtype: int64
None

COLUMN NAME    :  make
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  13
--------------------------------
Volvo            3659
Mercedes-Benz    2398
Opel             2385
Peugeot          2360

Among the features above, **``Domain Knowledge``**,  **``make_model``** & **``body_type``** are the critical/crucial ones to impute the missing values. Therefore let's take a close look at them one by one:

## make_model

In [ ]:
first_looking("make_model")

COLUMN NAME    :  make_model
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  611
--------------------------------
Renault Megane              863
SEAT Leon                   787
Volvo V40                   740
Dacia Sandero               730
Hyundai i30                 706
Volvo C70                   692
Opel Astra                  675
Ford Mustang                663
Peugeot 308                 537
Ford Focus                  495
Nissan Qashqai              490
SEAT Ibiza                  442
Fiat 500                    440
Fiat Tipo                   430
Renault Clio                417
Ford Fiesta                 400
Nissan Micra                390
Fiat 500X                   376
Skoda Octavia               371
Opel Corsa                  366
Volvo XC60                  364
Dacia Duster                349
Toyota Yaris                332
Volvo V60                   309
Opel Insignia               290
Peugeot 208                 262
Skoda Fabia                 251
Fiat 500C                   249
Volvo C30                   231
Toyota Auris                231
Peugeot RCZ                 220
Hyundai TUCSON              218
Peugeot 3008                217
Volvo XC90                  210
Ford Kuga                   210
Volvo V90                   208
Toyota Corolla              203
Volvo XC40                  202
Dacia Logan                 199
Peugeot 508                 194
Skoda Scala                 191
Skoda Superb                190
SEAT Ateca                  183
SEAT Arona                  170
Hyundai i20                 165
Fiat Coupe                  161
Renault Captur              157
Ford Mondeo                 156
Nissan 370Z                 154
Skoda Kodiaq                154
Toyota C-HR                 150
Skoda Karoq                 150
Peugeot 206                 150
Renault Talisman            144
Peugeot 207                 144
Peugeot 2008                144
Toyota MR 2                 141
Opel Grandland X            140
Renault Kadjar              129
Toyota Aygo                 128
Volvo S60                   126
Opel Cascada                125
Mercedes-Benz A 180         123
Nissan X-Trail              122
Nissan 350Z                 121
Fiat Panda                  120
Volvo S90                   117
Toyota Celica               117
Toyota RAV 4                115
Opel Adam                   114
Nissan Pulsar               113
Hyundai IONIQ               104
Opel                        103
Nissan Juke                 101
Toyota Land Cruiser          98
Fiat 124 Spider              96
Hyundai i10                  96
Peugeot 307                  95
Toyota Supra                 94
Fiat 500L                    93
Renault Twingo               92
Opel Crossland X             91
Renault ZOE                  89
Skoda Kamiq                  89
Volvo V90 Cross Country      88
Renault Laguna               88
Mercedes-Benz C 200          86
Dacia Jogger                 86
Mercedes-Benz A 200          86
Mercedes-Benz C 220          84
Toyota GT86                  84
Hyundai i40                  82
Nissan GT-R                  82
Peugeot 5008                 79
Peugeot 407                  78
Hyundai KONA                 78
Toyota Avensis               77
Opel Mokka                   75
Opel GT                      74
Skoda Rapid/Spaceback        73
Dacia Lodgy                  72
Mercedes-Benz A 45 AMG       72
Mercedes-Benz AMG GT         70
Peugeot 108                  67
Ford Puma                    66
Hyundai Coupe                64
Renault Arkana               64
Toyota Aygo X                63
Nissan Leaf                  61
Mercedes-Benz C 300          61
Mercedes-Benz E 220          61
Hyundai VELOSTER             59
SEAT Tarraco                 57
Skoda Citigo                 57
Dacia Dokker                 56
Mercedes-Benz C 63 AMG       55
Hyundai SANTA FE             52
Mercedes-Benz E 200          51
Nissan Townstar              50
Renault Koleos               49
Opel Tigra                   49
Fiat 500e                    49
Fiat Punto                   49
Nissan Note                  48
Mercedes-Benz E 300          48
Opel Calibra                 47
Mercedes-Benz C 180          47
Volvo V60 Cross Country      47
Renault Wind                 46
Mercedes-Benz E 400          45
Volvo V40 Cross Country      45
Hyundai iX20                 45
Mercedes-Benz A 250          44
Mercedes-Benz C 43 AMG       43
Volvo V70                    43
Mercedes-Benz E 350          42
Renault Alpine A110          41
Opel Mokka X                 40
Dacia Spring                 39
Mercedes-Benz CLA 200        37
Mercedes-Benz SLK 200        37
Mercedes-Benz GLC 220        36
Ford Ranger                  36
Toyota Yaris Cross           36
Hyundai BAYON                35
Nissan Primera               35
Nissan Skyline               35
Fiat Barchetta               33
Ford Edge                    33
Ford EcoSport                33
Volvo 480                    32
Toyota Prius                 32
Opel Crossland               32
Mercedes-Benz A 35 AMG       31
Mercedes-Benz                31
SEAT Mii                     31
Opel Grandland               30
Ford Ka/Ka+                  30
Volvo P1800                  30
Mercedes-Benz CL             30
Mercedes-Benz EQS            29
Mercedes-Benz C 400          29
Volvo XC70                   29
Peugeot 406                  29
Fiat                         28
Mercedes-Benz CLA 45 AMG     27
Hyundai Genesis              27
Nissan 300 ZX                26
Fiat 500 Abarth              26
Mercedes-Benz E 53 AMG       26
Hyundai ELANTRA              25
Mercedes-Benz CLS 350        25
Mercedes-Benz SL 500         25
Mercedes-Benz GLC 300        25
Hyundai iX35                 24
Volvo S40                    24
Nissan Murano                24
Mercedes-Benz S 500          24
Mercedes-Benz CLA 180        24
Mercedes-Benz GLC 63 AMG     23
Mercedes-Benz E 250          23
Mercedes-Benz E 63 AMG       22
Mercedes-Benz C 250          22
Volvo S80                    22
Volvo                        22
Toyota Hilux                 22
Opel Manta                   22
Nissan NV200                 21
Fiat Punto Evo               21
Nissan 200 SX                21
Mercedes-Benz GLC 43 AMG     21
Mercedes-Benz A 220          21
Peugeot 107                  21
Mercedes-Benz GLC 250        21
Mercedes-Benz S 63 AMG       20
Ford Mustang Mach-E          20
Toyota Verso                 19
Peugeot 205                  19
Opel Karl                    19
Nissan Navara                19
Ford                         19
Ford Tourneo Custom          18
Mercedes-Benz GLE 400        18
Mercedes-Benz S 350          18
Skoda Yeti                   18
Peugeot Rifter               18
Volvo 262                    18
Renault R 19                 17
Mercedes-Benz G 63 AMG       17
Skoda Enyaq                  17
SEAT Toledo                  17
Toyota                       16
Renault                      16
Mercedes-Benz A 160          16
Peugeot 306                  16
Mercedes-Benz EQC 400        16
Mercedes-Benz CLA 220        16
Mercedes-Benz S 400          16
Mercedes-Benz GLA 200        16
SEAT Alhambra                15
Mercedes-Benz S 580          15
Nissan Almera Tino           15
Mercedes-Benz SL 350         15
Hyundai IONIQ 5              14
Toyota Proace                14
Mercedes-Benz GLC 350        14
Nissan Almera                14
Opel Kadett                  14
Mercedes-Benz GLE 350        14
Hyundai                      14
Nissan Primastar             13
Ford Escort                  13
Renault Grand Scenic         13
Mercedes-Benz GLA 220        13
Volvo 240                    13
Mercedes-Benz CLS 400        13
Fiat Grande Punto            13
SEAT Altea XL                12
Ford Explorer                12
Fiat Dino                    12
Nissan                       12
Renault Twizy                12
Mercedes-Benz SLC 200        11
Fiat 850                     11
Mercedes-Benz EQE 350        11
Mercedes-Benz CLA 250        11
Fiat 124 Coupè               11
Fiat Fullback                11
Renault Trafic               11
Fiat New Panda               11
Mercedes-Benz GLC 200        11
Mercedes-Benz E 450          11
Mercedes-Benz GLE 300        11
Ford Transit Connect         10
Mercedes-Benz GLA 180        10
Volvo V50                    10
Volvo Amazon                 10
Mercedes-Benz GLC 400        10
Opel Speedster               10
Ford S-Max                   10
Mercedes-Benz G 500          10
Hyundai Getz                 10
Renault Alpine V6            10
Renault Kangoo               10
Renault Alpine A310          10
Nissan Terrano               10
Nissan 100 NX                10
Ford Thunderbird             10
Mercedes-Benz ML 350         10
Toyota iQ                    10
Fiat Freemont                10
Renault Spider               10
Ford Focus CC                10
Hyundai Genesis Coupe        10
Nissan NV300                  9
Renault Espace                9
Peugeot Partner               9
Fiat 130                      9
Mercedes-Benz GLS 400         9
Mercedes-Benz CLA 35 AMG      8
Toyota Mirai                  8
Mercedes-Benz S 560           8
Toyota Paseo                  8
Mercedes-Benz CLS 53 AMG      8
Mercedes-Benz CLS 450         8
Mercedes-Benz SL 63 AMG       8
Mercedes-Benz SLK 250         8
Fiat 595 Abarth               8
Fiat Qubo                     8
SEAT Altea                    8
Nissan Qashqai+2              8
Ford GT                       8
Nissan Pathfinder             8
Opel Monza                    8
Mercedes-Benz GLA 45 AMG      8
Mercedes-Benz G 350           8
Peugeot e-2008                7
Mercedes-Benz B 180           7
Hyundai ACCENT                7
Mercedes-Benz SLC 43 AMG      7
Opel Vivaro                   7
Nissan Patrol                 7
Mercedes-Benz B 200           7
Ford B-Max                    7
Ford Bronco                   7
Mercedes-Benz ML 63 AMG       7
Opel Vectra                   7
Toyota Camry                  7
Mercedes-Benz GLE 53 AMG      7
Mercedes-Benz CL 500          7
Mercedes-Benz C 350           7
Renault Alaskan               7
Mercedes-Benz GLE 63 AMG      7
Nissan Sunny                  7
Mercedes-Benz SLK 230         6
Mercedes-Benz 220             6
Fiat Bravo                    6
Toyota FJ Cruiser             6
Toyota Highlander             6
Mercedes-Benz E 43 AMG        6
Ford Streetka                 6
Peugeot 1007                  6
Renault Megane E-Tech         6
Mercedes-Benz EQB 350         6
Mercedes-Benz CLK 200         6
Peugeot 504                   6
Mercedes-Benz CLS 250         6
Opel Combo                    6
Mercedes-Benz CLS 500         6
Mercedes-Benz GLB 200         6
Hyundai Terracan              5
Mercedes-Benz SL 600          5
Dacia                         5
Mercedes-Benz G 400           5
Fiat 600                      5
Mercedes-Benz ML 500          5
Fiat Uno                      5
Mercedes-Benz SLK 55 AMG      5
Fiat Sedici                   5
SEAT Cordoba                  5
Opel Antara                   5
Fiat Spider Europa            5
Peugeot                       5
Ford Transit                  5
Ford F 150                    5
Opel Rekord                   5
Ford Tourneo Connect          5
Opel Zafira Life              5
Mercedes-Benz SLK 350         5
Peugeot e-208                 5
Mercedes-Benz EQE 43          5
Nissan Datsun                 5
Renault Scenic                5
Hyundai NEXO                  5
Mercedes-Benz GLS 350         5
Mercedes-Benz SL 280          5
Mercedes-Benz SL 300          5
Mercedes-Benz 190             4
Mercedes-Benz CLS             4
Mercedes-Benz C 160           4
Mercedes-Benz G               4
Nissan E-NV200                4
Volvo 780                     4
Renault R 5                   4
Mercedes-Benz V 250           4
Volvo PV544                   4
SEAT                          4
Renault R 9                   4
SEAT Exeo                     4
Volvo C40                     4
Mercedes-Benz ML 320          4
SEAT Arosa                    4
Mercedes-Benz S 450           4
Mercedes-Benz V 300           4
Nissan Silvia                 4
Opel Meriva                   4
Fiat 126                      4
Mercedes-Benz GLE 500         4
Mercedes-Benz EQA             4
Hyundai SONATA                4
Opel Corsa-e                  4
Mercedes-Benz GLE 250         4
Ford Tourneo Courier          4
Mercedes-Benz G 230           4
Fiat 131                      4
Mercedes-Benz GLB 35 AMG      4
Mercedes-Benz GLE 580         4
Fiat 128                      4
Mercedes-Benz GLE 43 AMG      4
Volvo 960                     4
Peugeot 106                   4
Mercedes-Benz GLE 450         3
Ford Cougar                   3
Toyota Coaster                3
Mercedes-Benz SL 320          3
Mercedes-Benz SL 400          3
Nissan Cube                   3
Ford Ranger Raptor            3
Ford Transit Custom           3
Toyota FJ40                   3
Nissan Figaro                 3
Nissan Titan                  3
Mercedes-Benz SLC 180         3
Mercedes-Benz 320             3
Mercedes-Benz SLK 280         3
Ford Probe                    3
Mercedes-Benz EQA 250         3
Mercedes-Benz GLA 250         3
Mercedes-Benz SLC 250         3
Mercedes-Benz S 300           3
Mercedes-Benz E 240           3
Mercedes-Benz 280             3
Mercedes-Benz ML 250          3
Mercedes-Benz A 150           3
Renault R 4                   3
Fiat Seicento                 3
Mercedes-Benz 500             3
Fiat Stilo                    3
Mercedes-Benz V 220           3
Mercedes-Benz GLB 250         3
Mercedes-Benz C 36 AMG        3
Peugeot 607                   3
Renault Fluence               3
Mercedes-Benz E 280           3
Fiat Croma                    3
Mercedes-Benz GLK 250         3
SEAT Leon e-Hybrid            3
Peugeot 404                   3
Mercedes-Benz SL 55 AMG       3
Skoda Felicia                 3
Peugeot Expert                3
Mercedes-Benz X 250           3
Mercedes-Benz E 500           3
Mercedes-Benz 230             3
Opel Commodore                3
Mercedes-Benz GLK 350         3
Mercedes-Benz GLK 220         3
Volvo S70                     3
Mercedes-Benz GL 350          3
Peugeot 309                   3
Renault Avantime              3
Mercedes-Benz CLS 63 AMG      2
Mercedes-Benz EQV 300         2
Renault Fuego                 2
Renault P 1400                2
Renault R 21                  2
Mercedes-Benz B 220           2
Mercedes-Benz B 250           2
Renault Kangoo Z.E.           2
Mercedes-Benz SLS             2
Opel Movano                   2
Nissan Stagea                 2
Volvo 850                     2
Opel Agila                    2
Ford Galaxy                   2
Ford Fairlane                 2
Volvo 945                     2
Ford M                        2
Mercedes-Benz E 230           2
Volvo 740                     2
Ford Mercury                  2
Nissan Evalia                 2
Opel Frontera                 2
Ford Sierra                   2
Ford Capri                    2
Opel Zafira                   2
Nissan Pixo                   2
Mercedes-Benz S 600           2
Ford Maverick                 2
Mercedes-Benz SL 65 AMG       2
Hyundai Atos                  2
Mercedes-Benz SLK 300         2
Hyundai STARIA                2
Mercedes-Benz GLK 200         2
Hyundai H-1                   2
Fiat X 1/9                    2
Mercedes-Benz CL 600          2
Fiat 127                      2
Fiat Ritmo                    2
Fiat Talento                  2
Hyundai S-Coupe               2
Hyundai Tiburon               2
Toyota Verso-S                2
Mercedes-Benz CLK             2
Mercedes-Benz GLB 220         2
Toyota Urban Cruiser          2
Mercedes-Benz CLK 55 AMG      2
Hyundai Excel                 2
Mercedes-Benz SLK             2
Mercedes-Benz GL 63 AMG       2
Fiat Fiorino                  2
Fiat Strada                   2
Ford C-Max                    2
Nissan 280 ZX                 2
Mercedes-Benz GL 500          2
Peugeot 4007                  2
Peugeot 305                   2
Peugeot Ranch                 2
Nissan Tiida                  2
Peugeot 4008                  2
Mercedes-Benz CLK 320         2
Toyota Corolla Verso          2
Peugeot Traveller             2
Mercedes-Benz CLK 500         2
Hyundai H 350                 1
Ford Grand Tourneo            1
Volvo 440                     1
Mercedes-Benz Viano           1
Hyundai Trajet                1
Ford Grand C-Max              1
Ford Gran Torino              1
Ford Transit Courier          1
Mercedes-Benz SL 560          1
Hyundai Lantra                1
Mercedes-Benz SL 380          1
Hyundai Grand Santa Fe        1
Hyundai KONA Elektro          1
Mercedes-Benz A 140           1
Hyundai Matrix                1
Opel Ampera                   1
Mercedes-Benz 250             1
Renault Latitude              1
Renault R 18                  1
Renault Grand Modus           1
Renault R 11                  1
Mercedes-Benz C 32 AMG        1
Mercedes-Benz Sprinter        1
Mercedes-Benz G 65 AMG        1
Mercedes-Benz ML 280          1
Mercedes-Benz 170             1
Mercedes-Benz GLS 63 AMG      1
Mercedes-Benz GL 320          1
Peugeot iOn                   1
Peugeot 304                   1
Mercedes-Benz GLB 180         1
Peugeot Bipper                1
Peugeot 505                   1
Peugeot 301                   1
Peugeot Boxer                 1
Mercedes-Benz EQB 300         1
Mercedes-Benz GL 420          1
Renault Safrane               1
Renault Grand Espace          1
Fiat Brava                    1
Renault Express               1
Mercedes-Benz 260             1
Opel Ascona                   1
Mercedes-Benz S 420           1
Mercedes-Benz EQE 500         1
Opel Monterey                 1
Mercedes-Benz E 320           1
Mercedes-Benz C 320           1
Opel Mokka-E                  1
Opel Zafira Tourer            1
Opel Combo Life               1
Opel Senator                  1
Mercedes-Benz S 55 AMG        1
Mercedes-Benz CLS 280         1
Mercedes-Benz C 280           1
Renault Coupe                 1
Mercedes-Benz Vito            1
Renault Super 5               1
Renault Alpine A610           1
Renault Master                1
Mercedes-Benz G 55 AMG        1
Mercedes-Benz GLA 35 AMG      1
Mercedes-Benz CLK 350         1
Toyota Aristo                 1
Mercedes-Benz CLS 320         1
Mercedes-Benz 450             1
Mercedes-Benz CLK 63 AMG      1
Mercedes-Benz CL 63 AMG       1
Mercedes-Benz 200             1
Nissan Ariya                  1
Mercedes-Benz CLK 230         1
Mercedes-Benz CLK 240         1
Nissan King Cab               1
Mercedes-Benz SL 450          1
Mercedes-Benz CLK 280         1
Nissan NV250                  1
Nissan Rogue                  1
Nissan NV400                  1
Nissan Gloria                 1
Mercedes-Benz SLR             1
Ford F 250                    1
Mercedes-Benz G 320           1
Mercedes-Benz SLC 300         1
Toyota Prius+                 1
Toyota Crown                  1
Mercedes-Benz ML 400          1
Toyota Sienna                 1
Fiat Cinquecento              1
Fiat Doblo                    1
Fiat Multipla                 1
SEAT Marbella                 1
Mercedes-Benz R 300           1
Mercedes-Benz ML 300          1
Mercedes-Benz ML 450          1
Skoda 105                     1
Skoda                         1
Dacia Break                   1
Mercedes-Benz E 50 AMG        1
Mercedes-Benz CLS 300         1
Mercedes-Benz S 65 AMG        1
Mercedes-Benz 350             1
Toyota Starlet                1
Toyota GR86                   1
Toyota Tacoma                 1
Toyota Tundra                 1
Toyota 4-Runner               1
Volvo 244                     1
Name: make_model, dtype: int64

## make

In [ ]:
first_looking("make")

COLUMN NAME    :  make
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  13
--------------------------------
Volvo            3659
Mercedes-Benz    2398
Opel             2385
Peugeot          2360
Renault          2351
Fiat             2338
Ford             2324
Nissan           2064
Toyota           2038
Hyundai          1867
SEAT             1743
Skoda            1566
Dacia            1537
Name: make, dtype: int64

## body_type

In [ ]:
first_looking("body_type")

COLUMN NAME    :  body_type
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  6
--------------------------------
Station wagon       5448
Off-Road/Pick-up    5415
Compact             5387
Sedan               5043
Coupe               4009
Convertible         3328
Name: body_type, dtype: int64

### Now it's time to examine and fill the missing values of each column/feature one by one:

In [ ]:
df_isnull = df[df.columns[df.isnull().any()]]
df_isnull.columns

Index(['doors', 'warranty', 'mileage', 'gearbox', 'fuel_type', 'seats',
       'engine_size', 'gears', 'co_emissions', 'drivetrain', 'cylinders',
       'comfort_&_convenience', 'entertainment_&_media', 'safety_&_security',
       'extras', 'empty_weight', 'upholstery', 'previous_owner',
       'energy_efficiency_class', 'age', 'power_kW', 'power_hp', 'cons_avg',
       'cons_city', 'cons_country'],
      dtype='object')

## engine_size

In [ ]:
first_looking("engine_size")

COLUMN NAME    :  engine_size
--------------------------------
per_of_nulls   :  % 4.9
num_of_nulls   :  1403
num_of_uniques :  467
--------------------------------
1598.000     2099
999.000      2068
1969.000     1929
NaN          1403
1461.000     1110
1998.000     1000
998.000       925
1199.000      867
1498.000      782
1997.000      665
1968.000      625
1984.000      580
1332.000      510
1798.000      473
1560.000      472
898.000       405
1499.000      397
1197.000      382
1242.000      373
1995.000      352
1991.000      351
1368.000      348
1248.000      322
2435.000      302
1600.000      252
2143.000      242
1364.000      226
1500.000      210
5038.000      204
3982.000      203
1950.000      202
1591.000      201
1956.000      195
2000.000      191
3498.000      175
1395.000      174
1987.000      159
1149.000      157
1796.000      156
3696.000      154
1200.000      153
1490.000      152
1198.000      149
1497.000      149
2400.000      148
1999.000      145
2996.000      145
1398.000      143
1794.000      138
1496.000      137
1618.000      128
1482.000      127
1582.000      125
0.000         117
2925.000      117
875.000       112
1587.000      110
1595.000      109
1596.000      106
2987.000      105
1400.000      104
2261.000      101
1000.000       99
1333.000       94
1685.000       92
1580.000       91
2521.000       91
1362.000       90
1390.000       90
4951.000       89
2999.000       86
1477.000       85
3799.000       76
1747.000       69
1229.000       63
2755.000       62
1300.000       60
1396.000       59
1870.000       55
1397.000       54
2319.000       53
900.000        53
2998.000       52
2300.000       52
1399.000       52
5461.000       51
1353.000       50
1386.000       48
1800.000       43
2401.000       43
2500.000       42
1597.000       41
2488.000       40
1422.000       39
1084.000       38
2494.000       38
2487.000       37
2198.000       35
1975.000       35
1769.000       34
1599.000       32
4663.000       31
1749.000       31
2199.000       31
1.000          30
1360.000       28
1686.000       28
1896.000       28
1329.000       27
1910.000       27
2946.000       23
2231.000       22
2230.000       21
1721.000       21
5000.000       21
2982.000       21
2960.000       20
1240.000       20
2720.000       20
899.000        20
2184.000       19
1341.000       19
3778.000       19
2800.000       19
1993.000       19
1469.000       19
3000.000       18
4966.000       18
2997.000       17
1330.000       17
3198.000       17
2299.000       16
1086.000       15
2200.000       15
1900.000       14
1700.000       13
2298.000       13
4606.000       13
1389.000       12
2.000          12
6208.000       12
5200.000       12
1299.000       11
2954.000       11
2953.000       10
1108.000       10
4009.000       10
4700.000       10
1986.000       10
1124.000       10
2700.000       10
2442.000       10
2179.000       10
2792.000        9
2956.000        9
2656.000        9
5439.000        9
3700.000        9
3720.000        9
1996.000        9
1468.000        8
2497.000        8
2600.000        8
2664.000        8
1781.000        7
1298.000        7
1762.000        7
1875.000        7
1764.000        7
2295.000        7
2148.000        7
3199.000        7
3731.000        7
2264.000        7
2498.000        7
2922.000        7
4600.000        7
1342.000        7
1388.000        7
3496.000        6
1495.000        6
843.000         6
4973.000        6
1576.000        6
1100.000        5
2478.000        5
3500.000        5
2188.000        5
3956.000        5
1905.000        5
1809.000        5
5513.000        5
1994.000        5
3724.000        4
2294.000        4
1120.000        4
3726.000        4
5162.000        4
5400.000        4
499.000         4
3200.000        4
1586.000        4
4000.000        4
2359.000        4
850.000         4
3800.000        4
2990.000        4
4949.000        4
5980.000        4
1658.000        4
1782.000        4
3606.000        4
767.000         3
2826.000        3
2279.000        3
5.000           3
1797.000        3
4414.000        3
4952.000        3
1990.000        3
2393.000        3
2544.000        3
964.000         3
2746.000        3
2947.000        3
1897.000        3
2799.000        3
1679.000        3
1761.000        3
2458.000        3
2717.000        3
3996.000        3
5600.000        3
2297.000        3
1979.000        3
1294.000        3
2721.000        3
1783.000        3
1948.000        3
2597.000        3
1955.000        3
6300.000        2
1795.000        2
1590.000        2
3600.000        2
3597.000        2
2798.000        2
2598.000        2
4742.000        2
4735.000        2
2171.000        2
5689.000        2
1635.000        2
5409.000        2
1221.000        2
4.000           2
2940.000        2
4942.000        2
1296.000        2
3878.000        2
5800.000        2
5032.000        2
2446.000        2
2784.000        2
1481.000        2
6400.000        2
1488.000        2
2499.000        2
750.000         2
4728.000        2
2995.000        2
2100.000        2
1116.000        2
5987.000        2
3235.000        2
2902.000        2
1301.000        2
2151.000        2
1337.000        2
652.000         2
3950.000        2
2034.000        2
1584.000        2
500.000         2
2992.000        2
1372.000        2
1589.000        2
1414.000        2
1699.000        2
1194.000        2
4200.000        2
2316.000        2
996.000         2
2932.000        2
4996.000        2
1290.000        2
1569.000        2
650.000         2
1709.000        2
903.000         2
1438.000        2
973.000         2
1992.000        1
2180.000        1
2043.000        1
3595.000        1
4948.000        1
3727.000        1
4601.000        1
5666.000        1
5766.000        1
4489.000        1
5812.000        1
5300.000        1
2985.000        1
4885.000        1
6276.000        1
54009.000       1
5768.000        1
2967.000        1
5700.000        1
5786.000        1
2685.000        1
3459.000        1
4605.000        1
2288.000        1
6387.000        1
2290.000        1
2699.000        1
3490.000        1
997.000         1
3793.000        1
1594.000        1
2966.000        1
2962.000        1
2306.000        1
2657.000        1
4800.000        1
5981.000        1
2351.000        1
300.000         1
2035.000        1
1799.000        1
3192.000        1
2461.000        1
2127.000        1
3300.000        1
2748.000        1
1954.000        1
6209.000        1
5083.000        1
3900.000        1
2276.000        1
3998.000        1
6294.000        1
4006.000        1
4886.000        1
5031.000        1
5686.000        1
8660.000        1
3797.000        1
289.000         1
19194.000       1
4736.000        1
6653.000        1
4995.000        1
6000.000        1
2263.000        1
2490.000        1
4660.000        1
3238.000        1
600.000         1
1739.000        1
549.000         1
1891.000        1
1245.000        1
2829.000        1
1616.000        1
2441.000        1
1647.000        1
2324.000        1
1270.000        1
1089.000        1
332.000         1
16597.000       1
1289.000        1
99900.000       1
1565.000        1
2993.000        1
2457.000        1
2975.000        1
16998.000       1
982.000         1
1988.000        1
1489.000        1
3220.000        1
1251.000        1
2155.000        1
2927.000        1
1581.000        1
1280.000        1
698.000         1
498.000         1
1122.000        1
1981.000        1
2518.000        1
2418.000        1
2402.000        1
1465.000        1
1295.000        1
1608.000        1
1756.000        1
1971.000        1
1592.000        1
847.000         1
1983.000        1
1150.000        1
2977.000        1
2384.000        1
4664.000        1
2740.000        1
2573.000        1
2935.000        1
2568.000        1
2484.000        1
2569.000        1
1585.000        1
2496.000        1
2991.000        1
2980.000        1
2464.000        1
2197.000        1
1974.000        1
5950.000        1
1241.000        1
2548.000        1
4146.000        1
4598.000        1
2398.000        1
1196.000        1
2145.000        1
2149.000        1
2565.000        1
988.000         1
1577.000        1
987.000         1
2933.000        1
1158.000        1
839.000         1
2645.000        1
20.000          1
1763.000        1
2959.000        1
1119.000        1
2969.000        1
2172.000        1
4500.000        1
5663.000        1
4164.000        1
3955.000        1
1235.000        1
3059.000        1
1281.000        1
2753.000        1
2495.000        1
200.000         1
3224.000        1
2473.000        1
Name: engine_size, dtype: int64

In [ ]:
df["engine_size"].fillna("-", inplace=True)

**⚠️ Why do we need to convert ``Nan`` values into something else, "-" in our case❓**

**``describe()``** does **NOT** return anything for ``NaN`` values. If you have **``"Nan"``** at the column/feature you are interested in, you should replace these ``nan`` values with something else. In our case, we have replaced the **``"NaN"``** values with **``"-"``** so that we could implement the ``describe()`` method.

In [ ]:
df.groupby(["make_model", "body_type","engine_size"]).price.describe()

                                          count      mean      std       min  \
make_model  body_type        engine_size
Dacia       Compact          0.0          1.000 19515.000      NaN 19515.000
                             -            2.000 22389.000  127.279 22299.000
            Sedan            1289.0       1.000  9999.000      NaN  9999.000
            Station wagon    999.0        1.000 21799.000      NaN 21799.000
Dacia Break Station wagon    -            1.000 20500.000      NaN 20500.000
...                                         ...       ...      ...       ...
Volvo XC90  Off-Road/Pick-up 2922.0       2.000 16990.000    0.000 16990.000
                             -            2.000 55900.000    0.000 55900.000
            Sedan            1969.0       2.000 48100.000  565.685 47700.000
                             -            1.000 84900.000      NaN 84900.000
            Station wagon    1969.0       4.000 32750.000 3752.777 29500.000

                                               25%       50%       75%  \
make_model  body_type        engine_size
Dacia       Compact          0.0         19515.000 19515.000 19515.000
                             -           22344.000 22389.000 22434.000
            Sedan            1289.0       9999.000  9999.000  9999.000
            Station wagon    999.0       21799.000 21799.000 21799.000
Dacia Break Station wagon    -           20500.000 20500.000 20500.000
...                                            ...       ...       ...
Volvo XC90  Off-Road/Pick-up 2922.0      16990.000 16990.000 16990.000
                             -           55900.000 55900.000 55900.000
            Sedan            1969.0      47900.000 48100.000 48300.000
                             -           84900.000 84900.000 84900.000
            Station wagon    1969.0      29500.000 32750.000 36000.000

                                               max
make_model  body_type        engine_size
Dacia       Compact          0.0         19515.000
                             -           22479.000
            Sedan            1289.0       9999.000
            Station wagon    999.0       21799.000
Dacia Break Station wagon    -           20500.000
...                                            ...
Volvo XC90  Off-Road/Pick-up 2922.0      16990.000
                             -           55900.000
            Sedan            1969.0      48500.000
                             -           84900.000
            Station wagon    1969.0      36000.000

[3890 rows x 8 columns]

**The ``engine_size`` of cars changes by their ``make_models`` & ``body_type`` most of the time. So it is more beneficial to decide to fill missing values with mode value of related group.**

In [ ]:
df["engine_size"].replace("-", np.nan, inplace=True)

def fill(df, group_col1, group_col2, col_name, method): # method can be either "mode" or "mean" or "median" or "ffill"
    
    '''Fills the missing values with "mode/mean/median/ffill/bfill method" according to double-stage grouping'''
    
    if method == "mode":
        for group1 in list(df[group_col1].unique()):
            for group2 in list(df[group_col2].unique()):
                cond1 = df[group_col1]==group1
                cond2 = (df[group_col1]==group1) & (df[group_col2]==group2)
                mode1 = list(df[cond1][col_name].mode())
                mode2 = list(df[cond2][col_name].mode())
                if mode2 != []:
                    df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond2][col_name].mode()[0])
                elif mode1 != []:
                    df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond1][col_name].mode()[0])
                else:
                    df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[col_name].mode()[0])

    elif method == "mean":
        df[col_name].fillna(df.groupby([group_col1, group_col2])[col_name].transform("mean"), inplace = True)
        df[col_name].fillna(df.groupby(group_col1)[col_name].transform("mean"), inplace = True)
        df[col_name].fillna(df[col_name].mean(), inplace = True)
        
    elif method == "median":
        df[col_name].fillna(df.groupby([group_col1, group_col2])[col_name].transform("median"), inplace = True)
        df[col_name].fillna(df.groupby(group_col1)[col_name].transform("median"), inplace = True)
        df[col_name].fillna(df[col_name].median(), inplace = True)
        
    elif method == "ffill":           
        for group1 in list(df[group_col1].unique()):
            for group2 in list(df[group_col2].unique()):
                cond2 = (df[group_col1]==group1) & (df[group_col2]==group2)
                df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(method="ffill").fillna(method="bfill")
                
        for group1 in list(df[group_col1].unique()):
            cond1 = df[group_col1]==group1
            df.loc[cond1, col_name] = df.loc[cond1, col_name].fillna(method="ffill").fillna(method="bfill")            
           
        df[col_name] = df[col_name].fillna(method="ffill").fillna(method="bfill")
    
    print("COLUMN NAME    : ", col_name)
    print("--------------------------------")
    print("per_of_nulls   : ", "%", round(df[col_name].isnull().sum()*100 / df.shape[0], 2))
    print("num_of_nulls   : ", df[col_name].isnull().sum())
    print("num_of_uniques : ", df[col_name].nunique())
    print("--------------------------------")
    print(df[col_name].value_counts(dropna = False).sort_index())

In [ ]:
fill(df, "make_model", "body_type", "engine_size", "mode")

COLUMN NAME    :  engine_size
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  467
--------------------------------
0.000         330
1.000         111
2.000          12
4.000           2
5.000           3
20.000          1
200.000         1
289.000         1
300.000         1
332.000         1
498.000         1
499.000         5
500.000         2
549.000         1
600.000         1
650.000         2
652.000         2
698.000         1
750.000         2
767.000         6
839.000         2
843.000        10
847.000         1
850.000         5
875.000       113
898.000       432
899.000        20
900.000        53
903.000         4
964.000         3
973.000         2
982.000         1
987.000         2
988.000         1
996.000         2
997.000         1
998.000       952
999.000      2145
1000.000       99
1084.000       38
1086.000       15
1089.000        1
1100.000       13
1108.000       10
1116.000        2
1119.000        1
1120.000        4
1122.000        1
1124.000       10
1149.000      159
1150.000        2
1158.000        4
1194.000        2
1196.000        1
1197.000      384
1198.000      153
1199.000      931
1200.000      162
1221.000        2
1229.000       64
1235.000        1
1240.000       20
1241.000        1
1242.000      421
1245.000        1
1248.000      332
1251.000        1
1270.000        1
1280.000        1
1281.000        1
1289.000        1
1290.000        2
1294.000        3
1295.000        1
1296.000        2
1298.000        7
1299.000       11
1300.000       60
1301.000        2
1329.000       27
1330.000       17
1332.000      531
1333.000      105
1337.000        2
1341.000       19
1342.000        7
1353.000       50
1360.000       30
1362.000       90
1364.000      230
1368.000      355
1372.000        2
1386.000       48
1388.000        7
1389.000       12
1390.000       90
1395.000      176
1396.000       59
1397.000       54
1398.000      147
1399.000       52
1400.000      105
1414.000        6
1422.000       39
1438.000        2
1461.000     1144
1465.000        1
1468.000        8
1469.000       19
1477.000       88
1481.000        2
1482.000      127
1488.000        2
1489.000        1
1490.000      153
1495.000        6
1496.000      138
1497.000      154
1498.000      785
1499.000      413
1500.000      213
1560.000      479
1565.000        1
1569.000        2
1576.000        6
1577.000        1
1580.000      109
1581.000        1
1582.000      127
1584.000        4
1585.000        1
1586.000        4
1587.000      113
1589.000        2
1590.000        2
1591.000      203
1592.000        1
1594.000        1
1595.000      120
1596.000      106
1597.000       42
1598.000     2255
1599.000       33
1600.000      296
1608.000        2
1616.000        1
1618.000      128
1635.000        2
1647.000        1
1658.000        4
1679.000        3
1685.000       92
1686.000       28
1699.000        2
1700.000       16
1709.000        2
1721.000       21
1739.000        1
1747.000       71
1749.000       31
1756.000        1
1761.000        3
1762.000        7
1763.000        1
1764.000        7
1769.000       34
1781.000        7
1782.000        4
1783.000        3
1794.000      142
1795.000        2
1796.000      160
1797.000        3
1798.000      487
1799.000        1
1800.000       49
1809.000        5
1870.000       55
1875.000       12
1891.000        1
1896.000       28
1897.000        3
1900.000       15
1905.000        5
1910.000       27
1948.000        3
1950.000      203
1954.000        1
1955.000        3
1956.000      203
1968.000      631
1969.000     1967
1971.000        2
1974.000        1
1975.000       36
1979.000        3
1981.000        1
1983.000        1
1984.000      584
1986.000       10
1987.000      164
1988.000        1
1990.000        3
1991.000      357
1992.000        1
1993.000       19
1994.000        6
1995.000      357
1996.000        9
1997.000      676
1998.000     1056
1999.000      149
2000.000      209
2034.000        2
2035.000        1
2043.000        2
2100.000        2
2127.000        1
2143.000      251
2145.000        1
2148.000        7
2149.000        1
2151.000        2
2155.000        1
2171.000        2
2172.000        1
2179.000       11
2180.000        1
2184.000       19
2188.000        5
2197.000        1
2198.000       35
2199.000       36
2200.000       16
2230.000       21
2231.000       22
2261.000      101
2263.000        1
2264.000        7
2276.000        1
2279.000        5
2288.000        2
2290.000        1
2294.000        4
2295.000        7
2297.000        3
2298.000       13
2299.000       19
2300.000       52
2306.000        1
2316.000        2
2319.000       53
2324.000        1
2351.000        1
2359.000        4
2384.000        1
2393.000        3
2398.000        1
2400.000      156
2401.000       43
2402.000        1
2418.000        1
2435.000      309
2441.000        1
2442.000       11
2446.000        2
2457.000        1
2458.000        6
2461.000        1
2464.000        1
2473.000        1
2478.000        5
2484.000        1
2487.000       37
2488.000       40
2490.000        1
2494.000       40
2495.000        1
2496.000        2
2497.000        8
2498.000        7
2499.000        2
2500.000       49
2518.000        1
2521.000       91
2544.000        3
2548.000        1
2565.000        1
2568.000        1
2569.000        1
2573.000        1
2597.000        3
2598.000        2
2600.000        8
2645.000        1
2656.000        9
2657.000        1
2664.000       13
2685.000        1
2699.000        1
2700.000       18
2717.000        3
2720.000       25
2721.000        3
2740.000        1
2746.000        3
2748.000        1
2753.000        1
2755.000       75
2784.000        4
2792.000        9
2798.000        2
2799.000        3
2800.000       19
2826.000        3
2829.000        1
2902.000        3
2922.000        7
2925.000      119
2927.000        1
2932.000        2
2933.000        1
2935.000        1
2940.000        2
2946.000       24
2947.000        3
2953.000       10
2954.000       12
2956.000        9
2959.000        1
2960.000       23
2962.000        1
2966.000        1
2967.000        1
2969.000        1
2975.000        1
2977.000        1
2980.000        1
2982.000       21
2985.000        1
2987.000      106
2990.000        4
2991.000        1
2992.000        2
2993.000        1
2995.000        2
2996.000      147
2997.000       17
2998.000       53
2999.000       91
3000.000       18
3059.000        1
3192.000        1
3198.000       17
3199.000        7
3200.000        7
3220.000        1
3224.000        1
3235.000        2
3238.000        1
3300.000        1
3459.000        1
3490.000        1
3496.000        6
3498.000      180
3500.000        5
3595.000        1
3597.000        2
3600.000        7
3606.000        4
3696.000      158
3700.000        9
3720.000        9
3724.000        4
3726.000        4
3727.000        1
3731.000        7
3778.000       19
3793.000        1
3797.000        1
3799.000       77
3800.000        4
3878.000        3
3900.000        1
3950.000        5
3955.000        5
3956.000        5
3982.000      205
3996.000        3
3998.000        1
4000.000        4
4006.000        1
4009.000       10
4146.000        1
4164.000        1
4200.000        2
4414.000        3
4489.000        1
4500.000        1
4598.000        1
4600.000        7
4601.000        1
4605.000        1
4606.000       13
4660.000        1
4663.000       31
4664.000        1
4700.000       10
4728.000        2
4735.000        2
4736.000        1
4742.000        2
4800.000        1
4885.000        1
4886.000        1
4942.000        2
4948.000        1
4949.000       10
4951.000       89
4952.000        3
4966.000       19
4973.000        7
4995.000        1
4996.000        2
5000.000       21
5031.000        1
5032.000        2
5038.000      303
5083.000        1
5162.000        4
5200.000       12
5300.000        1
5400.000        4
5409.000        2
5439.000        9
5461.000       51
5513.000        5
5600.000        4
5663.000        1
5666.000        1
5686.000        1
5689.000        2
5700.000        1
5766.000        1
5768.000        1
5786.000        1
5800.000        2
5812.000        1
5950.000        1
5980.000        4
5981.000        1
5987.000        2
6000.000        1
6208.000       12
6209.000        1
6276.000        1
6294.000        1
6300.000        2
6387.000        1
6400.000        2
6653.000        1
8660.000        1
16597.000       1
16998.000       1
19194.000       1
54009.000       1
99900.000       1
Name: engine_size, dtype: int64

## age

In [ ]:
first_looking("age")

COLUMN NAME    :  age
--------------------------------
per_of_nulls   :  % 0.01
num_of_nulls   :  2
num_of_uniques :  83
--------------------------------
3.000       3667
4.000       3492
0.000       3086
1.000       2870
2.000       2473
5.000       2426
6.000       1486
7.000       1237
8.000        936
9.000        703
10.000       655
11.000       642
12.000       559
15.000       492
14.000       441
13.000       424
16.000       395
17.000       287
18.000       247
19.000       211
21.000       191
20.000       187
22.000       160
23.000       144
24.000        91
25.000        81
28.000        80
27.000        78
26.000        71
31.000        62
30.000        60
29.000        55
32.000        54
56.000        41
55.000        34
34.000        33
57.000        32
49.000        29
50.000        29
54.000        27
35.000        26
44.000        23
36.000        22
33.000        20
52.000        19
51.000        18
37.000        18
53.000        17
43.000        17
39.000        16
47.000        14
45.000        13
58.000        11
46.000        11
40.000        11
38.000        10
41.000         9
59.000         9
48.000         9
60.000         8
61.000         7
42.000         6
67.000         6
68.000         4
64.000         4
65.000         4
62.000         4
90.000         3
85.000         2
63.000         2
122.000        2
69.000         2
92.000         2
NaN            2
70.000         2
-3.000         1
89.000         1
76.000         1
66.000         1
-1.000         1
93.000         1
72.000         1
94.000         1
-180.000       1
Name: age, dtype: int64

In [ ]:
df['age'].fillna('-', inplace=True)

In [ ]:
df.groupby("age").mileage.describe()

,count,mean,std,min,25%,50%,75%,max
age,,,,,,,,
-180.0,1.000,20926.000,NaN,20926.000,20926.000,20926.000,20926.000,20926.000
-3.0,1.000,59629.000,NaN,59629.000,59629.000,59629.000,59629.000,59629.000
-1.0,1.000,147985.000,NaN,147985.000,147985.000,147985.000,147985.000,147985.000
0.0,3085.000,3043.334,4697.710,0.000,10.000,400.000,5000.000,46500.000
1.0,2870.000,15009.230,12832.032,0.000,5806.000,12175.000,21493.500,94000.000
2.0,2473.000,30711.260,22596.144,1.000,16100.000,25681.000,39000.000,217000.000
3.0,3667.000,50955.462,39455.397,10.000,27319.500,44000.000,65166.000,1440000.000
4.0,3492.000,70204.332,44890.045,1.000,42000.000,64062.000,91500.000,1199900.000
5.0,2426.000,77484.786,40133.756,0.000,50000.000,72151.500,99699.250,415000.000
6.0,1486.000,83995.416,42973.692,1.000,53777.750,79999.500,108128.000,399000.000
7.0,1237.000,98250.392,45588.550,10.000,68000.000,93850.000,124883.000,523992.000
8.0,936.000,108883.928,56292.781,10.000,69791.500,102050.000,136054.750,546888.000
9.0,703.000,116788.030,53265.297,150.000,82000.000,112000.000,143281.000,383754.000
10.0,655.000,123027.414,55013.809,351.000,85065.000,117000.000,154686.000,406000.000
11.0,642.000,134643.419,62227.246,1021.000,94051.500,129981.500,172884.000,600000.000
12.0,559.000,147977.106,67955.454,6269.000,102635.000,141081.000,184737.500,667128.000
13.0,424.000,149548.219,67977.031,520.000,102750.000,142962.000,191242.000,400332.000
14.0,441.000,158996.961,67263.176,14162.000,116000.000,158000.000,194000.000,448914.000
15.0,492.000,163675.329,70389.441,2700.000,112448.750,160000.000,200000.000,433850.000
16.0,395.000,154184.003,61647.372,10800.000,115000.000,150000.000,199025.000,339000.000
17.0,287.000,160294.969,77156.500,139.000,106286.500,155000.000,203800.000,494457.000
18.0,247.000,174932.939,73793.423,10000.000,120428.500,166512.000,218491.000,461626.000
19.0,211.000,156258.806,66272.564,38270.000,98911.500,150000.000,199579.000,370000.000
20.0,187.000,154393.182,73776.315,4600.000,96975.000,156653.000,208443.000,361000.000
21.0,191.000,166095.005,75262.758,2000.000,115000.000,167363.000,207983.500,372008.000
22.0,160.000,148224.406,74415.076,7000.000,92744.750,144355.500,193150.000,600001.000
23.0,144.000,158723.424,88957.100,5000.000,92750.000,153850.000,211622.750,547000.000
24.0,91.000,130119.143,63423.222,5000.000,93200.000,125000.000,173600.000,256064.000
25.0,81.000,154737.321,82520.040,1.000,101000.000,150000.000,199000.000,350000.000
26.0,71.000,140526.282,68759.455,16000.000,96310.500,134504.000,170000.000,336634.000
27.0,78.000,138833.974,58265.537,12774.000,101912.000,133701.000,173054.250,339000.000
28.0,80.000,145438.038,69963.740,35600.000,93943.500,131754.000,185485.000,398000.000
29.0,55.000,150443.564,71014.321,9723.000,100100.000,151836.000,199500.000,350000.000
30.0,60.000,135084.500,68353.562,10000.000,87750.000,127377.500,182512.500,300000.000
31.0,62.000,150345.129,98111.077,10.000,76712.500,131876.000,203868.250,377733.000
32.0,54.000,146269.593,69476.180,900.000,100875.000,141917.500,186250.000,287064.000
33.0,20.000,104872.600,61901.897,2500.000,47126.000,119900.000,145112.500,208700.000
34.0,33.000,139495.545,79987.654,1.000,76000.000,123000.000,185180.000,302718.000
35.0,26.000,126674.962,54208.697,40000.000,86675.000,115043.000,148336.750,235964.000
36.0,22.000,178897.682,261746.665,1000.000,84511.500,143750.000,199517.750,1300000.000
37.0,18.000,112710.667,104722.535,2000.000,60500.000,94999.500,116482.750,457379.000
38.0,10.000,96806.900,57684.380,6000.000,49025.000,112034.500,144250.000,166000.000
39.0,16.000,94641.875,61222.865,1500.000,68600.000,90508.000,105682.750,262000.000
40.0,11.000,141104.182,127230.983,1.000,49680.000,147000.000,194814.500,431330.000
41.0,9.000,105145.000,60755.244,1.000,63715.000,119000.000,150000.000,196589.000
42.0,6.000,96055.167,15564.195,76072.000,82550.000,101929.500,108964.750,109000.000
43.0,17.000,108403.588,69128.066,300.000,51500.000,123000.000,150000.000,222606.000
44.0,23.000,118440.652,115268.781,10.000,44374.500,104498.000,159000.000,536388.000
45.0,13.000,86378.385,51218.306,596.000,50586.000,76025.000,135000.000,160000.000
46.0,11.000,69099.091,68456.067,1.000,9944.500,50000.000,130000.000,175000.000
47.0,14.000,87400.357,62188.458,1.000,45215.000,76311.000,138750.000,180559.000
48.0,9.000,56524.222,47047.161,1.000,15896.000,72500.000,95500.000,121000.000
49.0,29.000,76488.586,45976.775,2000.000,45000.000,73000.000,102301.000,191900.000
50.0,29.000,98134.966,72946.103,55.000,39500.000,85000.000,107933.000,260000.000
51.0,18.000,89645.167,46746.245,500.000,61533.750,90796.000,140013.500,146212.000
52.0,19.000,77385.789,52568.761,1000.000,38296.500,83400.000,111111.000,174000.000
53.0,17.000,59595.235,34806.013,1000.000,36000.000,49432.000,83500.000,150000.000
54.0,27.000,115241.667,256813.825,202.000,14062.500,45000.000,76500.000,1000000.000
55.0,34.000,73451.676,34762.329,20.000,51018.000,73175.000,93498.750,166221.000
56.0,41.000,85791.756,150315.468,2639.000,45220.000,55770.000,81480.000,999999.000
57.0,32.000,62834.688,39673.631,1.000,41585.000,54675.500,78915.000,163046.000
58.0,11.000,79000.273,28530.362,39000.000,50233.500,100000.000,100000.000,115000.000
59.0,9.000,55120.778,37724.097,10.000,46000.000,47470.000,82600.000,99999.000
60.0,8.000,90936.250,28639.226,59000.000,74675.000,79950.000,115415.000,132470.000
61.0,7.000,109524.286,65386.998,50000.000,57100.000,100000.000,151235.000,200000.000
62.0,4.000,52048.750,33253.266,18620.000,38960.000,45740.000,58828.750,98095.000
63.0,2.000,60603.500,55007.958,21707.000,41155.250,60603.500,80051.750,99500.000
64.0,4.000,46687.250,26288.550,24000.000,32724.750,39184.500,53147.000,84380.000
65.0,4.000,59412.500,52512.036,5650.000,23912.500,54000.000,89500.000,124000.000
66.0,1.000,41170.000,NaN,41170.000,41170.000,41170.000,41170.000,41170.000
67.0,6.000,23864.167,21335.705,1.000,12100.000,18042.000,32246.000,60000.000
68.0,4.000,64414.000,46946.137,1.000,44291.500,79177.500,99300.000,99300.000
69.0,2.000,46000.000,0.000,46000.000,46000.000,46000.000,46000.000,46000.000
70.0,2.000,65000.000,1414.214,64000.000,64500.000,65000.000,65500.000,66000.000
72.0,1.000,52466.000,NaN,52466.000,52466.000,52466.000,52466.000,52466.000
76.0,1.000,180000.000,NaN,180000.000,180000.000,180000.000,180000.000,180000.000
85.0,2.000,28000.000,0.000,28000.000,28000.000,28000.000,28000.000,28000.000
89.0,1.000,999999.000,NaN,999999.000,999999.000,999999.000,999999.000,999999.000
90.0,3.000,14700.000,11053.054,3500.000,9250.000,15000.000,20300.000,25600.000
92.0,2.000,30616.500,41554.544,1233.000,15924.750,30616.500,45308.250,60000.000
93.0,1.000,65515.000,NaN,65515.000,65515.000,65515.000,65515.000,65515.000
94.0,1.000,5000.000,NaN,5000.000,5000.000,5000.000,5000.000,5000.000
122.0,2.000,14985.500,21178.555,10.000,7497.750,14985.500,22473.250,29961.000
-,2.000,3175.000,963.079,2494.000,2834.500,3175.000,3515.500,3856.000

In [ ]:
df[df["age"] == "-"]["mileage"].value_counts(dropna=False)

3856.000    1
2494.000    1
Name: mileage, dtype: int64

cond1 = (df['mileage'] < 10000)
cond2 = ((df['mileage'] >= 10000) & (df['km'] < 25000))
cond3 = ((df['mileage'] >= 25000) & (df['km'] < 40000))
cond4 = (df['mileage'] >= 40000)
...

df.loc[cond1,'age'] = df.loc[cond1,'age'].replace('-', 0)
df.loc[cond2,'age'] = df.loc[cond2,'age'].replace('-', 1)
df.loc[cond3,'age'] = df.loc[cond3,'age'].replace('-', 2)
df.loc[cond4,'age'] = df.loc[cond4,'age'].replace('-', 3)

**Let us use replace() function to fill missing values at "age" column with proper values.**

In [ ]:
cond_age1 = (df['mileage'] < 10000)

df.loc[cond_age1,'age'] = df.loc[cond_age1,'age'].replace('-', 0)

In [ ]:
df.groupby('age').mileage.mean()

age
-180.000    20926.000
-3.000      59629.000
-1.000     147985.000
0.000        3043.419
1.000       15009.230
2.000       30711.260
3.000       50955.462
4.000       70204.332
5.000       77484.786
6.000       83995.416
7.000       98250.392
8.000      108883.928
9.000      116788.030
10.000     123027.414
11.000     134643.419
12.000     147977.106
13.000     149548.219
14.000     158996.961
15.000     163675.329
16.000     154184.003
17.000     160294.969
18.000     174932.939
19.000     156258.806
20.000     154393.182
21.000     166095.005
22.000     148224.406
23.000     158723.424
24.000     130119.143
25.000     154737.321
26.000     140526.282
27.000     138833.974
28.000     145438.038
29.000     150443.564
30.000     135084.500
31.000     150345.129
32.000     146269.593
33.000     104872.600
34.000     139495.545
35.000     126674.962
36.000     178897.682
37.000     112710.667
38.000      96806.900
39.000      94641.875
40.000     141104.182
41.000     105145.000
42.000      96055.167
43.000     108403.588
44.000     118440.652
45.000      86378.385
46.000      69099.091
47.000      87400.357
48.000      56524.222
49.000      76488.586
50.000      98134.966
51.000      89645.167
52.000      77385.789
53.000      59595.235
54.000     115241.667
55.000      73451.676
56.000      85791.756
57.000      62834.688
58.000      79000.273
59.000      55120.778
60.000      90936.250
61.000     109524.286
62.000      52048.750
63.000      60603.500
64.000      46687.250
65.000      59412.500
66.000      41170.000
67.000      23864.167
68.000      64414.000
69.000      46000.000
70.000      65000.000
72.000      52466.000
76.000     180000.000
85.000      28000.000
89.000     999999.000
90.000      14700.000
92.000      30616.500
93.000      65515.000
94.000       5000.000
122.000     14985.500
Name: mileage, dtype: float64

In [ ]:
first_looking("age")

COLUMN NAME    :  age
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  83
--------------------------------
3.000       3667
4.000       3492
0.000       3088
1.000       2870
2.000       2473
5.000       2426
6.000       1486
7.000       1237
8.000        936
9.000        703
10.000       655
11.000       642
12.000       559
15.000       492
14.000       441
13.000       424
16.000       395
17.000       287
18.000       247
19.000       211
21.000       191
20.000       187
22.000       160
23.000       144
24.000        91
25.000        81
28.000        80
27.000        78
26.000        71
31.000        62
30.000        60
29.000        55
32.000        54
56.000        41
55.000        34
34.000        33
57.000        32
49.000        29
50.000        29
54.000        27
35.000        26
44.000        23
36.000        22
33.000        20
52.000        19
37.000        18
51.000        18
43.000        17
53.000        17
39.000        16
47.000        14
45.000        13
40.000        11
58.000        11
46.000        11
38.000        10
48.000         9
59.000         9
41.000         9
60.000         8
61.000         7
67.000         6
42.000         6
68.000         4
65.000         4
64.000         4
62.000         4
90.000         3
122.000        2
85.000         2
63.000         2
70.000         2
92.000         2
69.000         2
89.000         1
-3.000         1
76.000         1
-1.000         1
93.000         1
66.000         1
-180.000       1
94.000         1
72.000         1
Name: age, dtype: int64

## mileage

In [ ]:
first_looking("mileage")

COLUMN NAME    :  mileage
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  1
num_of_uniques :  14183
--------------------------------
10.000        586
1.000         172
50.000        133
100.000       119
5000.000      118
             ...
141589.000      1
59821.000       1
123500.000      1
29781.000       1
230047.000      1
Name: mileage, Length: 14184, dtype: int64

In [ ]:
df.groupby("age").mileage.mean()

age
-180.000    20926.000
-3.000      59629.000
-1.000     147985.000
0.000        3043.419
1.000       15009.230
2.000       30711.260
3.000       50955.462
4.000       70204.332
5.000       77484.786
6.000       83995.416
7.000       98250.392
8.000      108883.928
9.000      116788.030
10.000     123027.414
11.000     134643.419
12.000     147977.106
13.000     149548.219
14.000     158996.961
15.000     163675.329
16.000     154184.003
17.000     160294.969
18.000     174932.939
19.000     156258.806
20.000     154393.182
21.000     166095.005
22.000     148224.406
23.000     158723.424
24.000     130119.143
25.000     154737.321
26.000     140526.282
27.000     138833.974
28.000     145438.038
29.000     150443.564
30.000     135084.500
31.000     150345.129
32.000     146269.593
33.000     104872.600
34.000     139495.545
35.000     126674.962
36.000     178897.682
37.000     112710.667
38.000      96806.900
39.000      94641.875
40.000     141104.182
41.000     105145.000
42.000      96055.167
43.000     108403.588
44.000     118440.652
45.000      86378.385
46.000      69099.091
47.000      87400.357
48.000      56524.222
49.000      76488.586
50.000      98134.966
51.000      89645.167
52.000      77385.789
53.000      59595.235
54.000     115241.667
55.000      73451.676
56.000      85791.756
57.000      62834.688
58.000      79000.273
59.000      55120.778
60.000      90936.250
61.000     109524.286
62.000      52048.750
63.000      60603.500
64.000      46687.250
65.000      59412.500
66.000      41170.000
67.000      23864.167
68.000      64414.000
69.000      46000.000
70.000      65000.000
72.000      52466.000
76.000     180000.000
85.000      28000.000
89.000     999999.000
90.000      14700.000
92.000      30616.500
93.000      65515.000
94.000       5000.000
122.000     14985.500
Name: mileage, dtype: float64

In [ ]:
df[df["mileage"].isna()][["age", "mileage"]]

        age  mileage
10753 0.000      NaN

**Let us use transform() function to fill missing values at "km" column with "mean".**

In [ ]:
df.groupby("age").mileage.transform("mean")

0        83995.416
1         3043.419
2        30711.260
3        30711.260
4        98250.392
           ...
28625    50955.462
28626   174932.939
28627   134643.419
28628    77484.786
28629   154393.182
Name: mileage, Length: 28630, dtype: float64

In [ ]:
df["mileage"].fillna(df.groupby("age").mileage.transform("mean"), inplace=True)

In [ ]:
df[df["mileage"].isna()][["age", "mileage"]]

Empty DataFrame
Columns: [age, mileage]
Index: []

**Using transform() function, we have filled missing values at "mileage" column with the "mean" of the each "age" group.**

In [ ]:
first_looking("mileage")

COLUMN NAME    :  mileage
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  14184
--------------------------------
10.000        586
1.000         172
50.000        133
100.000       119
5000.000      118
             ...
141589.000      1
59821.000       1
123500.000      1
29781.000       1
230047.000      1
Name: mileage, Length: 14184, dtype: int64

## doors

In [ ]:
first_looking("doors")

COLUMN NAME    :  doors
--------------------------------
per_of_nulls   :  % 1.25
num_of_nulls   :  359
num_of_uniques :  6
--------------------------------
5.000    17481
2.000     5523
4.000     3001
3.000     2259
NaN        359
6.000        5
1.000        2
Name: doors, dtype: int64

**The number of doors of cars changes by theirs make_models and body_types. So I have decided to fill missing values with mode value of related group.**

In [ ]:
for group1 in list(df["make_model"].unique()):
    for group2 in list(df["body_type"].unique()):
        cond1 = df["make_model"]==group1
        cond2 = (df["make_model"]==group1) & (df["body_type"]==group2)
        mode1 = list(df[cond1]["doors"].mode())
        mode2 = list(df[cond2]["doors"].mode())
        if mode2 != []:
            df.loc[cond2, "doors"] = df.loc[cond2, "doors"].fillna(df[cond2]["doors"].mode()[0])
        elif mode1 != []:
            df.loc[cond2, "doors"] = df.loc[cond2, "doors"].fillna(df[cond1]["doors"].mode()[0])
        else:
            df.loc[cond2, "doors"] = df.loc[cond2, "doors"].fillna(df["doors"].mode()[0])

In [ ]:
df["doors"].value_counts(dropna=False)

5.000    17637
2.000     5669
4.000     3013
3.000     2304
6.000        5
1.000        2
Name: doors, dtype: int64

def fill_mode(df, group_col1, group_col2, col_name):
    
    for group1 in list(df[group_col1].unique()):
        for group2 in list(df[group_col2].unique()):
            cond1 = df[group_col1]==group1
            cond2 = (df[group_col1]==group1) & (df[group_col2]==group2)
            mode1 = list(df[cond1][col_name].mode())
            mode2 = list(df[cond2][col_name].mode())
            if mode2 != []:
                df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond2][col_name].mode()[0])
            elif mode1 != []:
                df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond1][col_name].mode()[0])
            else:
                df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[col_name].mode()[0])
    
    print("column name    : ", col_name)
    print("--------------------------------")
    print("per_of_nulls   : ", "%", round(df[col_name].isnull().sum()*100 / df.shape[0], 2))
    print("num_of_nulls   : ", df[col_name].isnull().sum())
    print("num_of_uniques : ", df[col_name].nunique())
    print("--------------------------------")
    print(df[col_name].value_counts(dropna = False))

In [ ]:
fill_mode(df, "make_model", "body_type", "doors")

column name    :  doors
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  6
--------------------------------
5.000    17637
2.000     5669
4.000     3013
3.000     2304
6.000        5
1.000        2
Name: doors, dtype: int64

# Method-2

# if we want to generalize this script, it may not work in every case because of the indexing of mode result
# Sometimes it may give different results comparing with solution of "for loop"

df["doors"].fillna(df.groupby(["make_model", "body_type"])["doors"].transform(lambda x : x.mode()), inplace = True)
df["doors"].fillna(df.groupby("make_model")["doors"].transform(lambda x : x.mode()[0]), inplace = True)
df["doors"].fillna(df["doors"].mode()[0], inplace = True)

df["doors"].value_counts(dropna=False)

5.000    17637
2.000     5669
4.000     3013
3.000     2304
6.000        5
1.000        2
Name: Nr_of_Doors, dtype: int64

## warranty

In [ ]:
first_looking("warranty")

COLUMN NAME    :  warranty
--------------------------------
per_of_nulls   :  % 52.97
num_of_nulls   :  15165
num_of_uniques :  64
--------------------------------
NaN        15165
12.000      9545
24.000      1515
60.000       968
6.000        398
36.000       257
3.000        185
0.000        133
48.000        78
84.000        47
72.000        40
13.000        22
8.000         19
18.000        15
1.000         15
15.000        13
14.000        13
16.000        13
30.000        12
34.000        11
21.000        11
33.000        11
32.000         9
20.000         9
23.000         9
19.000         9
17.000         9
35.000         8
28.000         8
50.000         6
22.000         6
42.000         5
31.000         4
26.000         4
52.000         4
47.000         4
9.000          4
25.000         3
58.000         3
11.000         3
27.000         3
45.000         2
53.000         2
10.000         2
57.000         2
51.000         2
29.000         2
2.000          2
80.000         2
90.000         2
7.000          2
46.000         1
117.000        1
43.000         1
65.000         1
39.000         1
142.000        1
110.000        1
37.000         1
49.000         1
55.000         1
99.000         1
122.000        1
44.000         1
4.000          1
Name: warranty, dtype: int64

In [ ]:
df["warranty"].fillna("-", inplace=True)

In [ ]:
df.groupby(["make_model", "body_type"])["age"].describe()

                                count  unique    top   freq
make_model   body_type
Dacia        Compact            3.000   2.000  0.000  2.000
             Sedan              1.000   1.000 47.000  1.000
             Station wagon      1.000   1.000  0.000  1.000
Dacia Break  Station wagon      1.000   1.000  0.000  1.000
Dacia Dokker Compact            1.000   1.000  4.000  1.000
...                               ...     ...    ...    ...
Volvo XC70   Station wagon     26.000   7.000  6.000  6.000
Volvo XC90   Coupe              4.000   1.000  5.000  4.000
             Off-Road/Pick-up 199.000  15.000  5.000 40.000
             Sedan              3.000   3.000  4.000  1.000
             Station wagon      4.000   1.000  6.000  4.000

[1257 rows x 4 columns]

In [ ]:
df["age"] = df["age"].astype(float)

In [ ]:
df.groupby(["make_model", "body_type"])["age"].describe()

                                count   mean   std    min    25%    50%  \
make_model   body_type
Dacia        Compact            3.000  0.333 0.577  0.000  0.000  0.000
             Sedan              1.000 47.000   NaN 47.000 47.000 47.000
             Station wagon      1.000  0.000   NaN  0.000  0.000  0.000
Dacia Break  Station wagon      1.000  0.000   NaN  0.000  0.000  0.000
Dacia Dokker Compact            1.000  4.000   NaN  4.000  4.000  4.000
...                               ...    ...   ...    ...    ...    ...
Volvo XC70   Station wagon     26.000  8.385 2.282  6.000  7.000  8.000
Volvo XC90   Coupe              4.000  5.000 0.000  5.000  5.000  5.000
             Off-Road/Pick-up 199.000  4.231 3.443  0.000  2.000  4.000
             Sedan              3.000  2.667 1.528  1.000  2.000  3.000
             Station wagon      4.000  6.000 0.000  6.000  6.000  6.000

                                 75%    max
make_model   body_type
Dacia        Compact           0.500  1.000
             Sedan            47.000 47.000
             Station wagon     0.000  0.000
Dacia Break  Station wagon     0.000  0.000
Dacia Dokker Compact           4.000  4.000
...                              ...    ...
Volvo XC70   Station wagon     9.000 14.000
Volvo XC90   Coupe             5.000  5.000
             Off-Road/Pick-up  5.000 18.000
             Sedan             3.500  4.000
             Station wagon     6.000  6.000

[1257 rows x 8 columns]

**Let us take a close look at the age of cars considering the warranty feature with missing values**

In [ ]:
df.loc[df["warranty"] == "-"][["make_model", "body_type", "warranty", "age"]]

                   make_model body_type warranty    age
5         Mercedes-Benz C 160   Compact        - 17.000
8      Mercedes-Benz A 35 AMG   Compact        -  3.000
15        Mercedes-Benz A 180   Compact        - 12.000
16        Mercedes-Benz A 250   Compact        -  1.000
23        Mercedes-Benz A 200   Compact        -  3.000
...                       ...       ...      ...    ...
28615               Volvo 960     Sedan        - 30.000
28620               Volvo S90     Sedan        -  4.000
28623               Volvo V40     Sedan        -  4.000
28626               Volvo S40     Sedan        - 18.000
28629               Volvo S80     Sedan        - 20.000

[15165 rows x 4 columns]

In [ ]:
df.loc[df["warranty"] == "-"]["age"].value_counts(dropna=False).sort_index()

-180.000       1
-3.000         1
-1.000         1
0.000       1753
1.000       1385
2.000       1060
3.000       1577
4.000       1266
5.000        955
6.000        677
7.000        534
8.000        478
9.000        443
10.000       441
11.000       438
12.000       391
13.000       346
14.000       334
15.000       386
16.000       311
17.000       229
18.000       210
19.000       171
20.000       163
21.000       172
22.000       146
23.000       128
24.000        83
25.000        77
26.000        67
27.000        73
28.000        77
29.000        51
30.000        60
31.000        61
32.000        52
33.000        18
34.000        32
35.000        26
36.000        20
37.000        18
38.000        10
39.000        16
40.000        11
41.000         9
42.000         6
43.000        17
44.000        22
45.000        13
46.000        11
47.000        14
48.000         8
49.000        29
50.000        28
51.000        17
52.000        19
53.000        17
54.000        26
55.000        32
56.000        39
57.000        31
58.000        11
59.000         9
60.000         8
61.000         7
62.000         4
63.000         2
64.000         4
65.000         4
66.000         1
67.000         6
68.000         4
69.000         2
70.000         2
72.000         1
76.000         1
85.000         2
89.000         1
90.000         3
92.000         2
93.000         1
94.000         1
122.000        2
Name: age, dtype: int64

In [ ]:
display(df.loc[df["warranty"] == "-"]["age"].mean())

8.9531816683152

**It's assumed that missing values in the warranty feature represent no-warranty.**

In [ ]:
def warrantyclassifier(x):
    if "-" in x:
        return "No"
    else:
        return "Yes"

df["warranty"] = df["warranty"].astype(str).apply(warrantyclassifier)

In [ ]:
first_looking("warranty")

COLUMN NAME    :  warranty
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  2
--------------------------------
No     15165
Yes    13465
Name: warranty, dtype: int64

## gears & gearbox

### gears

In [ ]:
first_looking("gears")

COLUMN NAME    :  gears
--------------------------------
per_of_nulls   :  % 33.8
num_of_nulls   :  9676
num_of_uniques :  11
--------------------------------
NaN       9676
6.000     8412
5.000     5335
7.000     1738
8.000     1690
1.000      712
9.000      642
4.000      256
10.000     112
0.000       31
3.000       24
2.000        2
Name: gears, dtype: int64

In [ ]:
# df.groupby("fuel_type").gears.value_counts(dropna=False)

In [ ]:
df[df["fuel_type"]=="Electric"].gears.value_counts(dropna=False)

NaN      100
1.000     77
6.000      4
0.000      3
5.000      2
9.000      1
7.000      1
Name: gears, dtype: int64

In [ ]:
df["gears"].fillna("-", inplace=True)

In [ ]:
df.groupby(["make_model", "body_type", "gearbox", "gears"]).price.describe()

                                                   count      mean       std  \
make_model  body_type        gearbox        gears
Dacia       Compact          Automatic      1.0    1.000 19515.000       NaN
                                            -      2.000 22389.000   127.279
            Sedan            Manual         4.0    1.000  9999.000       NaN
            Station wagon    Manual         -      1.000 21799.000       NaN
Dacia Break Station wagon    Manual         -      1.000 20500.000       NaN
...                                                  ...       ...       ...
Volvo XC90  Off-Road/Pick-up Manual         6.0    2.000  6799.000     0.000
                                            -      2.000  7600.000     0.000
            Sedan            Automatic      -      3.000 60366.667 21250.255
            Station wagon    Automatic      8.0    2.000 29500.000     0.000
                             Semi-automatic 8.0    2.000 36000.000     0.000

                                                        min       25%  \
make_model  body_type        gearbox        gears
Dacia       Compact          Automatic      1.0   19515.000 19515.000
                                            -     22299.000 22344.000
            Sedan            Manual         4.0    9999.000  9999.000
            Station wagon    Manual         -     21799.000 21799.000
Dacia Break Station wagon    Manual         -     20500.000 20500.000
...                                                     ...       ...
Volvo XC90  Off-Road/Pick-up Manual         6.0    6799.000  6799.000
                                            -      7600.000  7600.000
            Sedan            Automatic      -     47700.000 48100.000
            Station wagon    Automatic      8.0   29500.000 29500.000
                             Semi-automatic 8.0   36000.000 36000.000

                                                        50%       75%  \
make_model  body_type        gearbox        gears
Dacia       Compact          Automatic      1.0   19515.000 19515.000
                                            -     22389.000 22434.000
            Sedan            Manual         4.0    9999.000  9999.000
            Station wagon    Manual         -     21799.000 21799.000
Dacia Break Station wagon    Manual         -     20500.000 20500.000
...                                                     ...       ...
Volvo XC90  Off-Road/Pick-up Manual         6.0    6799.000  6799.000
                                            -      7600.000  7600.000
            Sedan            Automatic      -     48500.000 66700.000
            Station wagon    Automatic      8.0   29500.000 29500.000
                             Semi-automatic 8.0   36000.000 36000.000

                                                        max
make_model  body_type        gearbox        gears
Dacia       Compact          Automatic      1.0   19515.000
                                            -     22479.000
            Sedan            Manual         4.0    9999.000
            Station wagon    Manual         -     21799.000
Dacia Break Station wagon    Manual         -     20500.000
...                                                     ...
Volvo XC90  Off-Road/Pick-up Manual         6.0    6799.000
                                            -      7600.000
            Sedan            Automatic      -     84900.000
            Station wagon    Automatic      8.0   29500.000
                             Semi-automatic 8.0   36000.000

[3181 rows x 8 columns]

**The number of ``gears`` of cars changes by their ``make_models``, ``body_type`` and ``gearbox`` most of the time. So it is more beneficial to decide to fill missing values with mode value of related group.**

In [ ]:
df["gears"].replace("-", np.nan, inplace=True)

In [ ]:
for group1 in df["make_model"].unique():
    for group2 in df["body_type"].unique():
        for group3 in df["gearbox"].unique():
            cond1 = df["make_model"] == group1
            cond2 = (df["make_model"] == group1) & (df["body_type"] == group2)
            cond3 = (df["make_model"] == group1) & (df["body_type"] == group2) & (df["gearbox"] == group3)
            mode1 = list(df[cond1]["gears"].mode())
            mode2 = list(df[cond2]["gears"].mode())
            mode3 = list(df[cond3]["gears"].mode())
            if mode3 != []:
                df.loc[cond3, "gears"] = df.loc[cond3, "gears"].fillna(df[cond3]["gears"].mode()[0])
            elif mode2 != []:
                df.loc[cond3, "gears"] = df.loc[cond3, "gears"].fillna(df[cond2]["gears"].mode()[0])
            elif mode1 != []:
                df.loc[cond3, "gears"] = df.loc[cond3, "gears"].fillna(df[cond1]["gears"].mode()[0])
            else:
                df.loc[cond3, "gears"] = df.loc[cond3, "gears"].fillna(df["gears"].mode()[0])

In [ ]:
first_looking("gears")

COLUMN NAME    :  gears
--------------------------------
per_of_nulls   :  % 0.68
num_of_nulls   :  196
num_of_uniques :  11
--------------------------------
6.000     12182
5.000      7741
8.000      2726
7.000      2612
1.000      1344
9.000      1142
4.000       359
10.000      242
NaN         196
3.000        52
0.000        31
2.000         3
Name: gears, dtype: int64

**However, there have still been some (196) missing values for ``gears`` and WHY❓**

In [ ]:
df[df["gears"].isna()][["make_model", "body_type", "gearbox"]]

                    make_model         body_type gearbox
175     Mercedes-Benz A 35 AMG           Compact     NaN
210        Mercedes-Benz A 200           Compact     NaN
222        Mercedes-Benz A 220           Compact     NaN
235        Mercedes-Benz A 220           Compact     NaN
239           Mercedes-Benz CL           Compact     NaN
241        Mercedes-Benz A 200           Compact     NaN
244        Mercedes-Benz A 200           Compact     NaN
246           Mercedes-Benz CL           Compact     NaN
247     Mercedes-Benz A 35 AMG           Compact     NaN
256        Mercedes-Benz A 180           Compact     NaN
258           Mercedes-Benz CL           Compact     NaN
259        Mercedes-Benz A 220           Compact     NaN
267        Mercedes-Benz A 220           Compact     NaN
268        Mercedes-Benz A 180           Compact     NaN
931      Mercedes-Benz CLA 250             Coupe     NaN
2232            Mercedes-Benz              Sedan     NaN
2371            Mercedes-Benz              Sedan     NaN
3085                   Opel GT       Convertible     NaN
3240            Opel Commodore             Coupe     NaN
3246                Opel Astra             Coupe     NaN
3286               Opel Kadett             Coupe     NaN
3316                   Opel GT             Coupe     NaN
3321                Opel Manta             Coupe     NaN
3409                Opel Monza             Coupe     NaN
3422                   Opel GT             Coupe     NaN
3689          Opel Crossland X  Off-Road/Pick-up     NaN
3998             Opel Insignia     Station wagon     NaN
4978            Renault Twingo           Compact     NaN
5004            Renault Megane           Compact     NaN
5072              Renault Clio           Compact     NaN
5095            Renault Megane           Compact     NaN
5108            Renault Megane           Compact     NaN
5126            Renault Megane           Compact     NaN
5133              Renault Clio           Compact     NaN
5152            Renault Megane           Compact     NaN
5170            Renault Megane           Compact     NaN
5239          Renault Talisman       Convertible     NaN
5300                  Renault        Convertible     NaN
5384            Renault Megane       Convertible     NaN
5434              Renault Wind       Convertible     NaN
5436              Renault Wind       Convertible     NaN
5444            Renault Kangoo       Convertible     NaN
5523              Renault Clio       Convertible     NaN
5664            Renault Arkana             Coupe     NaN
5665            Renault Megane             Coupe     NaN
5681            Renault Megane             Coupe     NaN
5707            Renault Megane             Coupe     NaN
5713         Renault Alpine V6             Coupe     NaN
5739            Renault Laguna             Coupe     NaN
5788            Renault Arkana             Coupe     NaN
5817            Renault Megane             Coupe     NaN
5825              Renault Clio             Coupe     NaN
5839            Renault Arkana             Coupe     NaN
5886            Renault Arkana             Coupe     NaN
5892       Renault Alpine A310             Coupe     NaN
5945              Renault Clio             Coupe     NaN
5963            Renault Arkana             Coupe     NaN
5977            Renault Arkana  Off-Road/Pick-up     NaN
6190            Renault Kadjar  Off-Road/Pick-up     NaN
6196            Renault Kadjar  Off-Road/Pick-up     NaN
6218            Renault Captur  Off-Road/Pick-up     NaN
6244            Renault Kadjar  Off-Road/Pick-up     NaN
6248            Renault Captur  Off-Road/Pick-up     NaN
6529            Renault Megane     Station wagon     NaN
6530            Renault Megane     Station wagon     NaN
6821            Renault Megane             Sedan     NaN
7043            Renault Megane             Sedan     NaN
7445               Peugeot 208           Compact     NaN
7547               Peugeot 206       Convertible     NaN
7598               Peugeot 504       Convertible     NaN
7691               Peugeot 206       Convertible     NaN
7702               Peugeot 207       Convertible     NaN
7703               Peugeot 206       Convertible     NaN
7727               Peugeot 205       Convertible     NaN
7734               Peugeot 307       Convertible     NaN
7763               Peugeot 207       Convertible     NaN
7778                  Peugeot        Convertible     NaN
7845               Peugeot 206       Convertible     NaN
7872               Peugeot 206       Convertible     NaN
7876               Peugeot 207       Convertible     NaN
8061               Peugeot 205             Coupe     NaN
8356              Peugeot 3008  Off-Road/Pick-up     NaN
9045               Peugeot 308     Station wagon     NaN
9065               Peugeot 208     Station wagon     NaN
9634                 Fiat Tipo           Compact     NaN
9647                  Fiat 500           Compact     NaN
9777                  Fiat 500           Compact     NaN
10329                Fiat Dino             Coupe     NaN
10377                 Fiat 500             Coupe     NaN
10422               Fiat Coupe             Coupe     NaN
10431                 Fiat 850             Coupe     NaN
10482               Fiat Coupe             Coupe     NaN
10488          Fiat 124 Spider             Coupe     NaN
10522                Fiat Dino             Coupe     NaN
10549                    Fiat              Coupe     NaN
10562                 Fiat 500             Coupe     NaN
10569                Fiat Dino             Coupe     NaN
10573                 Fiat 130             Coupe     NaN
10578                 Fiat 128             Coupe     NaN
10595                 Fiat 600             Coupe     NaN
10617                    Fiat              Coupe     NaN
10662                Fiat 500L             Coupe     NaN
10720                Fiat 500X  Off-Road/Pick-up     NaN
10736                Fiat 500X  Off-Road/Pick-up     NaN
10740                Fiat 500X  Off-Road/Pick-up     NaN
10749                Fiat 500X  Off-Road/Pick-up     NaN
10775                Fiat 500X  Off-Road/Pick-up     NaN
10818                Fiat 500X  Off-Road/Pick-up     NaN
11085                Fiat 500X     Station wagon     NaN
11086                Fiat 500X     Station wagon     NaN
11104                Fiat 500X     Station wagon     NaN
11156                Fiat Tipo     Station wagon     NaN
11196                Fiat 500X     Station wagon     NaN
11568                Fiat Tipo             Sedan     NaN
12233                    SEAT              Coupe     NaN
12259                SEAT Leon             Coupe     NaN
12267               SEAT Ibiza             Coupe     NaN
12793             SEAT Tarraco  Off-Road/Pick-up     NaN
12803               SEAT Arona  Off-Road/Pick-up     NaN
12972                SEAT Leon     Station wagon     NaN
13959            Skoda Felicia       Convertible     NaN
15526            Dacia Sandero       Convertible     NaN
15527             Dacia Duster       Convertible     NaN
15667             Dacia Spring  Off-Road/Pick-up     NaN
16253             Dacia Duster     Station wagon     NaN
16268              Dacia Logan     Station wagon     NaN
17064              Toyota FJ40       Convertible     NaN
17150            Toyota Celica       Convertible     NaN
17192              Toyota FJ40       Convertible     NaN
17360           Toyota Corolla             Coupe     NaN
17400             Toyota Supra             Coupe     NaN
17415            Toyota Celica             Coupe     NaN
17472           Toyota Corolla             Coupe     NaN
17501           Toyota Corolla             Coupe     NaN
17521            Toyota Celica             Coupe     NaN
17567              Toyota C-HR             Coupe     NaN
17931        Toyota FJ Cruiser  Off-Road/Pick-up     NaN
19191            Nissan 100 NX       Convertible     NaN
19204            Nissan Figaro       Convertible     NaN
19288              Nissan GT-R             Coupe     NaN
19509           Nissan Skyline             Coupe     NaN
19523              Nissan GT-R             Coupe     NaN
19550            Nissan Datsun             Coupe     NaN
19630              Nissan GT-R             Coupe     NaN
20046              Nissan Juke     Station wagon     NaN
20131            Nissan Murano     Station wagon     NaN
20134           Nissan Qashqai     Station wagon     NaN
20141              Nissan Juke     Station wagon     NaN
20261           Nissan Qashqai     Station wagon     NaN
20267           Nissan X-Trail     Station wagon     NaN
20325              Nissan Juke     Station wagon     NaN
20337           Nissan Qashqai     Station wagon     NaN
20338              Nissan Juke     Station wagon     NaN
20376              Nissan Juke     Station wagon     NaN
20398           Nissan Qashqai     Station wagon     NaN
20399           Nissan Qashqai     Station wagon     NaN
20788              Ford Fiesta           Compact     NaN
20813              Ford Ka/Ka+           Compact     NaN
21269             Ford Mustang       Convertible     NaN
21315            Ford Focus CC       Convertible     NaN
21319             Ford Mustang       Convertible     NaN
21357             Ford Mustang       Convertible     NaN
21365                    Ford        Convertible     NaN
21380             Ford Mustang       Convertible     NaN
21461                    Ford        Convertible     NaN
21463              Ford Escort       Convertible     NaN
21485             Ford Mustang       Convertible     NaN
21756              Ford Sierra             Coupe     NaN
21926             Ford Mustang             Coupe     NaN
21929             Ford Mustang             Coupe     NaN
22823      Ford Mustang Mach-E             Sedan     NaN
23200            Hyundai IONIQ           Compact     NaN
23224              Hyundai i30           Compact     NaN
23274            Hyundai IONIQ           Compact     NaN
23776              Hyundai i30             Coupe     NaN
24257              Hyundai i30     Station wagon     NaN
24308           Hyundai TUCSON     Station wagon     NaN
24309           Hyundai TUCSON     Station wagon     NaN
25792                Volvo C70       Convertible     NaN
26108                Volvo C70       Convertible     NaN
26387              Volvo P1800             Coupe     NaN
26407                Volvo C70             Coupe     NaN
26424              Volvo P1800             Coupe     NaN
26426                Volvo 262             Coupe     NaN
26428                Volvo 262             Coupe     NaN
26493              Volvo PV544             Coupe     NaN
26562              Volvo P1800             Coupe     NaN
26582                Volvo C70             Coupe     NaN
26599              Volvo P1800             Coupe     NaN
26601                Volvo 262             Coupe     NaN
26603                Volvo 262             Coupe     NaN
26668              Volvo PV544             Coupe     NaN
27644                Volvo V90     Station wagon     NaN
27647  Volvo V90 Cross Country     Station wagon     NaN
28029                Volvo V90     Station wagon     NaN
28032  Volvo V90 Cross Country     Station wagon     NaN

### gearbox

In [ ]:
first_looking("gearbox")

COLUMN NAME    :  gearbox
--------------------------------
per_of_nulls   :  % 0.87
num_of_nulls   :  248
num_of_uniques :  3
--------------------------------
Manual            17023
Automatic         11287
NaN                 248
Semi-automatic       72
Name: gearbox, dtype: int64

In [ ]:
# df.groupby("fuel_type").gearbox.value_counts(dropna=False)

In [ ]:
df[df["fuel_type"]=="Electric"].gearbox.value_counts(dropna=False)

Automatic         181
NaN                 3
Manual              3
Semi-automatic      1
Name: gearbox, dtype: int64

In [ ]:
df["gearbox"].fillna("-", inplace=True)

In [ ]:
df.groupby(["make_model", "body_type", "gearbox"]).price.describe()

                                               count      mean       std  \
make_model   body_type        gearbox
Dacia        Compact          Automatic        3.000 21431.000  1661.744
             Sedan            Manual           1.000  9999.000       NaN
             Station wagon    Manual           1.000 21799.000       NaN
Dacia Break  Station wagon    Manual           1.000 20500.000       NaN
Dacia Dokker Compact          Manual           1.000 11930.000       NaN
...                                              ...       ...       ...
Volvo XC90   Off-Road/Pick-up Automatic      195.000 52812.410 19180.001
                              Manual           4.000  7199.500   462.458
             Sedan            Automatic        3.000 60366.667 21250.255
             Station wagon    Automatic        2.000 29500.000     0.000
                              Semi-automatic   2.000 36000.000     0.000

                                                   min       25%       50%  \
make_model   body_type        gearbox
Dacia        Compact          Automatic      19515.000 20907.000 22299.000
             Sedan            Manual          9999.000  9999.000  9999.000
             Station wagon    Manual         21799.000 21799.000 21799.000
Dacia Break  Station wagon    Manual         20500.000 20500.000 20500.000
Dacia Dokker Compact          Manual         11930.000 11930.000 11930.000
...                                                ...       ...       ...
Volvo XC90   Off-Road/Pick-up Automatic       6400.000 41980.000 49900.000
                              Manual          6799.000  6799.000  7199.500
             Sedan            Automatic      47700.000 48100.000 48500.000
             Station wagon    Automatic      29500.000 29500.000 29500.000
                              Semi-automatic 36000.000 36000.000 36000.000

                                                   75%       max
make_model   body_type        gearbox
Dacia        Compact          Automatic      22389.000 22479.000
             Sedan            Manual          9999.000  9999.000
             Station wagon    Manual         21799.000 21799.000
Dacia Break  Station wagon    Manual         20500.000 20500.000
Dacia Dokker Compact          Manual         11930.000 11930.000
...                                                ...       ...
Volvo XC90   Off-Road/Pick-up Automatic      64990.000 97450.000
                              Manual          7600.000  7600.000
             Sedan            Automatic      66700.000 84900.000
             Station wagon    Automatic      29500.000 29500.000
                              Semi-automatic 36000.000 36000.000

[1816 rows x 8 columns]

**The type of ``gearbox`` of cars changes by their ``make_models`` & ``body_type`` most of the time. So it is more beneficial to decide to fill missing values with mode value of related group.**

In [ ]:
df["gearbox"] = df["gearbox"].replace('-', np.nan)

In [ ]:
fill(df, "make_model", "body_type", "gearbox", "mode")

COLUMN NAME    :  gearbox
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  3
--------------------------------
Automatic         11367
Manual            17191
Semi-automatic       72
Name: gearbox, dtype: int64

**Let us take care of ``gears`` again:**

In [ ]:
for group1 in df["make_model"].unique():
    for group2 in df["body_type"].unique():
        for group3 in df["gearbox"].unique():
            cond1 = df["make_model"] == group1
            cond2 = (df["make_model"] == group1) & (df["body_type"] == group2)
            cond3 = (df["make_model"] == group1) & (df["body_type"] == group2) & (df["gearbox"] == group3)
            mode1 = list(df[cond1]["gears"].mode())
            mode2 = list(df[cond2]["gears"].mode())
            mode3 = list(df[cond3]["gears"].mode())
            if mode3 != []:
                df.loc[cond3, "gears"] = df.loc[cond3, "gears"].fillna(df[cond3]["gears"].mode()[0])
            elif mode2 != []:
                df.loc[cond3, "gears"] = df.loc[cond3, "gears"].fillna(df[cond2]["gears"].mode()[0])
            elif mode1 != []:
                df.loc[cond3, "gears"] = df.loc[cond3, "gears"].fillna(df[cond1]["gears"].mode()[0])
            else:
                df.loc[cond3, "gears"] = df.loc[cond3, "gears"].fillna(df["gears"].mode()[0])

In [ ]:
first_looking("gears")

COLUMN NAME    :  gears
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  11
--------------------------------
6.000     12246
5.000      7802
8.000      2737
7.000      2631
1.000      1352
9.000      1144
4.000       380
10.000      244
3.000        60
0.000        31
2.000         3
Name: gears, dtype: int64

## fuel_type

With a greater push towards fuel efficiency, low running costs and less carbon emissions, you’ll find that hybrid, diesel and electric cars will hold their value for much longer than petrol counterparts. This isn’t a universal truth, as small petrol cars can do very well, but it is becoming a trend.

In [ ]:
first_looking("fuel_type")

COLUMN NAME    :  fuel_type
--------------------------------
per_of_nulls   :  % 6.24
num_of_nulls   :  1787
num_of_uniques :  4
--------------------------------
Benzine               17546
Diesel                 8727
NaN                    1787
Liquid/Natural Gas      382
Electric                188
Name: fuel_type, dtype: int64

In [ ]:
df["fuel_type"].fillna("-", inplace=True)

### 📝 Domain Knowledge:

If we use the same transmission in both engines, the power to the wheels would be uneven and disproportionate as per the engine RPM and driving conditions. Hence we cannot couple the same manual transmission with both the engines.

**[Is there any difference between transmission systems of petrol and diesel engines?](https://www.quora.com/Is-there-any-difference-between-transmission-systems-of-petrol-and-diesel-engines)**

**[Can I use a diesel engine on a petrol gearbox?](https://www.quora.com/Can-I-use-a-diesel-engine-on-a-petrol-gearbox)**

In [ ]:
df.groupby(["make_model", "body_type", "gearbox", "fuel_type"]).price.describe()

                                                        count      mean  \
make_model   body_type        gearbox        fuel_type
Dacia        Compact          Automatic      -          3.000 21431.000
             Sedan            Manual         Benzine    1.000  9999.000
             Station wagon    Manual         Benzine    1.000 21799.000
Dacia Break  Station wagon    Manual         Benzine    1.000 20500.000
Dacia Dokker Compact          Manual         Diesel     1.000 11930.000
...                                                       ...       ...
Volvo XC90   Off-Road/Pick-up Manual         Diesel     4.000  7199.500
             Sedan            Automatic      -          1.000 84900.000
                                             Diesel     2.000 48100.000
             Station wagon    Automatic      Diesel     2.000 29500.000
                              Semi-automatic Diesel     2.000 36000.000

                                                            std       min  \
make_model   body_type        gearbox        fuel_type
Dacia        Compact          Automatic      -         1661.744 19515.000
             Sedan            Manual         Benzine        NaN  9999.000
             Station wagon    Manual         Benzine        NaN 21799.000
Dacia Break  Station wagon    Manual         Benzine        NaN 20500.000
Dacia Dokker Compact          Manual         Diesel         NaN 11930.000
...                                                         ...       ...
Volvo XC90   Off-Road/Pick-up Manual         Diesel     462.458  6799.000
             Sedan            Automatic      -              NaN 84900.000
                                             Diesel     565.685 47700.000
             Station wagon    Automatic      Diesel       0.000 29500.000
                              Semi-automatic Diesel       0.000 36000.000

                                                             25%       50%  \
make_model   body_type        gearbox        fuel_type
Dacia        Compact          Automatic      -         20907.000 22299.000
             Sedan            Manual         Benzine    9999.000  9999.000
             Station wagon    Manual         Benzine   21799.000 21799.000
Dacia Break  Station wagon    Manual         Benzine   20500.000 20500.000
Dacia Dokker Compact          Manual         Diesel    11930.000 11930.000
...                                                          ...       ...
Volvo XC90   Off-Road/Pick-up Manual         Diesel     6799.000  7199.500
             Sedan            Automatic      -         84900.000 84900.000
                                             Diesel    47900.000 48100.000
             Station wagon    Automatic      Diesel    29500.000 29500.000
                              Semi-automatic Diesel    36000.000 36000.000

                                                             75%       max
make_model   body_type        gearbox        fuel_type
Dacia        Compact          Automatic      -         22389.000 22479.000
             Sedan            Manual         Benzine    9999.000  9999.000
             Station wagon    Manual         Benzine   21799.000 21799.000
Dacia Break  Station wagon    Manual         Benzine   20500.000 20500.000
Dacia Dokker Compact          Manual         Diesel    11930.000 11930.000
...                                                          ...       ...
Volvo XC90   Off-Road/Pick-up Manual         Diesel     7600.000  7600.000
             Sedan            Automatic      -         84900.000 84900.000
                                             Diesel    48300.000 48500.000
             Station wagon    Automatic      Diesel    29500.000 29500.000
                              Semi-automatic Diesel    36000.000 36000.000

[2465 rows x 8 columns]

In [ ]:
df["fuel_type"] = df["fuel_type"].replace('-', np.nan)

In [ ]:
fill(df, "make_model", "gearbox", "fuel_type", "mode")

COLUMN NAME    :  fuel_type
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  4
--------------------------------
Benzine               18702
Diesel                 9102
Electric                439
Liquid/Natural Gas      387
Name: fuel_type, dtype: int64

## seats

In [ ]:
first_looking("seats")

COLUMN NAME    :  seats
--------------------------------
per_of_nulls   :  % 10.92
num_of_nulls   :  3125
num_of_uniques :  11
--------------------------------
5.000     18308
4.000      5390
NaN        3125
2.000      1186
7.000       488
8.000        43
9.000        35
3.000        25
6.000        12
0.000         9
1.000         7
17.000        2
Name: seats, dtype: int64

**The number of seats of cars changes by theirs make_models and body_types. So I have decided to fill missing values with mode value of related group.**

In [ ]:
fill(df, "make_model", "body_type", "seats", "mode")

COLUMN NAME    :  seats
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  11
--------------------------------
0.000         9
1.000         7
2.000      1266
3.000        26
4.000      5967
5.000     20720
6.000        12
7.000       542
8.000        44
9.000        35
17.000        2
Name: seats, dtype: int64

## co_emissions

In [ ]:
first_looking("co_emissions")

COLUMN NAME    :  co_emissions
--------------------------------
per_of_nulls   :  % 35.05
num_of_nulls   :  10036
num_of_uniques :  326
--------------------------------
NaN        10036
0.000       1040
119.000      393
124.000      340
129.000      319
114.000      313
99.000       312
115.000      304
139.000      299
109.000      265
108.000      262
125.000      255
149.000      255
130.000      230
123.000      230
138.000      230
120.000      218
117.000      214
110.000      213
127.000      211
126.000      204
111.000      204
104.000      197
112.000      186
95.000       184
107.000      179
135.000      178
116.000      175
154.000      173
134.000      171
145.000      170
122.000      170
133.000      165
178.000      165
113.000      161
128.000      159
106.000      158
121.000      157
103.000      157
131.000      153
93.000       147
98.000       144
105.000      142
156.000      141
118.000      139
140.000      139
148.000      139
155.000      137
159.000      136
88.000       136
136.000      135
144.000      135
102.000      134
96.000       133
147.000      127
158.000      127
161.000      125
94.000       118
92.000       117
142.000      117
167.000      114
132.000      114
137.000      112
143.000      109
166.000      107
169.000      106
146.000      103
164.000      102
101.000      100
152.000       97
174.000       92
85.000        92
97.000        91
151.000       88
153.000       87
171.000       86
150.000       84
89.000        82
191.000       81
170.000       77
165.000       76
162.000       73
168.000       72
175.000       71
180.000       70
196.000       70
194.000       68
157.000       68
90.000        67
177.000       67
141.000       66
273.000       65
185.000       65
218.000       64
230.000       62
160.000       62
179.000       61
193.000       60
163.000       60
184.000       57
190.000       57
173.000       56
195.000       56
82.000        56
181.000       56
229.000       55
199.000       50
176.000       50
100.000       48
219.000       47
212.000       46
34.000        45
42.000        44
200.000       43
209.000       42
225.000       41
261.000       41
183.000       40
41.000        39
248.000       38
197.000       38
226.000       38
192.000       38
26.000        37
187.000       35
189.000       35
234.000       34
182.000       33
49.000        33
76.000        33
275.000       33
289.000       32
210.000       32
263.000       32
253.000       31
215.000       30
186.000       30
64.000        30
284.000       30
38.000        30
268.000       30
188.000       29
84.000        29
242.000       28
220.000       28
172.000       28
47.000        27
40.000        27
214.000       26
39.000        25
86.000        25
280.000       25
87.000        25
211.000       24
79.000        24
279.000       24
91.000        23
245.000       22
254.000       22
288.000       22
75.000        22
36.000        21
217.000       21
35.000        21
205.000       21
236.000       20
270.000       20
216.000       19
208.000       19
202.000       19
31.000        18
232.000       18
48.000        18
1.000         18
201.000       17
262.000       16
299.000       16
235.000       16
32.000        16
204.000       16
252.000       16
198.000       16
259.000       15
203.000       15
246.000       15
278.000       15
46.000        15
223.000       14
54.000        14
213.000       14
250.000       14
83.000        14
50.000        14
25.000        13
207.000       13
221.000       13
238.000       13
206.000       13
244.000       12
247.000       12
285.000       12
44.000        11
256.000       11
277.000       11
281.000       11
258.000       11
231.000       10
222.000       10
51.000        10
240.000       10
78.000        10
224.000       10
298.000       10
295.000       10
37.000         9
311.000        9
260.000        9
33.000         9
249.000        9
228.000        9
237.000        8
287.000        8
251.000        8
267.000        8
29.000         8
292.000        8
282.000        8
52.000         8
239.000        8
28.000         8
59.000         8
255.000        8
265.000        7
55.000         6
330.000        6
312.000        6
257.000        6
306.000        6
296.000        6
14.000         5
22.000         5
30.000         5
66.000         5
327.000        5
269.000        5
68.000         5
227.000        5
43.000         5
283.000        5
303.000        4
320.000        4
81.000         4
27.000         4
243.000        4
24.000         4
276.000        4
274.000        4
241.000        4
322.000        4
271.000        4
18.000         3
15.000         3
300.000        3
319.000        3
310.000        3
324.000        3
17.000         3
8.000          2
414.000        2
290.000        2
336.000        2
16.000         2
340.000        2
45.000         2
23.000         2
233.000        2
293.000        2
264.000        2
400.000        2
56.000         2
10.000         2
65.000         2
272.000        1
9.000          1
71.000         1
307.000        1
326.000        1
313.000        1
399.000        1
940.000        1
294.000        1
420.000        1
328.000        1
304.000        1
314.000        1
350.000        1
339.000        1
394.000        1
910.000        1
343.000        1
316.000        1
341.000        1
21.000         1
317.000        1
335.000        1
20.000         1
19.000         1
345.000        1
13.000         1
348.000        1
266.000        1
373.000        1
344.000        1
80.000         1
398.000        1
7.000          1
377.000        1
5.000          1
3.000          1
308.000        1
321.000        1
73.000         1
332.000        1
70.000         1
338.000        1
342.000        1
53.000         1
Name: co_emissions, dtype: int64

In [ ]:
df["co_emissions"].fillna("-", inplace=True)

In [ ]:
df.groupby(["make_model", "body_type", "fuel_type", "co_emissions"]).price.describe()

                                                      count      mean  \
make_model   body_type        fuel_type co_emissions
Dacia        Compact          Benzine   -             3.000 21431.000
             Sedan            Benzine   -             1.000  9999.000
             Station wagon    Benzine   130.0         1.000 21799.000
Dacia Break  Station wagon    Benzine   -             1.000 20500.000
Dacia Dokker Compact          Diesel    -             1.000 11930.000
...                                                     ...       ...
Volvo XC90   Off-Road/Pick-up Electric  0.0           4.000 64400.000
             Sedan            Diesel    47.0          1.000 84900.000
                                        -             2.000 48100.000
             Station wagon    Diesel    149.0         2.000 29500.000
                                        152.0         2.000 36000.000

                                                          std       min  \
make_model   body_type        fuel_type co_emissions
Dacia        Compact          Benzine   -            1661.744 19515.000
             Sedan            Benzine   -                 NaN  9999.000
             Station wagon    Benzine   130.0             NaN 21799.000
Dacia Break  Station wagon    Benzine   -                 NaN 20500.000
Dacia Dokker Compact          Diesel    -                 NaN 11930.000
...                                                       ...       ...
Volvo XC90   Off-Road/Pick-up Electric  0.0          9814.955 55900.000
             Sedan            Diesel    47.0              NaN 84900.000
                                        -             565.685 47700.000
             Station wagon    Diesel    149.0           0.000 29500.000
                                        152.0           0.000 36000.000

                                                           25%       50%  \
make_model   body_type        fuel_type co_emissions
Dacia        Compact          Benzine   -            20907.000 22299.000
             Sedan            Benzine   -             9999.000  9999.000
             Station wagon    Benzine   130.0        21799.000 21799.000
Dacia Break  Station wagon    Benzine   -            20500.000 20500.000
Dacia Dokker Compact          Diesel    -            11930.000 11930.000
...                                                        ...       ...
Volvo XC90   Off-Road/Pick-up Electric  0.0          55900.000 64400.000
             Sedan            Diesel    47.0         84900.000 84900.000
                                        -            47900.000 48100.000
             Station wagon    Diesel    149.0        29500.000 29500.000
                                        152.0        36000.000 36000.000

                                                           75%       max
make_model   body_type        fuel_type co_emissions
Dacia        Compact          Benzine   -            22389.000 22479.000
             Sedan            Benzine   -             9999.000  9999.000
             Station wagon    Benzine   130.0        21799.000 21799.000
Dacia Break  Station wagon    Benzine   -            20500.000 20500.000
Dacia Dokker Compact          Diesel    -            11930.000 11930.000
...                                                        ...       ...
Volvo XC90   Off-Road/Pick-up Electric  0.0          72900.000 72900.000
             Sedan            Diesel    47.0         84900.000 84900.000
                                        -            48300.000 48500.000
             Station wagon    Diesel    149.0        29500.000 29500.000
                                        152.0        36000.000 36000.000

[8233 rows x 8 columns]

**Let's first examine how CO2_Emission values for Electric cars differ from others.**

In [ ]:
df.groupby(["fuel_type", "make_model", "body_type", "co_emissions"]).price.describe().loc["Electric"]

                                                     count       mean  \
make_model            body_type        co_emissions
Dacia Spring          Compact          -            27.000  22753.667
                      Off-Road/Pick-up 0.0           2.000  17494.500
                                       -             1.000  22980.000
                      Sedan            0.0           1.000  18400.000
                                       -             8.000  21581.750
Fiat                  Coupe            0.0           1.000  27900.000
Fiat 500              Compact          0.0           8.000  26186.250
                      Convertible      0.0           6.000  30148.333
                      Coupe            0.0           3.000  31333.333
                      Sedan            0.0           2.000  27400.000
Fiat 500e             Compact          0.0           4.000  22824.500
                                       -            11.000  31006.364
                      Convertible      0.0           4.000  29550.000
                                       -             5.000  34025.800
                      Coupe            0.0           2.000  26470.000
                                       -             1.000  26599.000
                      Sedan            0.0          15.000  27516.533
                                       -             7.000  29791.286
Ford Kuga             Off-Road/Pick-up 0.0           3.000  37400.000
Ford Mustang          Off-Road/Pick-up 0.0           1.000  71250.000
Ford Mustang Mach-E   Coupe            -             1.000  64500.000
                      Off-Road/Pick-up 0.0           2.000  66400.000
                                       -            14.000  69253.929
                      Sedan            0.0           1.000  64400.000
                                       -             2.000  59977.500
Hyundai IONIQ         Compact          0.0           1.000  33900.000
                      Sedan            0.0           2.000  38450.000
Hyundai KONA          Off-Road/Pick-up 0.0           9.000  31973.333
Mercedes-Benz EQA     Off-Road/Pick-up 0.0           2.000  58050.000
                                       -             1.000  54850.000
                      Sedan            -             1.000  61485.000
Mercedes-Benz EQB 350 Off-Road/Pick-up 0.0           1.000  64900.000
                                       -             5.000  67148.000
Mercedes-Benz EQC 400 Off-Road/Pick-up 0.0           4.000  76449.250
                                       -            12.000  75537.750
Mercedes-Benz EQE 350 Compact          0.0           1.000  80900.000
                      Sedan            0.0           2.000  85000.000
                                       -             7.000  97532.000
                      Station wagon    -             1.000  87879.000
Mercedes-Benz EQS     Compact          -             3.000 136148.000
                      Sedan            0.0           3.000 133773.000
                                       -            20.000 128365.500
                      Station wagon    -             3.000 126085.667
Nissan Leaf           Compact          0.0          17.000  23733.353
                                       -            17.000  21521.941
                      Sedan            0.0          12.000  22683.333
                                       1.0           1.000  20990.000
                                       -            13.000  25984.077
                      Station wagon    0.0           1.000  11000.000
Opel Corsa            Compact          0.0           1.000  28000.000
Opel Mokka            Off-Road/Pick-up 0.0           1.000  25500.000
Peugeot 2008          Off-Road/Pick-up 0.0           1.000  29999.000
                      Station wagon    0.0           2.000  34435.000
Peugeot 208           Compact          0.0           3.000  30318.333
                      Sedan            0.0           8.000  28263.875
Peugeot 308           Sedan            0.0           1.000  33355.000
Peugeot 508           Sedan            0.0           1.000  34173.000
Peugeot Partner       Station wagon    0.0           2.000  16370.000
                                       1.0           1.000  14990.000
Peugeot e-2008        Off-Road/Pick-up -             1.000  35989.000
                      Station wagon    0.0           6.000  37365.667
Peugeot e-208         Compact          0.0           2.000  26999.000
                                       -             3.000  31130.000
Peugeot iOn           Compact          0.0           1.000   9990.000
Renault Arkana        Coupe            132.0         1.000  27500.000
Renault R 11          Sedan            0.0           1.000  10490.000
Renault R 9           Sedan            0.0           3.000  10923.333
Renault Twingo        Compact          0.0           2.000  16910.000
Renault Twizy         Compact          0.0           2.000   8440.000
                                       -             2.000  11990.000
                      Convertible      -             1.000   5900.000
                      Coupe            0.0           2.000   5747.500
                                       -             3.000   8166.000
                      Off-Road/Pick-up -             2.000   7697.500
Renault ZOE           Compact          0.0           8.000  19100.125
                                       -            40.000  20607.800
                      Convertible      0.0           1.000  21999.000
                      Sedan            0.0          14.000  15664.929
                                       -            24.000  19912.167
Skoda Enyaq           Off-Road/Pick-up 0.0           2.000  60900.000
                                       -            14.000  58745.714
                      Sedan            -             1.000  61930.000
Toyota Proace         Station wagon    0.0           1.000  40999.000
Toyota RAV 4          Off-Road/Pick-up 0.0           4.000  46750.000
Volvo S90             Sedan            0.0           2.000  51900.000
Volvo XC90            Off-Road/Pick-up 0.0           4.000  64400.000

                                                          std        min  \
make_model            body_type        co_emissions
Dacia Spring          Compact          -              912.016  19269.000
                      Off-Road/Pick-up 0.0           1407.850  16499.000
                                       -                  NaN  22980.000
                      Sedan            0.0                NaN  18400.000
                                       -             2571.869  18099.000
Fiat                  Coupe            0.0                NaN  27900.000
Fiat 500              Compact          0.0           6390.535  17000.000
                      Convertible      0.0           2373.103  27000.000
                      Coupe            0.0           5918.051  25700.000
                      Sedan            0.0           2262.742  25800.000
Fiat 500e             Compact          0.0           5984.558  14900.000
                                       -             3225.381  23700.000
                      Convertible      0.0           2150.194  26900.000
                                       -             1069.973  32400.000
                      Coupe            0.0            678.823  25990.000
                                       -                  NaN  26599.000
                      Sedan            0.0           3733.042  22900.000
                                       -             2614.819  27450.000
Ford Kuga             Off-Road/Pick-up 0.0           3905.125  32900.000
Ford Mustang          Off-Road/Pick-up 0.0                NaN  71250.000
Ford Mustang Mach-E   Coupe            -                  NaN  64500.000
                      Off-Road/Pick-up 0.0           4949.747  62900.000
                                       -             9204.226  55975.000
                      Sedan            0.0                NaN  64400.000
                                       -             7074.603  54975.000
Hyundai IONIQ         Compact          0.0                NaN  33900.000
                      Sedan            0.0          16263.456  26950.000
Hyundai KONA          Off-Road/Pick-up 0.0           4224.541  25990.000
Mercedes-Benz EQA     Off-Road/Pick-up 0.0           1202.082  57200.000
                                       -                  NaN  54850.000
                      Sedan            -                  NaN  61485.000
Mercedes-Benz EQB 350 Off-Road/Pick-up 0.0                NaN  64900.000
                                       -             2814.120  62900.000
Mercedes-Benz EQC 400 Off-Road/Pick-up 0.0          10466.306  64900.000
                                       -             4864.804  69580.000
Mercedes-Benz EQE 350 Compact          0.0                NaN  80900.000
                      Sedan            0.0           6929.646  80100.000
                                       -            10038.271  86370.000
                      Station wagon    -                  NaN  87879.000
Mercedes-Benz EQS     Compact          -            28080.664 117500.000
                      Sedan            0.0          21400.118 109950.000
                                       -            23153.379  99290.000
                      Station wagon    -            44873.468  98879.000
Nissan Leaf           Compact          0.0           5519.327  12999.000
                                       -             6980.651  10450.000
                      Sedan            0.0           5809.864  13200.000
                                       1.0                NaN  20990.000
                                       -             6481.872  13290.000
                      Station wagon    0.0                NaN  11000.000
Opel Corsa            Compact          0.0                NaN  28000.000
Opel Mokka            Off-Road/Pick-up 0.0                NaN  25500.000
Peugeot 2008          Off-Road/Pick-up 0.0                NaN  29999.000
                      Station wagon    0.0            629.325  33990.000
Peugeot 208           Compact          0.0            280.416  29995.000
                      Sedan            0.0           4494.749  22980.000
Peugeot 308           Sedan            0.0                NaN  33355.000
Peugeot 508           Sedan            0.0                NaN  34173.000
Peugeot Partner       Station wagon    0.0            537.401  15990.000
                                       1.0                NaN  14990.000
Peugeot e-2008        Off-Road/Pick-up -                  NaN  35989.000
                      Station wagon    0.0            520.256  36799.000
Peugeot e-208         Compact          0.0           4242.641  23999.000
                                       -             1014.852  29995.000
Peugeot iOn           Compact          0.0                NaN   9990.000
Renault Arkana        Coupe            132.0              NaN  27500.000
Renault R 11          Sedan            0.0                NaN  10490.000
Renault R 9           Sedan            0.0            404.145  10490.000
Renault Twingo        Compact          0.0           2729.432  14980.000
Renault Twizy         Compact          0.0           2757.716   6490.000
                                       -             4242.641   8990.000
                      Convertible      -                  NaN   5900.000
                      Coupe            0.0            350.018   5500.000
                                       -             4010.445   3999.000
                      Off-Road/Pick-up -              357.089   7445.000
Renault ZOE           Compact          0.0           6901.421  12500.000
                                       -             8255.643   9945.000
                      Convertible      0.0                NaN  21999.000
                      Sedan            0.0           4999.314   8500.000
                                       -             5970.152  13990.000
Skoda Enyaq           Off-Road/Pick-up 0.0           5656.854  56900.000
                                       -             6566.627  48995.000
                      Sedan            -                  NaN  61930.000
Toyota Proace         Station wagon    0.0                NaN  40999.000
Toyota RAV 4          Off-Road/Pick-up 0.0              0.000  46750.000
Volvo S90             Sedan            0.0              0.000  51900.000
Volvo XC90            Off-Road/Pick-up 0.0           9814.955  55900.000

                                                           25%        50%  \
make_model            body_type        co_emissions
Dacia Spring          Compact          -             22985.000  22985.000
                      Off-Road/Pick-up 0.0           16996.750  17494.500
                                       -             22980.000  22980.000
                      Sedan            0.0           18400.000  18400.000
                                       -             21074.250  21599.000
Fiat                  Coupe            0.0           27900.000  27900.000
Fiat 500              Compact          0.0           22925.000  26850.000
                      Convertible      0.0           29067.500  29700.000
                      Coupe            0.0           28250.000  30800.000
                      Sedan            0.0           26600.000  27400.000
Fiat 500e             Compact          0.0           20974.250  23499.000
                                       -             29290.000  32950.000
                      Convertible      0.0           28400.000  29700.000
                                       -             33750.000  33999.000
                      Coupe            0.0           26230.000  26470.000
                                       -             26599.000  26599.000
                      Sedan            0.0           24950.000  26699.000
                                       -             28445.000  28700.000
Ford Kuga             Off-Road/Pick-up 0.0           36150.000  39400.000
Ford Mustang          Off-Road/Pick-up 0.0           71250.000  71250.000
Ford Mustang Mach-E   Coupe            -             64500.000  64500.000
                      Off-Road/Pick-up 0.0           64650.000  66400.000
                                       -             64622.500  68470.000
                      Sedan            0.0           64400.000  64400.000
                                       -             57476.250  59977.500
Hyundai IONIQ         Compact          0.0           33900.000  33900.000
                      Sedan            0.0           32700.000  38450.000
Hyundai KONA          Off-Road/Pick-up 0.0           27990.000  32900.000
Mercedes-Benz EQA     Off-Road/Pick-up 0.0           57625.000  58050.000
                                       -             54850.000  54850.000
                      Sedan            -             61485.000  61485.000
Mercedes-Benz EQB 350 Off-Road/Pick-up 0.0           64900.000  64900.000
                                       -             65950.000  67790.000
Mercedes-Benz EQC 400 Off-Road/Pick-up 0.0           70972.750  75498.500
                                       -             71453.750  75389.500
Mercedes-Benz EQE 350 Compact          0.0           80900.000  80900.000
                      Sedan            0.0           82550.000  85000.000
                                       -             92895.000  95999.000
                      Station wagon    -             87879.000  87879.000
Mercedes-Benz EQS     Compact          -            120000.000 122500.000
                      Sedan            0.0          124975.000 140000.000
                                       -            110890.000 122470.000
                      Station wagon    -            100189.000 101499.000
Nissan Leaf           Compact          0.0           21500.000  24900.000
                                       -             14850.000  24390.000
                      Sedan            0.0           20650.000  21740.000
                                       1.0           20990.000  20990.000
                                       -             21980.000  25900.000
                      Station wagon    0.0           11000.000  11000.000
Opel Corsa            Compact          0.0           28000.000  28000.000
Opel Mokka            Off-Road/Pick-up 0.0           25500.000  25500.000
Peugeot 2008          Off-Road/Pick-up 0.0           29999.000  29999.000
                      Station wagon    0.0           34212.500  34435.000
Peugeot 208           Compact          0.0           30230.000  30465.000
                      Sedan            0.0           24869.250  27889.500
Peugeot 308           Sedan            0.0           33355.000  33355.000
Peugeot 508           Sedan            0.0           34173.000  34173.000
Peugeot Partner       Station wagon    0.0           16180.000  16370.000
                                       1.0           14990.000  14990.000
Peugeot e-2008        Off-Road/Pick-up -             35989.000  35989.000
                      Station wagon    0.0           37024.000  37199.000
Peugeot e-208         Compact          0.0           25499.000  26999.000
                                       -             30720.000  31445.000
Peugeot iOn           Compact          0.0            9990.000   9990.000
Renault Arkana        Coupe            132.0         27500.000  27500.000
Renault R 11          Sedan            0.0           10490.000  10490.000
Renault R 9           Sedan            0.0           10740.000  10990.000
Renault Twingo        Compact          0.0           15945.000  16910.000
Renault Twizy         Compact          0.0            7465.000   8440.000
                                       -             10490.000  11990.000
                      Convertible      -              5900.000   5900.000
                      Coupe            0.0            5623.750   5747.500
                                       -              6249.500   8500.000
                      Off-Road/Pick-up -              7571.250   7697.500
Renault ZOE           Compact          0.0           15250.000  17995.000
                                       -             11950.000  20950.000
                      Convertible      0.0           21999.000  21999.000
                      Sedan            0.0           12950.000  14990.000
                                       -             16290.000  17240.000
Skoda Enyaq           Off-Road/Pick-up 0.0           58900.000  60900.000
                                       -             54995.000  57492.000
                      Sedan            -             61930.000  61930.000
Toyota Proace         Station wagon    0.0           40999.000  40999.000
Toyota RAV 4          Off-Road/Pick-up 0.0           46750.000  46750.000
Volvo S90             Sedan            0.0           51900.000  51900.000
Volvo XC90            Off-Road/Pick-up 0.0           55900.000  64400.000

                                                           75%        max
make_model            body_type        co_emissions
Dacia Spring          Compact          -             22985.000  23090.000
                      Off-Road/Pick-up 0.0           17992.250  18490.000
                                       -             22980.000  22980.000
                      Sedan            0.0           18400.000  18400.000
                                       -             21607.000  27044.000
Fiat                  Coupe            0.0           27900.000  27900.000
Fiat 500              Compact          0.0           31922.500  33000.000
                      Convertible      0.0           31225.000  33900.000
                      Coupe            0.0           34150.000  37500.000
                      Sedan            0.0           28200.000  29000.000
Fiat 500e             Compact          0.0           25349.250  29400.000

**It seems more sensible to fill missing values in two stages:**

- With the ``Mode`` value of Electric feature for ``Electric cars``.

- With the ``Median`` values of related make_model, body_type and fuel_type features for the ``others``.

In [ ]:
df["co_emissions"].replace("-", np.nan, inplace=True)

In [ ]:
df[df["fuel_type"] == "Electric"]["co_emissions"].value_counts(dropna=False)

NaN        251
0.000      185
1.000        2
132.000      1
Name: co_emissions, dtype: int64

In [ ]:
df[df["fuel_type"] == "Benzine"]["co_emissions"].value_counts(dropna=False)

NaN        6020
0.000       673
124.000     241
119.000     235
114.000     217
115.000     199
99.000      199
139.000     187
125.000     179
108.000     179
149.000     172
123.000     165
138.000     163
129.000     157
178.000     155
109.000     151
110.000     148
130.000     146
145.000     146
126.000     139
112.000     132
134.000     131
117.000     130
120.000     125
113.000     121
127.000     121
88.000      120
128.000     119
107.000     115
116.000     114
111.000     114
155.000     112
93.000      111
133.000     111
121.000     109
154.000     107
140.000     106
104.000     106
148.000     102
122.000     100
103.000      98
105.000      95
136.000      92
166.000      91
159.000      89
142.000      88
156.000      87
144.000      85
118.000      85
135.000      84
92.000       83
106.000      83
164.000      83
102.000      80
147.000      79
171.000      79
161.000      78
158.000      78
152.000      77
137.000      77
174.000      73
132.000      73
191.000      72
96.000       71
95.000       71
131.000      70
167.000      69
143.000      66
153.000      65
273.000      65
169.000      65
218.000      63
170.000      62
175.000      62
97.000       60
177.000      58
230.000      58
165.000      57
185.000      56
146.000      53
101.000      52
229.000      52
141.000      52
179.000      52
98.000       51
157.000      51
173.000      50
196.000      50
168.000      49
150.000      49
184.000      49
194.000      48
180.000      48
181.000      47
160.000      47
162.000      46
176.000      45
190.000      45
212.000      42
195.000      42
34.000       41
219.000      41
200.000      41
163.000      40
85.000       39
261.000      38
209.000      38
26.000       36
151.000      36
41.000       36
197.000      36
225.000      35
94.000       34
76.000       33
248.000      32
192.000      32
289.000      32
275.000      32
263.000      32
234.000      32
199.000      31
284.000      30
268.000      30
64.000       30
84.000       29
253.000      28
215.000      27
187.000      26
42.000       26
182.000      26
280.000      25
189.000      25
38.000       24
220.000      24
279.000      24
226.000      23
242.000      23
89.000       23
100.000      23
186.000      23
75.000       22
214.000      22
245.000      22
183.000      22
211.000      22
288.000      22
188.000      21
40.000       21
217.000      21
270.000      20
39.000       20
254.000      20
202.000      19
216.000      19
205.000      19
236.000      18
86.000       18
193.000      18
31.000       18
201.000      17
49.000       17
91.000       17
210.000      17
79.000       17
299.000      16
35.000       16
208.000      16
246.000      15
278.000      15
204.000      15
262.000      15
235.000      15
252.000      15
87.000       14
259.000      14
198.000      14
90.000       14
250.000      13
232.000      13
203.000      13
221.000      13
244.000      12
172.000      12
47.000       12
238.000      12
25.000       12
83.000       12
213.000      12
247.000      12
285.000      12
206.000      11
277.000      11
54.000       11
256.000      11
258.000      11
78.000       10
1.000        10
298.000      10
32.000        9
249.000       9
311.000       9
281.000       9
287.000       8
44.000        8
46.000        8
267.000       8
237.000       8
251.000       8
223.000       8
240.000       8
260.000       8
282.000       8
255.000       8
224.000       8
207.000       8
82.000        7
295.000       7
239.000       7
292.000       7
265.000       7
306.000       6
29.000        6
228.000       6
51.000        6
330.000       6
312.000       6
296.000       6
22.000        5
14.000        5
28.000        5
269.000       5
37.000        5
283.000       5
66.000        5
222.000       5
52.000        5
68.000        5
33.000        5
257.000       5
241.000       4
243.000       4
271.000       4
55.000        4
81.000        4
50.000        4
274.000       4
320.000       4
276.000       4
327.000       4
322.000       4
303.000       4
27.000        3
300.000       3
227.000       3
43.000        3
36.000        3
319.000       3
324.000       3
310.000       3
15.000        3
17.000        3
30.000        3
231.000       3
233.000       2
8.000         2
400.000       2
336.000       2
10.000        2
24.000        2
293.000       2
290.000       2
45.000        2
65.000        2
340.000       2
56.000        2
48.000        2
16.000        2
9.000         1
316.000       1
910.000       1
71.000        1
307.000       1
314.000       1
420.000       1
313.000       1
339.000       1
294.000       1
342.000       1
394.000       1
350.000       1
399.000       1
398.000       1
345.000       1
308.000       1
377.000       1
19.000        1
13.000        1
20.000        1
335.000       1
317.000       1
21.000        1
348.000       1
18.000        1
373.000       1
344.000       1
341.000       1
59.000        1
23.000        1
70.000        1
321.000       1
338.000       1
266.000       1
326.000       1
304.000       1
328.000       1
5.000         1
3.000         1
272.000       1
332.000       1
343.000       1
73.000        1
53.000        1
Name: co_emissions, dtype: int64

In [ ]:
df.loc[df["fuel_type"] == "Electric", "co_emissions"]

1         0.000
93          NaN
94          NaN
108         NaN
1213      0.000
1226      0.000
1271      0.000
1273        NaN
1281        NaN
1283        NaN
1303        NaN
1304        NaN
1307      0.000
1326        NaN
1331        NaN
1341        NaN
1350        NaN
1361        NaN
1364        NaN
1369        NaN
1400        NaN
1416        NaN
1425        NaN
1427        NaN
1436      0.000
1447      0.000
1458      0.000
1513        NaN
1575        NaN
1628        NaN
1641        NaN
1777        NaN
1798        NaN
1998      0.000
2000        NaN
2004        NaN
2015      0.000
2045        NaN
2082        NaN
2084        NaN
2086        NaN
2099        NaN
2130        NaN
2144        NaN
2156        NaN
2161        NaN
2166      0.000
2182        NaN
2192        NaN
2199        NaN
2230        NaN
2246      0.000
2255        NaN
2272        NaN
2276        NaN
2278        NaN
2301      0.000
2312        NaN
2317        NaN
2322        NaN
2328        NaN
2331        NaN
2355        NaN
2356        NaN
2360        NaN
2372        NaN
2713      0.000
3663      0.000
4810        NaN
4819        NaN
4823      0.000
4826        NaN
4838        NaN
4840      0.000
4873        NaN
4886      0.000
4914      0.000
4923        NaN
4929        NaN
4939        NaN
4943      0.000
4952        NaN
4957        NaN
4963        NaN
4972        NaN
4973      0.000
4985        NaN
4986        NaN
4989        NaN
4998        NaN
5002        NaN
5026        NaN
5028        NaN
5040      0.000
5045        NaN
5046        NaN
5047        NaN
5051      0.000
5054        NaN
5067        NaN
5071        NaN
5074        NaN
5075        NaN
5080        NaN
5087        NaN
5093        NaN
5097        NaN
5100        NaN
5102        NaN
5116        NaN
5117        NaN
5120      0.000
5122        NaN
5129        NaN
5134      0.000
5140        NaN
5143        NaN
5148      0.000
5149      0.000
5163        NaN
5166        NaN
5167        NaN
5199      0.000
5430        NaN
5748      0.000
5786        NaN
5816        NaN
5831    132.000
5919      0.000
5936        NaN
6166        NaN
6205        NaN
6795        NaN
6803      0.000
6810      0.000
6811        NaN
6824        NaN
6830        NaN
6835        NaN
6837        NaN
6839        NaN
6847        NaN
6849        NaN
6852        NaN
6854        NaN
6860        NaN
6869        NaN
6870        NaN
6874        NaN
6876        NaN
6878        NaN
6879      0.000
6882        NaN
6896        NaN
6907      0.000
6909        NaN
6912        NaN
6916      0.000
6918        NaN
6943        NaN
6951      0.000
6952        NaN
6958      0.000
6982      0.000
7060      0.000
7071      0.000
7102      0.000
7103      0.000
7113      0.000
7114      0.000
7116      0.000
7124      0.000
7127      0.000
7132      0.000
7156      0.000
7232      0.000
7316        NaN
7335      0.000
7397        NaN
7408        NaN
7461      0.000
7480      0.000
7525      0.000
8400        NaN
8670      0.000
8876      0.000
8899      0.000
9005      0.000
9070      0.000
9079      0.000
9082      0.000
9087      0.000
9088      0.000
9089      0.000
9091      0.000
9102      1.000
9152      0.000
9154      0.000
9366      0.000
9426      0.000
9428      0.000
9448      0.000
9455      0.000
9473      0.000
9481      0.000
9487      0.000
9501      0.000
9514        NaN
9515      0.000
9522        NaN
9524      0.000
9527        NaN
9532        NaN
9538        NaN
9539        NaN
9540        NaN
9544      0.000
9545      0.000
9603      0.000
9608        NaN
9620        NaN
9654      0.000
9692      0.000
9699      0.000
9706        NaN
9716      0.000
9720        NaN
9795      0.000
9859      0.000
9889      0.000
9894        NaN
9918        NaN
9984      0.000
10023       NaN
10033     0.000
10039       NaN
10069     0.000
10074     0.000
10098       NaN
10104     0.000
10183     0.000
10215     0.000
10246     0.000
10258     0.000
10467     0.000
10566       NaN
10617     0.000
10625     0.000
10630     0.000
10631     0.000
10668     0.000
11467       NaN
11479       NaN
11544     0.000
11558     0.000
11572     0.000
11577     0.000
11578     0.000
11595     0.000
11619     0.000
11620     0.000
11632     0.000
11640     0.000
11641       NaN
11648       NaN
11653     0.000
11655     0.000
11665     0.000
11672       NaN
11673     0.000
11676       NaN
11690       NaN
11730     0.000
11776     0.000
11801     0.000
13978     0.000
13995       NaN
14055       NaN
14057     0.000
14066       NaN
14118       NaN
14188       NaN
14196       NaN
14212       NaN
14235       NaN
14248       NaN
14277       NaN
14284       NaN
14300       NaN
14316       NaN
14317       NaN
14952       NaN
15141       NaN
15143       NaN
15144       NaN
15145       NaN
15146       NaN
15147       NaN
15148       NaN
15149       NaN
15150       NaN
15151       NaN
15152       NaN
15153       NaN
15155       NaN
15156       NaN
15157       NaN
15158       NaN
15159       NaN
15161       NaN
15166       NaN
15181       NaN
15182       NaN
15183       NaN
15184       NaN
15185       NaN
15186       NaN
15187       NaN
15214       NaN
15648     0.000
15667     0.000
15903       NaN
16296       NaN
16312       NaN
16315       NaN
16319       NaN
16344       NaN
16351       NaN
16405       NaN
16416       NaN
16471     0.000
17699     0.000
17701     0.000
17718     0.000
17720     0.000
18114     0.000
18716     0.000
18725     0.000
18726     0.000
18730     0.000
18733     0.000
18742     0.000
18752       NaN
18759       NaN
18774       NaN
18779       NaN
18782       NaN
18784       NaN
18785       NaN
18786       NaN
18787     0.000
18789       NaN
18794       NaN
18795       NaN
18796     0.000
18807       NaN
18812       NaN
18816       NaN
18817       NaN
18819     0.000
18822     0.000
18836     0.000
18861     0.000
18866       NaN
18880     0.000
18917     0.000
18964     0.000
18990       NaN
19025     0.000
19080     0.000
20076     0.000
20414       NaN
20464       NaN
20480       NaN
20484       NaN
20487       NaN
20507     0.000
20516     0.000
20523     0.000
20533     0.000
20534       NaN
20535       NaN
20536       NaN
20537     0.000
20539     0.000
20540     0.000
20546       NaN
20551       NaN
20552       NaN
20557     0.000
20562     0.000
20563     0.000
20571       NaN
20582     1.000
20599       NaN
20600     0.000
20602     0.000
21623       NaN
21937       NaN
21948     0.000
21955     0.000
21957     0.000
21958     0.000
21960       NaN
21963       NaN
21966       NaN
21979       NaN
21986       NaN
21990       NaN
21994       NaN
22004       NaN
22008       NaN
22028       NaN
22029       NaN
22047       NaN
22048     0.000
22185       NaN
22247     0.000
22775       NaN
22783     0.000
22823       NaN
23379     0.000
23809     0.000
23870     0.000
23951     0.000
24051     0.000
24092     0.000
24099     0.000
24123     0.000
24170     0.000
24173     0.000
24832     0.000
24851     0.000
26952     0.000
26985     0.000
27338     0.000
27367     0.000
28340     0.000
28528     0.000
Name: co_emissions, dtype: float64

In [ ]:
df.loc[df["fuel_type"] == "Electric", "co_emissions"] = df.loc[df["fuel_type"] == "Electric", "co_emissions"].fillna(df.loc[df["fuel_type"] == "Electric", "co_emissions"].mode()[0])
df.loc[df["fuel_type"] == "Electric", "co_emissions"]

1         0.000
93        0.000
94        0.000
108       0.000
1213      0.000
1226      0.000
1271      0.000
1273      0.000
1281      0.000
1283      0.000
1303      0.000
1304      0.000
1307      0.000
1326      0.000
1331      0.000
1341      0.000
1350      0.000
1361      0.000
1364      0.000
1369      0.000
1400      0.000
1416      0.000
1425      0.000
1427      0.000
1436      0.000
1447      0.000
1458      0.000
1513      0.000
1575      0.000
1628      0.000
1641      0.000
1777      0.000
1798      0.000
1998      0.000
2000      0.000
2004      0.000
2015      0.000
2045      0.000
2082      0.000
2084      0.000
2086      0.000
2099      0.000
2130      0.000
2144      0.000
2156      0.000
2161      0.000
2166      0.000
2182      0.000
2192      0.000
2199      0.000
2230      0.000
2246      0.000
2255      0.000
2272      0.000
2276      0.000
2278      0.000
2301      0.000
2312      0.000
2317      0.000
2322      0.000
2328      0.000
2331      0.000
2355      0.000
2356      0.000
2360      0.000
2372      0.000
2713      0.000
3663      0.000
4810      0.000
4819      0.000
4823      0.000
4826      0.000
4838      0.000
4840      0.000
4873      0.000
4886      0.000
4914      0.000
4923      0.000
4929      0.000
4939      0.000
4943      0.000
4952      0.000
4957      0.000
4963      0.000
4972      0.000
4973      0.000
4985      0.000
4986      0.000
4989      0.000
4998      0.000
5002      0.000
5026      0.000
5028      0.000
5040      0.000
5045      0.000
5046      0.000
5047      0.000
5051      0.000
5054      0.000
5067      0.000
5071      0.000
5074      0.000
5075      0.000
5080      0.000
5087      0.000
5093      0.000
5097      0.000
5100      0.000
5102      0.000
5116      0.000
5117      0.000
5120      0.000
5122      0.000
5129      0.000
5134      0.000
5140      0.000
5143      0.000
5148      0.000
5149      0.000
5163      0.000
5166      0.000
5167      0.000
5199      0.000
5430      0.000
5748      0.000
5786      0.000
5816      0.000
5831    132.000
5919      0.000
5936      0.000
6166      0.000
6205      0.000
6795      0.000
6803      0.000
6810      0.000
6811      0.000
6824      0.000
6830      0.000
6835      0.000
6837      0.000
6839      0.000
6847      0.000
6849      0.000
6852      0.000
6854      0.000
6860      0.000
6869      0.000
6870      0.000
6874      0.000
6876      0.000
6878      0.000
6879      0.000
6882      0.000
6896      0.000
6907      0.000
6909      0.000
6912      0.000
6916      0.000
6918      0.000
6943      0.000
6951      0.000
6952      0.000
6958      0.000
6982      0.000
7060      0.000
7071      0.000
7102      0.000
7103      0.000
7113      0.000
7114      0.000
7116      0.000
7124      0.000
7127      0.000
7132      0.000
7156      0.000
7232      0.000
7316      0.000
7335      0.000
7397      0.000
7408      0.000
7461      0.000
7480      0.000
7525      0.000
8400      0.000
8670      0.000
8876      0.000
8899      0.000
9005      0.000
9070      0.000
9079      0.000
9082      0.000
9087      0.000
9088      0.000
9089      0.000
9091      0.000
9102      1.000
9152      0.000
9154      0.000
9366      0.000
9426      0.000
9428      0.000
9448      0.000
9455      0.000
9473      0.000
9481      0.000
9487      0.000
9501      0.000
9514      0.000
9515      0.000
9522      0.000
9524      0.000
9527      0.000
9532      0.000
9538      0.000
9539      0.000
9540      0.000
9544      0.000
9545      0.000
9603      0.000
9608      0.000
9620      0.000
9654      0.000
9692      0.000
9699      0.000
9706      0.000
9716      0.000
9720      0.000
9795      0.000
9859      0.000
9889      0.000
9894      0.000
9918      0.000
9984      0.000
10023     0.000
10033     0.000
10039     0.000
10069     0.000
10074     0.000
10098     0.000
10104     0.000
10183     0.000
10215     0.000
10246     0.000
10258     0.000
10467     0.000
10566     0.000
10617     0.000
10625     0.000
10630     0.000
10631     0.000
10668     0.000
11467     0.000
11479     0.000
11544     0.000
11558     0.000
11572     0.000
11577     0.000
11578     0.000
11595     0.000
11619     0.000
11620     0.000
11632     0.000
11640     0.000
11641     0.000
11648     0.000
11653     0.000
11655     0.000
11665     0.000
11672     0.000
11673     0.000
11676     0.000
11690     0.000
11730     0.000
11776     0.000
11801     0.000
13978     0.000
13995     0.000
14055     0.000
14057     0.000
14066     0.000
14118     0.000
14188     0.000
14196     0.000
14212     0.000
14235     0.000
14248     0.000
14277     0.000
14284     0.000
14300     0.000
14316     0.000
14317     0.000
14952     0.000
15141     0.000
15143     0.000
15144     0.000
15145     0.000
15146     0.000
15147     0.000
15148     0.000
15149     0.000
15150     0.000
15151     0.000
15152     0.000
15153     0.000
15155     0.000
15156     0.000
15157     0.000
15158     0.000
15159     0.000
15161     0.000
15166     0.000
15181     0.000
15182     0.000
15183     0.000
15184     0.000
15185     0.000
15186     0.000
15187     0.000
15214     0.000
15648     0.000
15667     0.000
15903     0.000
16296     0.000
16312     0.000
16315     0.000
16319     0.000
16344     0.000
16351     0.000
16405     0.000
16416     0.000
16471     0.000
17699     0.000
17701     0.000
17718     0.000
17720     0.000
18114     0.000
18716     0.000
18725     0.000
18726     0.000
18730     0.000
18733     0.000
18742     0.000
18752     0.000
18759     0.000
18774     0.000
18779     0.000
18782     0.000
18784     0.000
18785     0.000
18786     0.000
18787     0.000
18789     0.000
18794     0.000
18795     0.000
18796     0.000
18807     0.000
18812     0.000
18816     0.000
18817     0.000
18819     0.000
18822     0.000
18836     0.000
18861     0.000
18866     0.000
18880     0.000
18917     0.000
18964     0.000
18990     0.000
19025     0.000
19080     0.000
20076     0.000
20414     0.000
20464     0.000
20480     0.000
20484     0.000
20487     0.000
20507     0.000
20516     0.000
20523     0.000
20533     0.000
20534     0.000
20535     0.000
20536     0.000
20537     0.000
20539     0.000
20540     0.000
20546     0.000
20551     0.000
20552     0.000
20557     0.000
20562     0.000
20563     0.000
20571     0.000
20582     1.000
20599     0.000
20600     0.000
20602     0.000
21623     0.000
21937     0.000
21948     0.000
21955     0.000
21957     0.000
21958     0.000
21960     0.000
21963     0.000
21966     0.000
21979     0.000
21986     0.000
21990     0.000
21994     0.000
22004     0.000
22008     0.000
22028     0.000
22029     0.000
22047     0.000
22048     0.000
22185     0.000
22247     0.000
22775     0.000
22783     0.000
22823     0.000
23379     0.000
23809     0.000
23870     0.000
23951     0.000
24051     0.000
24092     0.000
24099     0.000
24123     0.000
24170     0.000
24173     0.000
24832     0.000
24851     0.000
26952     0.000
26985     0.000
27338     0.000
27367     0.000
28340     0.000
28528     0.000
Name: co_emissions, dtype: float64

In [ ]:
df.loc[(df["fuel_type"] == "Electric") & (df["co_emissions"] != 0)][["fuel_type", "co_emissions"]]

      fuel_type  co_emissions
5831   Electric       132.000
9102   Electric         1.000
20582  Electric         1.000

In [ ]:
df.iloc[5831]

make_model                                                    Renault Arkana
make                                                                 Renault
location                   Via Nazionale, 29,  33010 Reana del Rojale - U...
price                                                              27500.000
body_type                                                              Coupe
type                                                          Pre-registered
doors                                                                  5.000
warranty                                                                  No
mileage                                                               10.000
gearbox                                                            Automatic
fuel_type                                                           Electric
seller                                                                Dealer
seats                                                                  5.000
engine_size                                                         1333.000
gears                                                                  7.000
co_emissions                                                         132.000
drivetrain                                                             Front
cylinders                                                              4.000
comfort_&_convenience      Air conditioning, Armrest, Automatic climate c...
entertainment_&_media                  Apple CarPlay, Digital cockpit, Radio
safety_&_security          ABS, Adaptive Cruise Control, Blind spot monit...
extras                     Alloy wheels (18"), Automatically dimming inte...
empty_weight                                                        1336.000
full_service_history                                                      No
upholstery                                                               NaN
previous_owner                                                         1.000
energy_efficiency_class                                                  NaN
age                                                                    0.000
power_kW                                                             103.000
power_hp                                                             140.000
cons_avg                                                                 NaN
cons_city                                                                NaN
cons_country                                                             NaN
Name: 5831, dtype: object

In [ ]:
df.loc[df["make_model"] == "Renault Arkana"][["gearbox", "fuel_type", "gears", "co_emissions"]]

        gearbox fuel_type  gears  co_emissions
5612  Automatic   Benzine  7.000           NaN
5615  Automatic   Benzine  7.000           NaN
5618  Automatic   Benzine  7.000           NaN
5622  Automatic   Benzine  7.000           NaN
5623  Automatic   Benzine  7.000           NaN
5624  Automatic   Benzine  7.000           NaN
5625  Automatic   Benzine  6.000           NaN
5626  Automatic   Benzine  7.000           NaN
5627  Automatic   Benzine  7.000       133.000
5637  Automatic   Benzine  7.000       132.000
5646  Automatic   Benzine  6.000           NaN
5664  Automatic   Benzine  7.000           NaN
5788  Automatic   Benzine  7.000       133.000
5831  Automatic  Electric  7.000       132.000
5839  Automatic   Benzine  7.000           NaN
5862  Automatic   Benzine  7.000           NaN
5886  Automatic   Benzine  7.000       135.000
5905  Automatic   Benzine  7.000           NaN
5943  Automatic   Benzine  7.000       132.000
5958  Automatic   Benzine  7.000       132.000
5963  Automatic   Benzine  7.000       131.000
5977  Automatic   Benzine  7.000       124.000
5994  Automatic   Benzine  7.000       124.000
5995  Automatic   Benzine  4.000           NaN
5996  Automatic   Benzine  7.000        96.000
5999  Automatic   Benzine  7.000       124.000
6003  Automatic   Benzine  7.000       100.000
6010  Automatic   Benzine  7.000       124.000
6022  Automatic   Benzine  7.000           NaN
6034  Automatic   Benzine  7.000        96.000
6053  Automatic   Benzine  7.000           NaN
6061  Automatic   Benzine  7.000       122.000
6062  Automatic   Benzine  7.000       124.000
6066  Automatic   Benzine  7.000           NaN
6081  Automatic   Benzine  7.000       124.000
6106  Automatic   Benzine  7.000       134.000
6116  Automatic   Benzine  7.000        96.000
6161  Automatic   Benzine  7.000        97.000
6172  Automatic   Benzine  7.000           NaN
6175  Automatic   Benzine  7.000       121.000
6182  Automatic   Benzine  7.000           NaN
6183  Automatic   Benzine  7.000           NaN
6192  Automatic   Benzine  7.000         0.000
6194  Automatic   Benzine  1.000        96.000
6198  Automatic   Benzine  7.000       124.000
6209  Automatic   Benzine  7.000       124.000
6210  Automatic   Benzine  7.000       124.000
6220  Automatic   Benzine  7.000         0.000
6226  Automatic   Benzine  7.000       122.000
6228  Automatic   Benzine  7.000       124.000
6231  Automatic   Benzine  7.000       124.000
6239  Automatic   Benzine  7.000           NaN
6255  Automatic   Benzine  7.000         0.000
6264  Automatic   Benzine  7.000       122.000
6266  Automatic   Benzine  7.000           NaN
6267  Automatic   Benzine  7.000       124.000
6273  Automatic   Benzine  7.000        96.000
6299  Automatic   Benzine  7.000         0.000
6317  Automatic   Benzine  7.000           NaN
6321  Automatic   Benzine  7.000           NaN
6788  Automatic   Benzine  7.000       124.000
6797  Automatic   Benzine  7.000       124.000
6838  Automatic   Benzine  7.000       124.000
7074  Automatic   Benzine  7.000       121.000

In [ ]:
# df.at[5831, "fuel_type"] = "Benzine" 
# df.loc[index, "fuel_type"] = "Benzine" 

df.iloc[5831, df.columns.get_loc("fuel_type")] = "Benzine"

In [ ]:
df.loc[5831]["fuel_type"]

'Benzine'

# Step-1

df['co_emissions'].fillna(df["co_emissions"].median(), inplace = True)

# Step-2

df['co_emissions'].fillna(df.groupby("make_model")["co_emissions"].transform("median"), inplace=True)

# Step-3

df['co_emissions'].fillna(df.groupby(["make_model", "body_type"])["co_emissions"].transform("median"), inplace=True)

# Step-3

df['co_emissions'].fillna(df.groupby(["make_model", "body_type", "fuel_type"])["co_emissions"].transform("median"), inplace=True)

In [ ]:
def fill_median(df, group_col1, group_col2, group_col3, col_name):
    
    df[col_name].fillna(df.groupby([group_col1, group_col2, group_col3])[col_name].transform("median"), inplace = True)
    df[col_name].fillna(df.groupby([group_col1, group_col2])[col_name].transform("median"), inplace = True)
    df[col_name].fillna(df.groupby(group_col1)[col_name].transform("median"), inplace = True)
    df[col_name].fillna(df[col_name].median(), inplace = True)

    print("column name    : ", col_name)
    print("--------------------------------")
    print("per_of_nulls   : ", "%", round(df[col_name].isnull().sum()*100 / df.shape[0], 2))
    print("num_of_nulls   : ", df[col_name].isnull().sum())
    print("num_of_uniques : ", df[col_name].nunique())
    print("--------------------------------")
    print(df[col_name].value_counts(dropna = False))

In [ ]:
fill_median(df, "make_model", "body_type", "fuel_type", "co_emissions")

column name    :  co_emissions
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  389
--------------------------------
0.000      1410
124.000    1080
115.000     681
99.000      588
119.000     574
89.000      549
129.000     528
117.000     521
139.000     467
109.000     456
108.000     454
114.000     410
113.000     386
110.000     380
123.000     375
104.000     364
116.000     358
130.000     355
120.000     335
138.000     332
149.000     328
127.000     310
125.000     306
112.000     288
105.000     273
107.000     257
93.000      250
111.000     250
178.000     239
273.000     234
98.000      233
128.000     233
126.000     228
145.000     227
96.000      216
121.000     213
118.000     212
137.000     210
276.000     208
142.000     206
95.000      204
85.000      199
155.000     197
133.000     196
135.000     195
131.000     194
148.000     194
122.000     193
143.000     193
106.000     190
167.000     189
154.000     184
134.000     181
102.000     175
147.000     173
169.000     173
144.000     169
185.000     168
159.000     168
156.000     167
232.000     163
166.000     162
88.000      161
103.000     160
132.000     155
136.000     155
140.000     148
158.000     146
162.000     144
92.000      143
94.000      142
161.000     141
196.000     140
101.000     135
97.000      133
230.000     124
170.000     124
150.000     117
146.000     116
151.000     109
194.000     109
164.000     105
153.000     105
174.000     104
152.000     102
87.000      102
248.000      95
173.000      92
180.000      91
141.000      91
165.000      90
171.000      88
184.000      86
193.000      84
90.000       84
191.000      83
160.000      76
168.000      76
175.000      76
84.000       75
177.000      74
218.000      73
79.000       72
100.000      71
157.000      70
212.000      66
195.000      63
179.000      63
219.000      62
163.000      60
181.000      58
190.000      57
226.000      57
101.500      56
82.000       56
229.000      55
277.000      54
106.500      53
189.000      53
99.500       52
234.000      52
176.000      51
199.000      50
107.500      49
209.000      46
250.000      46
34.000       46
192.000      45
42.000       44
91.000       44
217.000      43
200.000      43
225.000      42
261.000      41
183.000      41
197.000      40
26.000       40
41.000       39
182.000      39
49.000       39
257.000      38
125.500      38
210.000      36
187.000      35
186.000      35
275.000      33
76.000       33
289.000      33
253.000      32
220.000      32
263.000      32
214.000      32
172.000      32
280.000      31
268.000      31
188.000      31
211.000      31
215.000      30
64.000       30
284.000      30
38.000       30
86.000       30
88.500       30
47.000       29
242.000      29
87.500       28
238.000      28
112.500      28
131.500      28
94.500       28
116.500      27
40.000       27
216.000      26
198.000      26
202.000      25
39.000       25
279.000      24
254.000      24
247.000      24
3.000        24
208.000      22
205.000      22
245.000      22
75.000       22
288.000      22
22.000       22
36.000       21
121.500      21
35.000       21
236.000      20
270.000      20
134.500      20
276.500      19
201.000      19
222.500      19
1.000        18
252.000      18
223.000      18
31.000       18
54.000       18
48.000       18
262.000      17
161.500      17
246.000      17
32.000       16
204.000      16
235.000      16
299.000      16
203.000      16
213.000      15
259.000      15
278.000      15
46.000       15
260.000      15
186.500      14
330.000      14
224.000      14
50.000       14
133.500      14
206.000      14
295.000      14
83.000       14
244.000      14
138.500      14
207.000      13
221.000      13
146.500      13
25.000       13
285.000      12
256.000      11
44.000       11
227.000      11
281.000      11
141.500      11
126.500      11
258.000      11
51.000       10
228.000      10
298.000      10
231.000      10
222.000      10
249.000      10
78.000       10
282.000      10
240.000      10
152.500      10
178.500       9
239.000       9
103.500       9
311.000       9
33.000        9
336.000       9
37.000        9
287.000       8
66.000        8
350.000       8
110.500       8
10.000        8
29.000        8
28.000        8
255.000       8
267.000       8
251.000       8
292.000       8
52.000        8
59.000        8
237.000       8
293.000       7
266.500       7
265.000       7
55.000        6
312.000       6
306.000       6
104.500       6
296.000       6
310.000       5
149.500       5
327.000       5
43.000        5
283.000       5
269.000       5
68.000        5
30.000        5
14.000        5
24.000        4
320.000       4
274.000       4
243.000       4
261.500       4
81.000        4
27.000        4
199.500       4
241.000       4
303.000       4
322.000       4
203.500       4
170.500       4
271.000       4
300.000       3
150.500       3
113.500       3
0.500         3
139.500       3
324.000       3
188.500       3
18.000        3
15.000        3
319.000       3
17.000        3
136.500       3
8.000         2
400.000       2
233.000       2
290.000       2
120.500       2
340.000       2
179.500       2
227.500       2
63.500        2
414.000       2
16.000        2
45.000        2
308.000       2
55.500        2
65.000        2
56.000        2
332.000       2
190.500       2
142.500       2
23.000        2
56.500        2
7.000         2
264.000       2
313.000       1
940.000       1
316.000       1
294.000       1
420.000       1
394.000       1
272.000       1
398.000       1
128.500       1
307.000       1
910.000       1
9.000         1
399.000       1
167.500       1
314.000       1
71.000        1
339.000       1
317.000       1
342.000       1
373.000       1
377.000       1
197.500       1
266.000       1
118.500       1
169.500       1
341.000       1
344.000       1
348.000       1
75.500        1
13.000        1
345.000       1
19.000        1
20.000        1
37.500        1
216.500       1
21.000        1
80.000        1
321.000       1
157.500       1
5.000         1
70.000        1
73.000        1
343.000       1
156.500       1
328.000       1
304.000       1
326.000       1
108.500       1
111.500       1
127.500       1
335.000       1
338.000       1
95.500        1
146.750       1
123.500       1
53.000        1
Name: co_emissions, dtype: int64

## cylinders

In [ ]:
first_looking("cylinders")

COLUMN NAME    :  cylinders
--------------------------------
per_of_nulls   :  % 34.15
num_of_nulls   :  9778
num_of_uniques :  12
--------------------------------
4.000     13068
NaN        9778
3.000      3258
6.000      1013
5.000       799
8.000       539
2.000       103
0.000        35
1.000        21
12.000        8
7.000         6
26.000        1
16.000        1
Name: cylinders, dtype: int64

In [ ]:
df["cylinders"].fillna("-", inplace=True)

In [ ]:
df.groupby(["make_model", "body_type", "age", "cylinders"]).price.describe()

                                               count      mean      std  \
make_model  body_type        age    cylinders
Dacia       Compact          0.000  -          2.000 22389.000  127.279
                             1.000  -          1.000 19515.000      NaN
            Sedan            47.000 4.0        1.000  9999.000      NaN
            Station wagon    0.000  -          1.000 21799.000      NaN
Dacia Break Station wagon    0.000  -          1.000 20500.000      NaN
...                                              ...       ...      ...
Volvo XC90  Off-Road/Pick-up 18.000 5.0        2.000  6799.000    0.000
            Sedan            1.000  -          1.000 84900.000      NaN
                             3.000  -          1.000 48500.000      NaN
                             4.000  -          1.000 47700.000      NaN
            Station wagon    6.000  4.0        4.000 32750.000 3752.777

                                                    min       25%       50%  \
make_model  body_type        age    cylinders
Dacia       Compact          0.000  -         22299.000 22344.000 22389.000
                             1.000  -         19515.000 19515.000 19515.000
            Sedan            47.000 4.0        9999.000  9999.000  9999.000
            Station wagon    0.000  -         21799.000 21799.000 21799.000
Dacia Break Station wagon    0.000  -         20500.000 20500.000 20500.000
...                                                 ...       ...       ...
Volvo XC90  Off-Road/Pick-up 18.000 5.0        6799.000  6799.000  6799.000
            Sedan            1.000  -         84900.000 84900.000 84900.000
                             3.000  -         48500.000 48500.000 48500.000
                             4.000  -         47700.000 47700.000 47700.000
            Station wagon    6.000  4.0       29500.000 29500.000 32750.000

                                                    75%       max
make_model  body_type        age    cylinders
Dacia       Compact          0.000  -         22434.000 22479.000
                             1.000  -         19515.000 19515.000
            Sedan            47.000 4.0        9999.000  9999.000
            Station wagon    0.000  -         21799.000 21799.000
Dacia Break Station wagon    0.000  -         20500.000 20500.000
...                                                 ...       ...
Volvo XC90  Off-Road/Pick-up 18.000 5.0        6799.000  6799.000
            Sedan            1.000  -         84900.000 84900.000
                             3.000  -         48500.000 48500.000
                             4.000  -         47700.000 47700.000
            Station wagon    6.000  4.0       36000.000 36000.000

[7494 rows x 8 columns]

In [ ]:
df["cylinders"].replace("-", np.nan, inplace=True)

In [ ]:
fill(df, "make_model", "body_type", "cylinders", "mode")

COLUMN NAME    :  cylinders
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  12
--------------------------------
0.000       187
1.000       136
2.000       107
3.000      5148
4.000     19798
5.000       970
6.000      1322
7.000         6
8.000       943
12.000       11
16.000        1
26.000        1
Name: cylinders, dtype: int64

**However, it is preferred to drop the ``cylinders`` feature in this analysis since there have been some other features, such as ``"hp``, ``engine_size``, ``empty_weight``", having fewer missing values and giving similar insight. So it's assumed to continue without the ``cylinders`` feature in this analysis.**

In [ ]:
df.shape

(28630, 33)

In [ ]:
df.drop("cylinders", axis=1, inplace=True)

In [ ]:
df.shape

(28630, 32)

## power_kW

In [ ]:
first_looking("power_kW")

COLUMN NAME    :  power_kW
--------------------------------
per_of_nulls   :  % 2.0
num_of_nulls   :  572
num_of_uniques :  351
--------------------------------
110.000    1992
96.000     1356
88.000     1182
81.000     1166
66.000     1110
103.000    1033
85.000     1002
74.000      892
140.000     787
51.000      701
70.000      685
100.000     681
NaN         572
55.000      515
92.000      477
147.000     458
125.000     422
120.000     418
80.000      349
132.000     339
90.000      318
135.000     296
173.000     249
118.000     247
115.000     246
130.000     241
84.000      240
77.000      236
221.000     234
150.000     232
206.000     224
67.000      213
82.000      204
63.000      200
145.000     199
97.000      185
53.000      176
104.000     163
288.000     155
59.000      149
143.000     143
73.000      139
184.000     138
121.000     134
44.000      133
60.000      133
180.000     130
165.000     130
75.000      128
68.000      127
202.000     126
107.000     124
54.000      120
190.000     119
331.000     118
241.000     117
162.000     115
52.000      112
99.000      111
228.000     105
225.000     104
169.000     103
87.000      102
133.000     100
310.000      99
105.000      99
50.000       99
112.000      98
65.000       97
117.000      92
114.000      89
270.000      86
49.000       84
62.000       83
250.000      81
213.000      81
108.000      80
243.000      79
155.000      79
245.000      76
142.000      70
287.000      64
64.000       63
116.000      63
160.000      63
195.000      61
223.000      60
136.000      59
113.000      56
320.000      55
194.000      53
350.000      51
375.000      51
98.000       50
72.000       50
300.000      50
154.000      49
176.000      49
79.000       48
336.000      47
43.000       45
338.000      45
93.000       44
224.000      43
233.000      43
430.000      43
192.000      42
33.000       42
200.000      41
101.000      40
71.000       39
86.000       39
330.000      39
102.000      38
251.000      37
215.000      36
265.000      36
177.000      36
91.000       36
185.000      35
210.000      34
419.000      34
134.000      34
48.000       33
78.000       32
138.000      32
280.000      32
129.000      31
450.000      30
191.000      30
137.000      29
231.000      28
170.000      27
157.000      27
128.000      26
152.000      26
186.000      25
83.000       25
175.000      25
76.000       24
95.000       24
61.000       24
410.000      24
285.000      24
232.000      24
57.000       23
40.000       22
253.000      22
163.000      21
141.000      21
235.000      20
199.000      20
119.000      20
205.000      20
220.000      19
151.000      19
335.000      19
158.000      19
257.000      18
298.000      17
122.000      16
56.000       15
227.000      15
123.000      14
404.000      14
187.000      14
153.000      14
308.000      14
166.000      13
156.000      13
201.000      13
208.000      13
168.000      13
47.000       12
178.000      12
294.000      12
109.000      11
139.000      11
386.000      11
69.000       11
172.000      11
258.000      11
127.000      10
13.000       10
239.000      10
390.000      10
182.000      10
94.000       10
212.000      10
405.000       9
559.000       9
198.000       9
343.000       9
188.000       9
35.000        9
149.000       9
207.000       8
124.000       8
385.000       8
324.000       8
131.000       8
470.000       7
18.000        7
380.000       7
299.000       7
370.000       7
345.000       7
146.000       6
271.000       6
174.000       6
111.000       6
295.000       6
203.000       6
148.000       6
37.000        6
32.000        6
392.000       6
368.000       6
240.000       6
353.000       6
307.000       6
360.000       5
1.000         5
357.000       5
126.000       5
167.000       5
248.000       5
286.000       5
230.000       5
17.000        5
193.000       5
279.000       4
214.000       4
340.000       4
441.000       4
400.000       4
246.000       4
420.000       4
196.000       4
45.000        4
309.000       4
339.000       4
106.000       4
487.000       4
313.000       4
25.000        3
387.000       3
58.000        3
38.000        3
8.000         3
588.000       3
216.000       3
89.000        3
229.000       3
218.000       3
293.000       3
567.000       3
36.000        3
484.000       3
29.000        3
266.000       3
46.000        3
463.000       2
412.000       2
244.000       2
552.000       2
363.000       2
292.000       2
312.000       2
31.000        2
209.000       2
316.000       2
9.000         2
7.000         2
274.000       2
4.000         2
222.000       2
12.000        2
290.000       2
23.000        2
19.000        2
189.000       2
161.000       2
14.000        2
346.000       2
34.000        2
311.000       2
267.000       2
662.000       2
358.000       2
354.000       2
485.000       1
328.000       1
238.000       1
39.000        1
342.000       1
303.000       1
6.000         1
530.000       1
551.000       1
493.000       1
234.000       1
332.000       1
372.000       1
499.000       1
144.000       1
365.000       1
341.000       1
255.000       1
3.000         1
403.000       1
325.000       1
527.000       1
237.000       1
254.000       1
217.000       1
20.000        1
30.000        1
10.000        1
42.000        1
22.000        1
27.000        1
16.000        1
24.000        1
384.000       1
15.000        1
41.000        1
409.000       1
537.000       1
373.000       1
378.000       1
242.000       1
924.000       1
236.000       1
810.000       1
21.000        1
183.000       1
496.000       1
664.000       1
600.000       1
327.000       1
478.000       1
665.000       1
284.000       1
883.000       1
296.000       1
164.000       1
746.000       1
570.000       1
471.000       1
179.000       1
26.000        1
Name: power_kW, dtype: int64

In [ ]:
df["power_kW"].fillna("-", inplace=True)

In [ ]:
df.groupby(["make_model", "body_type", "power_kW"]).price.describe()

                                        count      mean      std       min  \
make_model   body_type        power_kW
Dacia        Compact          33.0      3.000 21431.000 1661.744 19515.000
             Sedan            40.0      1.000  9999.000      NaN  9999.000
             Station wagon    81.0      1.000 21799.000      NaN 21799.000
Dacia Break  Station wagon    -         1.000 20500.000      NaN 20500.000
Dacia Dokker Compact          66.0      1.000 11930.000      NaN 11930.000
...                                       ...       ...      ...       ...
Volvo XC90   Off-Road/Pick-up 294.0     6.000 50793.333 6277.645 42790.000
                              300.0     2.000 44200.000    0.000 44200.000
             Sedan            173.0     2.000 48100.000  565.685 47700.000
                              223.0     1.000 84900.000      NaN 84900.000
             Station wagon    165.0     4.000 32750.000 3752.777 29500.000

                                             25%       50%       75%       max
make_model   body_type        power_kW
Dacia        Compact          33.0     20907.000 22299.000 22389.000 22479.000
             Sedan            40.0      9999.000  9999.000  9999.000  9999.000
             Station wagon    81.0     21799.000 21799.000 21799.000 21799.000
Dacia Break  Station wagon    -        20500.000 20500.000 20500.000 20500.000
Dacia Dokker Compact          66.0     11930.000 11930.000 11930.000 11930.000
...                                          ...       ...       ...       ...
Volvo XC90   Off-Road/Pick-up 294.0    45515.000 53690.000 55347.500 55900.000
                              300.0    44200.000 44200.000 44200.000 44200.000
             Sedan            173.0    47900.000 48100.000 48300.000 48500.000
                              223.0    84900.000 84900.000 84900.000 84900.000
             Station wagon    165.0    29500.000 32750.000 36000.000 36000.000

[5034 rows x 8 columns]

In [ ]:
df.loc[df["power_kW"] == "-"][["make_model", "body_type", "power_kW", "power_hp", "engine_size", "fuel_type"]]

,make_model,body_type,power_kW,power_hp,engine_size,fuel_type
0,Mercedes-Benz A 160,Compact,-,NaN,1595.000,Diesel
6,Mercedes-Benz CLA 180,Compact,-,NaN,1595.000,Diesel
94,Mercedes-Benz EQS,Compact,-,NaN,0.000,Electric
100,Mercedes-Benz A 200,Compact,-,NaN,1337.000,Benzine
114,Mercedes-Benz A 200,Compact,-,NaN,1337.000,Benzine
115,Mercedes-Benz A 200,Compact,-,NaN,2143.000,Benzine
129,Mercedes-Benz A 250,Compact,-,NaN,1332.000,Benzine
131,Mercedes-Benz A 200,Compact,-,NaN,2143.000,Benzine
137,Mercedes-Benz A 160,Compact,-,NaN,1595.000,Diesel
145,Mercedes-Benz A 200,Compact,-,NaN,2143.000,Diesel
169,Mercedes-Benz CL,Compact,-,NaN,1332.000,Benzine
170,Mercedes-Benz CL,Compact,-,NaN,1332.000,Benzine
171,Mercedes-Benz CL,Compact,-,NaN,1332.000,Benzine
200,Mercedes-Benz CL,Compact,-,NaN,1332.000,Benzine
205,Mercedes-Benz CL,Compact,-,NaN,1950.000,Diesel
209,Mercedes-Benz CL,Compact,-,NaN,1332.000,Benzine
216,Mercedes-Benz CL,Compact,-,NaN,1332.000,Benzine
229,Mercedes-Benz CL,Compact,-,NaN,1991.000,Benzine
230,Mercedes-Benz CL,Compact,-,NaN,2143.000,Diesel
233,Mercedes-Benz CL,Compact,-,NaN,1332.000,Benzine
237,Mercedes-Benz CL,Compact,-,NaN,1332.000,Benzine
240,Mercedes-Benz CL,Compact,-,NaN,1461.000,Diesel
243,Mercedes-Benz CL,Compact,-,NaN,1461.000,Diesel
248,Mercedes-Benz CL,Compact,-,NaN,1950.000,Diesel
253,Mercedes-Benz CL,Compact,-,NaN,1332.000,Benzine
254,Mercedes-Benz CL,Compact,-,NaN,1332.000,Benzine
260,Mercedes-Benz CL,Compact,-,NaN,1461.000,Diesel
262,Mercedes-Benz CL,Compact,-,NaN,1332.000,Benzine
263,Mercedes-Benz CL,Compact,-,NaN,1332.000,Benzine
269,Mercedes-Benz CL,Compact,-,NaN,1332.000,Benzine
270,Mercedes-Benz CL,Compact,-,NaN,1332.000,Benzine
271,Mercedes-Benz CL,Compact,-,NaN,1595.000,Benzine
272,Mercedes-Benz CL,Compact,-,NaN,1332.000,Benzine
273,Mercedes-Benz CL,Compact,-,NaN,1461.000,Diesel
284,Mercedes-Benz GLA 180,Compact,-,NaN,1595.000,Diesel
691,Mercedes-Benz 280,Convertible,-,NaN,2748.000,Benzine
740,Mercedes-Benz 500,Convertible,-,NaN,4973.000,Benzine
778,Mercedes-Benz 190,Convertible,-,NaN,1598.000,Benzine
804,Mercedes-Benz C 220,Coupe,-,NaN,2143.000,Diesel
1201,Mercedes-Benz GLA 180,Off-Road/Pick-up,-,NaN,1595.000,Diesel
1600,Mercedes-Benz C 180,Station wagon,-,NaN,1595.000,Diesel
2030,Mercedes-Benz CLA 180,Sedan,-,NaN,1600.000,Benzine
2060,Mercedes-Benz A 200,Sedan,-,NaN,1332.000,Diesel
2145,Mercedes-Benz A 200,Sedan,-,NaN,1332.000,Diesel
2733,Opel Adam,Compact,-,NaN,1398.000,Benzine
2745,Opel Corsa,Compact,-,NaN,0.000,Benzine
2758,Opel Adam,Compact,-,NaN,1398.000,Benzine
2777,Opel Adam,Compact,-,NaN,1398.000,Benzine
2778,Opel Ampera,Compact,-,NaN,1598.000,Benzine
2869,Opel Cascada,Convertible,-,NaN,1956.000,Diesel
3266,Opel Calibra,Coupe,-,NaN,1998.000,Benzine
3330,Opel Astra,Coupe,-,NaN,1800.000,Benzine
3397,Opel Kadett,Coupe,-,NaN,1100.000,Benzine
4290,Opel Astra,Station wagon,-,NaN,1598.000,Diesel
4923,Renault ZOE,Compact,-,NaN,1.000,Electric
4939,Renault ZOE,Compact,-,NaN,1.000,Electric
4952,Renault ZOE,Compact,-,NaN,1.000,Electric
4963,Renault ZOE,Compact,-,NaN,1.000,Electric
4970,Renault Clio,Compact,-,NaN,1598.000,Benzine
4972,Renault ZOE,Compact,-,NaN,1.000,Electric
4985,Renault ZOE,Compact,-,NaN,1.000,Electric
5026,Renault ZOE,Compact,-,NaN,1.000,Electric
5065,Renault Twingo,Compact,-,NaN,898.000,Benzine
5103,Renault Twingo,Compact,-,NaN,898.000,Benzine
5110,Renault Twingo,Compact,-,NaN,898.000,Benzine
5123,Renault Twingo,Compact,-,NaN,898.000,Benzine
5127,Renault Twingo,Compact,-,NaN,999.000,Benzine
5145,Renault Twingo,Compact,-,NaN,999.000,Benzine
5149,Renault Twingo,Compact,-,NaN,999.000,Electric
5212,Renault R 4,Convertible,-,NaN,839.000,Benzine
5384,Renault Megane,Convertible,-,NaN,1998.000,Diesel
5608,Renault Megane,Coupe,-,NaN,1461.000,Diesel
5612,Renault Arkana,Coupe,-,NaN,1333.000,Benzine
5615,Renault Arkana,Coupe,-,NaN,1333.000,Benzine
5624,Renault Arkana,Coupe,-,NaN,1333.000,Benzine
5628,Renault R 5,Coupe,-,NaN,1400.000,Benzine
5664,Renault Arkana,Coupe,-,NaN,1333.000,Benzine
5707,Renault Megane,Coupe,-,NaN,1998.000,Diesel
5739,Renault Laguna,Coupe,-,NaN,1995.000,Diesel
5786,Renault Twizy,Coupe,-,NaN,1598.000,Electric
5788,Renault Arkana,Coupe,-,NaN,1333.000,Benzine
5817,Renault Megane,Coupe,-,NaN,1995.000,Diesel
5839,Renault Arkana,Coupe,-,NaN,1333.000,Benzine
5862,Renault Arkana,Coupe,-,NaN,1333.000,Benzine
5886,Renault Arkana,Coupe,-,NaN,1333.000,Benzine
5902,Renault Laguna,Coupe,-,NaN,1995.000,Diesel
5905,Renault Arkana,Coupe,-,NaN,1333.000,Benzine
5963,Renault Arkana,Coupe,-,NaN,1333.000,Benzine
6166,Renault Twizy,Off-Road/Pick-up,-,NaN,1598.000,Electric
6174,Renault Captur,Off-Road/Pick-up,-,NaN,1332.000,Diesel
6181,Renault Captur,Off-Road/Pick-up,-,NaN,1332.000,Benzine
6185,Renault Captur,Off-Road/Pick-up,-,NaN,1461.000,Diesel
6191,Renault Kadjar,Off-Road/Pick-up,-,NaN,1461.000,Diesel
6205,Renault Twizy,Off-Road/Pick-up,-,NaN,1598.000,Electric
6229,Renault Alaskan,Off-Road/Pick-up,-,NaN,2298.000,Diesel
6239,Renault Arkana,Off-Road/Pick-up,-,NaN,1333.000,Benzine
6240,Renault Kadjar,Off-Road/Pick-up,-,NaN,1461.000,Diesel
6266,Renault Arkana,Off-Road/Pick-up,-,NaN,1598.000,Benzine
6271,Renault Captur,Off-Road/Pick-up,-,NaN,1332.000,Benzine
6272,Renault Koleos,Off-Road/Pick-up,-,NaN,1995.000,Diesel
6276,Renault Kadjar,Off-Road/Pick-up,-,NaN,1461.000,Diesel
6277,Renault Captur,Off-Road/Pick-up,-,NaN,1461.000,Diesel
6278,Renault Kadjar,Off-Road/Pick-up,-,NaN,1332.000,Diesel
6281,Renault Koleos,Off-Road/Pick-up,-,NaN,1995.000,Benzine
6291,Renault Kadjar,Off-Road/Pick-up,-,NaN,1197.000,Benzine
6300,Renault Captur,Off-Road/Pick-up,-,NaN,1461.000,Diesel
6311,Renault Kadjar,Off-Road/Pick-up,-,NaN,1461.000,Diesel
6317,Renault Arkana,Off-Road/Pick-up,-,NaN,1333.000,Benzine
6320,Renault Captur,Off-Road/Pick-up,-,NaN,1461.000,Diesel
6321,Renault Arkana,Off-Road/Pick-up,-,NaN,1598.000,Benzine
6322,Renault Koleos,Off-Road/Pick-up,-,NaN,1995.000,Benzine
6329,Renault Koleos,Off-Road/Pick-up,-,NaN,1995.000,Diesel
6331,Renault Captur,Off-Road/Pick-up,-,NaN,999.000,Liquid/Natural Gas
6332,Renault Captur,Off-Road/Pick-up,-,NaN,1598.000,Benzine
6337,Renault Scenic,Off-Road/Pick-up,-,NaN,1461.000,Diesel
6464,Renault Grand Scenic,Station wagon,-,NaN,1600.000,Benzine
6515,Renault Clio,Station wagon,-,NaN,1197.000,Benzine
6523,Renault Megane,Station wagon,-,NaN,1461.000,Diesel
6536,Renault Clio,Station wagon,-,NaN,1461.000,Diesel
6560,Renault Grand Scenic,Station wagon,-,NaN,1600.000,Diesel
6574,Renault Megane,Station wagon,-,NaN,1461.000,Diesel
6581,Renault Talisman,Station wagon,-,NaN,1461.000,Diesel
6597,Renault Talisman,Station wagon,-,NaN,1461.000,Diesel
6607,Renault Talisman,Station wagon,-,NaN,1598.000,Diesel
6615,Renault Talisman,Station wagon,-,NaN,1461.000,Diesel
6627,Renault Clio,Station wagon,-,NaN,1461.000,Diesel
6631,Renault Grand Scenic,Station wagon,-,NaN,1600.000,Diesel
6635,Renault Talisman,Station wagon,-,NaN,1598.000,Diesel
6646,Renault Talisman,Station wagon,-,NaN,1598.000,Diesel
6655,Renault Talisman,Station wagon,-,NaN,1997.000,Diesel
6660,Renault Megane,Station wagon,-,NaN,1461.000,Diesel
6673,Renault Megane,Station wagon,-,NaN,1461.000,Diesel
6679,Renault Megane,Station wagon,-,NaN,1330.000,Benzine
6683,Renault Megane,Station wagon,-,NaN,1332.000,Benzine
6686,Renault Talisman,Station wagon,-,NaN,1749.000,Diesel
6691,Renault Megane,Station wagon,-,NaN,1461.000,Diesel
6695,Renault Megane,Station wagon,-,NaN,1598.000,Benzine
6697,Renault Talisman,Station wagon,-,NaN,1749.000,Diesel
6701,Renault Talisman,Station wagon,-,NaN,1997.000,Diesel
6706,Renault Megane,Station wagon,-,NaN,1461.000,Diesel
6710,Renault Megane,Station wagon,-,NaN,1461.000,Diesel
6723,Renault Clio,Station wagon,-,NaN,1461.000,Diesel
6731,Renault Megane,Station wagon,-,NaN,1461.000,Diesel
6735,Renault Megane,Station wagon,-,NaN,1461.000,Diesel
6810,Renault ZOE,Sedan,-,NaN,0.000,Electric
6842,Renault Clio,Sedan,-,NaN,900.000,Benzine
6951,Renault R 9,Sedan,-,NaN,1700.000,Electric
6958,Renault R 9,Sedan,-,NaN,1700.000,Electric
6963,Renault Talisman,Sedan,-,NaN,1997.000,Diesel
6975,Renault Talisman,Sedan,-,NaN,1598.000,Diesel
6977,Renault Talisman,Sedan,-,NaN,1598.000,Diesel
6999,Renault Twingo,Sedan,-,NaN,898.000,Benzine
7011,Renault Clio,Sedan,-,NaN,999.000,Liquid/Natural Gas
7028,Renault Talisman,Sedan,-,NaN,1598.000,Diesel
7047,Renault Talisman,Sedan,-,NaN,1997.000,Diesel
7054,Renault Megane,Sedan,-,NaN,1461.000,Benzine
7055,Renault Megane,Sedan,-,NaN,1461.000,Benzine
7060,Renault ZOE,Sedan,-,NaN,0.000,Electric
7065,Renault Talisman,Sedan,-,NaN,1461.000,Diesel
7066,Renault Talisman,Sedan,-,NaN,1598.000,Diesel
7067,Renault Megane,Sedan,-,NaN,1461.000,Diesel
7069,Renault Talisman,Sedan,-,NaN,1997.000,Diesel
7077,Renault Talisman,Sedan,-,NaN,1997.000,Diesel
7084,Renault Talisman,Sedan,-,NaN,1598.000,Diesel
7090,Renault Talisman,Sedan,-,NaN,1598.000,Diesel
7092,Renault Talisman,Sedan,-,NaN,1997.000,Diesel
7093,Renault Talisman,Sedan,-,NaN,1997.000,Diesel
7102,Renault ZOE,Sedan,-,NaN,0.000,Electric
7103,Renault R 11,Sedan,-,NaN,1598.000,Electric
7108,Renault Talisman,Sedan,-,NaN,1598.000,Diesel
7113,Renault ZOE,Sedan,-,NaN,0.000,Electric
7114,Renault ZOE,Sedan,-,NaN,0.000,Electric
7116,Renault ZOE,Sedan,-,NaN,0.000,Electric
7120,Renault Talisman,Sedan,-,NaN,1997.000,Diesel
7124,Renault ZOE,Sedan,-,NaN,0.000,Electric
7127,Renault R 9,Sedan,-,NaN,1700.000,Electric
7129,Renault Talisman,Sedan,-,NaN,1997.000,Diesel
7132,Renault ZOE,Sedan,-,NaN,0.000,Electric
7133,Renault Clio,Sedan,-,NaN,898.000,Liquid/Natural Gas
7232,Peugeot e-208,Compact,-,NaN,1598.000,Electric
7292,Peugeot 108,Compact,-,NaN,998.000,Benzine
7343,Peugeot 108,Compact,-,NaN,998.000,Benzine
7386,Peugeot 1007,Compact,-,NaN,1360.000,Benzine
7428,Peugeot 108,Compact,-,NaN,998.000,Benzine
7433,Peugeot 108,Compact,-,NaN,998.000,Benzine
7470,Peugeot 108,Compact,-,NaN,1199.000,Benzine
7475,Peugeot 108,Compact,-,NaN,998.000,Benzine
7492,Peugeot 107,Compact,-,NaN,998.000,Benzine
7521,Peugeot 108,Compact,-,NaN,1199.000,Benzine
7598,Peugeot 504,Convertible,-,NaN,1971.000,Benzine
7709,Peugeot Expert,Convertible,-,NaN,1499.000,Diesel
7790,Peugeot 306,Convertible,-,NaN,1998.000,Benzine
7871,Peugeot 207,Convertible,-,NaN,1598.000,Benzine
8069,Peugeot 207,Coupe,-,NaN,1598.000,Diesel
8207,Peugeot 407,Coupe,-,NaN,2720.000,Diesel
8229,Peugeot 407,Coupe,-,NaN,2720.000,Diesel
8594,Peugeot 3008,Off-Road/Pick-up,-,NaN,1499.000,Diesel
8607,Peugeot 5008,Off-Road/Pick-up,-,NaN,1997.000,Diesel
8632,Peugeot 3008,Off-Road/Pick-up,-,NaN,1997.000,Diesel
8634,Peugeot 2008,Off-Road/Pick-up,-,NaN,1199.000,Benzine
8641,Peugeot 3008,Off-Road/Pick-up,-,NaN,1199.000,Benzine
8670,Peugeot 2008,Off-Road/Pick-up,-,NaN,1199.000,Electric
8818,Peugeot 308,Station wagon,-,NaN,1199.000,Benzine
8945,Peugeot 308,Station wagon,-,NaN,1199.000,Benzine
8959,Peugeot 508,Station wagon,-,NaN,1598.000,Benzine
8961,Peugeot 508,Station wagon,-,NaN,1499.000,Diesel
8973,Peugeot 508,Station wagon,-,NaN,1997.000,Diesel
8990,Peugeot 508,Station wagon,-,NaN,1997.000,Diesel
9004,Peugeot 308,Station wagon,-,NaN,1598.000,Diesel
9008,Peugeot 308,Station wagon,-,NaN,1499.000,Diesel
9009,Peugeot 508,Station wagon,-,NaN,1499.000,Diesel
9014,Peugeot 308,Station wagon,-,NaN,1499.000,Diesel
9020,Peugeot 508,Station wagon,-,NaN,1997.000,Diesel
9022,Peugeot 508,Station wagon,-,NaN,1598.000,Diesel
9025,Peugeot 308,Station wagon,-,NaN,1499.000,Diesel
9027,Peugeot 508,Station wagon,-,NaN,1598.000,Diesel
9033,Peugeot 308,Station wagon,-,NaN,1560.000,Diesel
9034,Peugeot 508,Station wagon,-,NaN,1598.000,Diesel
9035,Peugeot 508,Station wagon,-,NaN,1598.000,Benzine
9037,Peugeot 308,Station wagon,-,NaN,1598.000,Diesel
9040,Peugeot 308,Station wagon,-,NaN,1199.000,Benzine
9041,Peugeot 308,Station wagon,-,NaN,1598.000,Diesel
9042,Peugeot 308,Station wagon,-,NaN,1598.000,Diesel
9044,Peugeot 308,Station wagon,-,NaN,1199.000,Benzine
9045,Peugeot 308,Station wagon,-,NaN,1499.000,Diesel
9047,Peugeot 508,Station wagon,-,NaN,1598.000,Diesel
9048,Peugeot 308,Station wagon,-,NaN,1499.000,Diesel
9051,Peugeot 308,Station wagon,-,NaN,1499.000,Diesel
9057,Peugeot 308,Station wagon,-,NaN,1598.000,Diesel
9058,Peugeot 308,Station wagon,-,NaN,1499.000,Diesel
9060,Peugeot 308,Station wagon,-,NaN,1199.000,Benzine
9061,Peugeot 308,Station wagon,-,NaN,1598.000,Diesel
9064,Peugeot 308,Station wagon,-,NaN,1499.000,Diesel
9065,Peugeot 208,Station wagon,-,NaN,1199.000,Benzine
9066,Peugeot 308,Station wagon,-,NaN,1199.000,Benzine
9067,Peugeot 308,Station wagon,-,NaN,1199.000,Benzine
9263,Peugeot 508,Sedan,-,NaN,1598.000,Diesel
9272,Peugeot 208,Sedan,-,NaN,1199.000,Benzine
9299,Peugeot 508,Sedan,-,NaN,1997.000,Diesel
9315,Peugeot 208,Sedan,-,NaN,1199.000,Benzine
9320,Peugeot 508,Sedan,-,NaN,1997.000,Diesel
9324,Peugeot 308,Sedan,-,NaN,1598.000,Diesel
9326,Peugeot 208,Sedan,-,NaN,999.000,Benzine
9330,Peugeot 508,Sedan,-,NaN,1598.000,Diesel
9334,Peugeot 508,Sedan,-,NaN,1499.000,Diesel
9351,Peugeot 301,Sedan,-,NaN,1598.000,Benzine
9366,Peugeot 208,Sedan,-,NaN,1199.000,Electric
9372,Peugeot 508,Sedan,-,NaN,1997.000,Diesel
9374,Peugeot 508,Sedan,-,NaN,1598.000,Diesel
9377,Peugeot 508,Sedan,-,NaN,1598.000,Diesel
9380,Peugeot 208,Sedan,-,NaN,1199.000,Benzine
9386,Peugeot 308,Sedan,-,NaN,1997.000,Diesel
9393,Peugeot 508,Sedan,-,NaN,1997.000,Diesel
9410,Peugeot 308,Sedan,-,NaN,1199.000,Benzine
9421,Peugeot 308,Sedan,-,NaN,1199.000,Benzine
9426,Peugeot 208,Sedan,-,NaN,1199.000,Electric
9428,Peugeot 208,Sedan,-,NaN,1199.000,Electric
9430,Peugeot 308,Sedan,-,NaN,1499.000,Diesel
9431,Peugeot 508,Sedan,-,NaN,1499.000,Diesel
9448,Peugeot 208,Sedan,-,NaN,1199.000,Electric
9450,Peugeot 508,Sedan,-,NaN,1598.000,Benzine
9454,Peugeot 508,Sedan,-,NaN,1598.000,Benzine
9455,Peugeot 208,Sedan,-,NaN,1199.000,Electric
9458,Peugeot 308,Sedan,-,NaN,1598.000,Diesel
9466,Peugeot 308,Sedan,-,NaN,1560.000,Diesel
9473,Peugeot 208,Sedan,-,NaN,1199.000,Electric
9475,Peugeot 208,Sedan,-,NaN,1199.000,Benzine
9481,Peugeot 208,Sedan,-,NaN,1199.000,Electric
9482,Peugeot 508,Sedan,-,NaN,1499.000,Diesel
9487,Peugeot 208,Sedan,-,NaN,1199.000,Electric
9488,Peugeot 208,Sedan,-,NaN,1199.000,Benzine
9493,Peugeot 308,Sedan,-,NaN,1560.000,Diesel
9696,Fiat 500,Compact,-,NaN,1242.000,Benzine
9699,Fiat 500e,Compact,-,NaN,0.000,Electric
9820,Fiat 500,Compact,-,NaN,1242.000,Benzine
9824,Fiat Panda,Compact,-,NaN,1242.000,Benzine
9841,Fiat 500,Compact,-,NaN,1248.000,Diesel
10000,Fiat,Convertible,-,NaN,0.000,Benzine
10296,Fiat 130,Coupe,-,NaN,3200.000,Benzine
10408,Fiat 500,Coupe,-,NaN,875.000,Benzine
10433,Fiat Coupe,Coupe,-,NaN,1998.000,Benzine
10726,Fiat 500X,Off-Road/Pick-up,-,NaN,1598.000,Diesel
10788,Fiat 500X,Off-Road/Pick-up,-,NaN,999.000,Benzine
10791,Fiat 500X,Off-Road/Pick-up,-,NaN,1332.000,Benzine
10843,Fiat 500X,Off-Road/Pick-up,-,NaN,1332.000,Benzine
10852,Fiat 500X,Off-Road/Pick-up,-,NaN,999.000,Benzine
11115,Fiat Tipo,Station wagon,-,NaN,1598.000,Diesel
11156,Fiat Tipo,Station wagon,-,NaN,999.000,Benzine
11211,Fiat Tipo,Station wagon,-,NaN,1469.000,Diesel
11543,Fiat New Panda,Sedan,-,NaN,875.000,Benzine
11547,Fiat New Panda,Sedan,-,NaN,999.000,Benzine
11567,Fiat Tipo,Sedan,-,NaN,1368.000,Benzine
11591,Fiat Tipo,Sedan,-,NaN,1368.000,Benzine
11635,Fiat Tipo,Sedan,-,NaN,1368.000,Benzine
11637,Fiat Tipo,Sedan,-,NaN,1368.000,Benzine
11675,Fiat Tipo,Sedan,-,NaN,1598.000,Diesel
11734,Fiat Tipo,Sedan,-,NaN,1368.000,Benzine
11764,Fiat Tipo,Sedan,-,NaN,1598.000,Diesel
12280,SEAT Ibiza,Coupe,-,NaN,1198.000,Benzine
13017,SEAT Leon,Station wagon,-,NaN,1984.000,Benzine
13113,SEAT Leon,Station wagon,-,NaN,1984.000,Benzine
13114,SEAT Leon,Station wagon,-,NaN,1798.000,Benzine
13390,SEAT Leon,Sedan,-,NaN,1498.000,Benzine
13447,SEAT Leon,Sedan,-,NaN,1498.000,Benzine
13518,SEAT Ibiza,Sedan,-,NaN,999.000,Benzine
13549,SEAT Ibiza,Sedan,-,NaN,999.000,Benzine
13558,SEAT Leon,Sedan,-,NaN,1498.000,Benzine
13677,Skoda Citigo,Compact,-,NaN,999.000,Benzine
13819,Skoda Octavia,Compact,-,NaN,1968.000,Diesel
13958,Skoda 105,Convertible,-,NaN,1598.000,Diesel
15078,Skoda Scala,Sedan,-,NaN,1498.000,Benzine
15083,Skoda Superb,Sedan,-,NaN,1395.000,Benzine
15126,Skoda Octavia,Sedan,-,NaN,1395.000,Diesel
15134,Skoda Octavia,Sedan,-,NaN,1598.000,Diesel
15651,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15685,Dacia Duster,Off-Road/Pick-up,-,NaN,1598.000,Liquid/Natural Gas
15703,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15716,Dacia Duster,Off-Road/Pick-up,-,NaN,1198.000,Benzine
15721,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15725,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15728,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15730,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15738,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15746,Dacia Duster,Off-Road/Pick-up,-,NaN,999.000,Liquid/Natural Gas
15747,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15756,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15761,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15771,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15774,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15775,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15779,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15781,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15784,Dacia Duster,Off-Road/Pick-up,-,NaN,999.000,Liquid/Natural Gas
15785,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15787,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15788,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15790,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15795,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15809,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15810,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15812,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15813,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15814,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15815,Dacia Duster,Off-Road/Pick-up,-,NaN,1333.000,Benzine
15818,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15819,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15823,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15824,Dacia Duster,Off-Road/Pick-up,-,NaN,1333.000,Benzine
15826,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15827,Dacia Duster,Off-Road/Pick-up,-,NaN,1461.000,Diesel
15839,Dacia Duster,Off-Road/Pick-up,-,NaN,1333.000,Benzine
15840,Dacia Duster,Off-Road/Pick-up,-,NaN,1333.000,Benzine
15841,Dacia Duster,Off-Road/Pick-up,-,NaN,1333.000,Benzine
15939,Dacia Logan,Station wagon,-,NaN,1461.000,Diesel
16172,Dacia Logan,Station wagon,-,NaN,898.000,Liquid/Natural Gas
16234,Dacia Break,Station wagon,-,NaN,1598.000,Benzine
16379,Dacia Sandero,Sedan,-,NaN,1461.000,Diesel
16387,Dacia Sandero,Sedan,-,NaN,1461.000,Diesel
16388,Dacia Sandero,Sedan,-,NaN,1598.000,Benzine
16393,Dacia Sandero,Sedan,-,NaN,898.000,Benzine
16396,Dacia Sandero,Sedan,-,NaN,998.000,Benzine
16399,Dacia Sandero,Sedan,-,NaN,898.000,Benzine
16407,Dacia Sandero,Sedan,-,NaN,898.000,Benzine
16415,Dacia Sandero,Sedan,-,NaN,1461.000,Diesel
16418,Dacia Sandero,Sedan,-,NaN,898.000,Benzine
16425,Dacia Sandero,Sedan,-,NaN,898.000,Benzine
16427,Dacia Sandero,Sedan,-,NaN,898.000,Benzine
16435,Dacia Sandero,Sedan,-,NaN,1461.000,Diesel
16436,Dacia Sandero,Sedan,-,NaN,998.000,Benzine
16438,Dacia Sandero,Sedan,-,NaN,898.000,Benzine
16441,Dacia Logan,Sedan,-,NaN,898.000,Benzine
16445,Dacia Sandero,Sedan,-,NaN,898.000,Benzine
16449,Dacia Sandero,Sedan,-,NaN,898.000,Benzine
16456,Dacia Sandero,Sedan,-,NaN,898.000,Benzine
16457,Dacia Sandero,Sedan,-,NaN,998.000,Benzine
16464,Dacia Sandero,Sedan,-,NaN,999.000,Benzine
16465,Dacia Sandero,Sedan,-,NaN,999.000,Benzine
16473,Dacia Sandero,Sedan,-,NaN,999.000,Liquid/Natural Gas
16685,Toyota Yaris,Compact,-,NaN,1490.000,Benzine
16856,Toyota Prius,Compact,-,NaN,1798.000,Benzine
16865,Toyota Yaris,Compact,-,NaN,998.000,Benzine
16868,Toyota Prius,Compact,-,NaN,1798.000,Benzine
16877,Toyota Corolla,Compact,-,NaN,1987.000,Benzine
16878,Toyota Yaris,Compact,-,NaN,1497.000,Benzine

**The ``kW`` of cars changes by their ``make_models`` & ``body_type`` most of the time. So it is more beneficial to decide to fill missing values with mode value of related group.**

In [ ]:
df["power_kW"].replace(["-"], np.nan, inplace=True)

In [ ]:
fill(df, "make_model", "body_type", "power_kW", "mode")

COLUMN NAME    :  power_kW
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  351
--------------------------------
1.000         5
3.000         1
4.000         5
6.000         1
7.000         2
8.000         3
9.000         2
10.000        1
12.000        2
13.000       10
14.000        2
15.000        1
16.000        1
17.000        5
18.000        7
19.000        2
20.000        1
21.000        2
22.000        1
23.000        2
24.000        1
25.000        4
26.000        1
27.000        1
29.000        3
30.000        1
31.000        2
32.000        8
33.000       42
34.000        2
35.000        9
36.000        3
37.000        6
38.000        3
39.000        1
40.000       22
41.000        1
42.000        1
43.000       54
44.000      135
45.000        4
46.000        3
47.000       13
48.000       33
49.000       84
50.000      100
51.000      707
52.000      112
53.000      184
54.000      120
55.000      523
56.000       15
57.000       23
58.000        3
59.000      149
60.000      133
61.000       24
62.000       85
63.000      200
64.000       66
65.000       99
66.000     1152
67.000      213
68.000      132
69.000       11
70.000      696
71.000       39
72.000       50
73.000      139
74.000      915
75.000      130
76.000       24
77.000      238
78.000       32
79.000       48
80.000      356
81.000     1186
82.000      216
83.000       25
84.000      240
85.000     1052
86.000       39
87.000      127
88.000     1202
89.000        3
90.000      324
91.000       36
92.000      477
93.000       44
94.000       10
95.000       24
96.000     1426
97.000      187
98.000       50
99.000      111
100.000     700
101.000      40
102.000      38
103.000    1055
104.000     171
105.000      99
106.000       4
107.000     124
108.000      81
109.000      11
110.000    2018
111.000       6
112.000      98
113.000      56
114.000      89
115.000     248
116.000      79
117.000      92
118.000     258
119.000      20
120.000     422
121.000     134
122.000      16
123.000      15
124.000       8
125.000     424
126.000       5
127.000      10
128.000      26
129.000      31
130.000     252
131.000       8
132.000     344
133.000     100
134.000      34
135.000     315
136.000      59
137.000      29
138.000      32
139.000      11
140.000     790
141.000      21
142.000      70
143.000     143
144.000       1
145.000     205
146.000       6
147.000     460
148.000       6
149.000       9
150.000     234
151.000      19
152.000      26
153.000      14
154.000      49
155.000      79
156.000      13
157.000      27
158.000      19
160.000      65
161.000       2
162.000     116
163.000      21
164.000       1
165.000     130
166.000      13
167.000       5
168.000      13
169.000     103
170.000      27
172.000      11
173.000     249
174.000       6
175.000      25
176.000      49
177.000      36
178.000      15
179.000       1
180.000     130
182.000      11
183.000       1
184.000     138
185.000      35
186.000      25
187.000      14
188.000       9
189.000       2
190.000     119
191.000      30
192.000      42
193.000       5
194.000      53
195.000      61
196.000       4
198.000       9
199.000      20
200.000      41
201.000      13
202.000     129
203.000       6
205.000      20
206.000     224
207.000       8
208.000      13
209.000       2
210.000      34
212.000      10
213.000      81
214.000       4
215.000      37
216.000       3
217.000       1
218.000       3
220.000      19
221.000     234
222.000       2
223.000      60
224.000      43
225.000     104
227.000      15
228.000     105
229.000       3
230.000       5
231.000      28
232.000      24
233.000      43
234.000       1
235.000      20
236.000       1
237.000       1
238.000       1
239.000      10
240.000       7
241.000     117
242.000       1
243.000      79
244.000       2
245.000      76
246.000       4
248.000       5
250.000      81
251.000      37
253.000      22
254.000       1
255.000       1
257.000      18
258.000      11
265.000      36
266.000       3
267.000       2
270.000      86
271.000       6
274.000       2
279.000       4
280.000      32
284.000       1
285.000      24
286.000       5
287.000      64
288.000     155
290.000       2
292.000       2
293.000       3
294.000      12
295.000       6
296.000       1
298.000      17
299.000       7
300.000      50
303.000       1
307.000       6
308.000      14
309.000       4
310.000      99
311.000       2
312.000       2
313.000       4
316.000       2
320.000      55
324.000       8
325.000       1
327.000       1
328.000       1
330.000      39
331.000     170
332.000       1
335.000      19
336.000      47
338.000      45
339.000       4
340.000       4
341.000       1
342.000       1
343.000       9
345.000       7
346.000       2
350.000      51
353.000       6
354.000       2
357.000       5
358.000       2
360.000       5
363.000       2
365.000       1
368.000       6
370.000       7
372.000       1
373.000       1
375.000      51
378.000       1
380.000       7
384.000       1
385.000       8
386.000      11
387.000       3
390.000      10
392.000       6
400.000       4
403.000       1
404.000      14
405.000      11
409.000       1
410.000      24
412.000       2
419.000      34
420.000       4
430.000      43
441.000       4
450.000      30
463.000       2
470.000       7
471.000       1
478.000       1
484.000       3
485.000       1
487.000       4
493.000       1
496.000       1
499.000       1
527.000       1
530.000       1
537.000       1
551.000       1
552.000       2
559.000       9
567.000       3
570.000       1
588.000       3
600.000       1
662.000       2
664.000       1
665.000       1
746.000       1
810.000       1
883.000       1
924.000       1
Name: power_kW, dtype: int64

## power_hp

In [ ]:
first_looking("power_hp")

COLUMN NAME    :  power_hp
--------------------------------
per_of_nulls   :  % 2.0
num_of_nulls   :  572
num_of_uniques :  347
--------------------------------
150.000    1992
131.000    1356
120.000    1182
110.000    1166
90.000     1110
140.000    1033
116.000    1002
101.000     892
190.000     787
69.000      701
95.000      685
136.000     681
NaN         572
75.000      515
125.000     477
200.000     458
170.000     422
163.000     418
109.000     349
179.000     339
122.000     318
184.000     296
235.000     249
160.000     247
156.000     246
177.000     241
114.000     240
105.000     236
300.000     234
204.000     232
280.000     224
91.000      213
111.000     204
86.000      200
197.000     199
132.000     185
72.000      176
141.000     163
392.000     155
80.000      149
194.000     143
99.000      139
250.000     138
165.000     134
60.000      133
82.000      133
224.000     130
245.000     130
102.000     128
92.000      127
275.000     126
145.000     124
73.000      120
258.000     119
450.000     118
328.000     117
220.000     115
71.000      112
135.000     111
310.000     105
306.000     104
230.000     103
118.000     102
181.000     100
143.000      99
421.000      99
68.000       99
152.000      98
88.000       97
159.000      92
155.000      89
367.000      86
67.000       84
84.000       83
290.000      81
340.000      81
147.000      80
211.000      79
330.000      79
333.000      76
193.000      70
390.000      64
218.000      63
87.000       63
158.000      63
265.000      61
303.000      60
185.000      59
154.000      56
435.000      55
264.000      53
510.000      51
476.000      51
408.000      50
133.000      50
98.000       50
239.000      49
209.000      49
107.000      48
457.000      47
460.000      45
58.000       45
126.000      44
317.000      43
305.000      43
585.000      43
45.000       42
261.000      42
272.000      41
137.000      40
97.000       39
449.000      39
117.000      39
139.000      38
341.000      37
292.000      36
241.000      36
124.000      36
360.000      36
252.000      35
182.000      34
286.000      34
570.000      34
65.000       33
381.000      32
106.000      32
188.000      32
175.000      31
612.000      30
260.000      30
186.000      29
314.000      28
231.000      27
213.000      27
207.000      26
174.000      26
238.000      25
253.000      25
113.000      25
387.000      24
557.000      24
129.000      24
315.000      24
103.000      24
83.000       24
77.000       23
54.000       22
344.000      22
222.000      21
192.000      21
271.000      20
279.000      20
162.000      20
320.000      20
299.000      19
205.000      19
215.000      19
455.000      19
349.000      18
405.000      17
166.000      16
309.000      15
76.000       15
254.000      14
167.000      14
549.000      14
419.000      14
208.000      14
228.000      13
212.000      13
226.000      13
273.000      13
283.000      13
64.000       12
242.000      12
400.000      12
189.000      11
351.000      11
148.000      11
234.000      11
94.000       11
525.000      11
530.000      10
128.000      10
247.000      10
288.000      10
18.000       10
173.000      10
325.000      10
760.000       9
48.000        9
269.000       9
466.000       9
551.000       9
256.000       9
1.000         9
203.000       9
441.000       8
523.000       8
178.000       8
169.000       8
281.000       8
639.000       7
24.000        7
517.000       7
469.000       7
503.000       7
407.000       7
151.000       6
50.000        6
368.000       6
417.000       6
480.000       6
533.000       6
44.000        6
237.000       6
199.000       6
201.000       6
500.000       6
276.000       6
326.000       6
401.000       6
489.000       5
171.000       5
227.000       5
485.000       5
389.000       5
313.000       5
23.000        5
337.000       5
262.000       5
291.000       4
461.000       4
379.000       4
334.000       4
600.000       4
144.000       4
462.000       4
420.000       4
662.000       4
61.000        4
571.000       4
266.000       4
544.000       4
426.000       4
39.000        3
79.000        3
658.000       3
398.000       3
294.000       3
63.000        3
11.000        3
49.000        3
362.000       3
121.000       3
52.000        3
526.000       3
771.000       3
799.000       3
34.000        3
296.000       3
311.000       3
423.000       2
424.000       2
397.000       2
430.000       2
494.000       2
373.000       2
751.000       2
394.000       2
363.000       2
470.000       2
487.000       2
481.000       2
630.000       2
560.000       2
332.000       2
19.000        2
26.000        2
257.000       2
302.000       2
12.000        2
5.000         2
31.000        2
284.000       2
42.000        2
219.000       2
900.000       2
10.000        2
46.000        2
16.000        2
324.000       1
464.000       1
775.000       1
22.000        1
37.000        1
30.000        1
57.000        1
14.000        1
41.000        1
721.000       1
507.000       1
20.000        1
446.000       1
749.000       1
496.000       1
659.000       1
318.000       1
442.000       1
4.000         1
347.000       1
8.000         1
53.000        1
640.000       1
514.000       1
35.000        1
451.000       1
196.000       1
249.000       1
243.000       1
386.000       1
321.000       1
223.000       1
556.000       1
402.000       1
904.000       1
650.000       1
445.000       1
816.000       1
903.000       1
674.000       1
329.000       1
345.000       1
678.000       1
522.000       1
56.000        1
730.000       1
29.000        1
295.000       1
322.000       1
27.000        1
717.000       1
548.000       1
465.000       1
412.000       1
670.000       1
506.000       1
33.000        1
Name: power_hp, dtype: int64

In [ ]:
df["power_hp"].fillna("-", inplace=True)

In [ ]:
df.groupby(["make_model", "body_type", "power_hp"]).price.describe()

                                        count      mean      std       min  \
make_model   body_type        power_hp
Dacia        Compact          45.0      3.000 21431.000 1661.744 19515.000
             Sedan            54.0      1.000  9999.000      NaN  9999.000
             Station wagon    110.0     1.000 21799.000      NaN 21799.000
Dacia Break  Station wagon    -         1.000 20500.000      NaN 20500.000
Dacia Dokker Compact          90.0      1.000 11930.000      NaN 11930.000
...                                       ...       ...      ...       ...
Volvo XC90   Off-Road/Pick-up 400.0     6.000 50793.333 6277.645 42790.000
                              408.0     2.000 44200.000    0.000 44200.000
             Sedan            235.0     2.000 48100.000  565.685 47700.000
                              303.0     1.000 84900.000      NaN 84900.000
             Station wagon    224.0     4.000 32750.000 3752.777 29500.000

                                             25%       50%       75%       max
make_model   body_type        power_hp
Dacia        Compact          45.0     20907.000 22299.000 22389.000 22479.000
             Sedan            54.0      9999.000  9999.000  9999.000  9999.000
             Station wagon    110.0    21799.000 21799.000 21799.000 21799.000
Dacia Break  Station wagon    -        20500.000 20500.000 20500.000 20500.000
Dacia Dokker Compact          90.0     11930.000 11930.000 11930.000 11930.000
...                                          ...       ...       ...       ...
Volvo XC90   Off-Road/Pick-up 400.0    45515.000 53690.000 55347.500 55900.000
                              408.0    44200.000 44200.000 44200.000 44200.000
             Sedan            235.0    47900.000 48100.000 48300.000 48500.000
                              303.0    84900.000 84900.000 84900.000 84900.000
             Station wagon    224.0    29500.000 32750.000 36000.000 36000.000

[5032 rows x 8 columns]

**The ``hp`` of cars changes by their ``make_models`` & ``body_type`` most of the time. So it is more beneficial to decide to fill missing values with mode value of related group.**

In [ ]:
df["power_hp"].replace(["-"], np.nan, inplace=True)

In [ ]:
fill(df, "make_model", "body_type", "power_hp", "mode")

COLUMN NAME    :  power_hp
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  347
--------------------------------
1.000         9
4.000         1
5.000         5
8.000         1
10.000        2
11.000        3
12.000        2
14.000        1
16.000        2
18.000       10
19.000        2
20.000        1
22.000        1
23.000        5
24.000        7
26.000        2
27.000        1
29.000        2
30.000        1
31.000        2
33.000        1
34.000        4
35.000        1
37.000        1
39.000        3
41.000        1
42.000        2
44.000        8
45.000       42
46.000        2
48.000        9
49.000        3
50.000        6
52.000        3
53.000        1
54.000       22
56.000        1
57.000        1
58.000       54
60.000      135
61.000        4
63.000        3
64.000       13
65.000       33
67.000       84
68.000      100
69.000      707
71.000      112
72.000      184
73.000      120
75.000      523
76.000       15
77.000       23
79.000        3
80.000      149
82.000      133
83.000       24
84.000       85
86.000      200
87.000       66
88.000       99
90.000     1152
91.000      213
92.000      132
94.000       11
95.000      696
97.000       39
98.000       50
99.000      139
101.000     915
102.000     130
103.000      24
105.000     238
106.000      32
107.000      48
109.000     356
110.000    1186
111.000     216
113.000      25
114.000     240
116.000    1052
117.000      39
118.000     127
120.000    1202
121.000       3
122.000     324
124.000      36
125.000     477
126.000      44
128.000      10
129.000      24
131.000    1426
132.000     187
133.000      50
135.000     111
136.000     700
137.000      40
139.000      38
140.000    1055
141.000     171
143.000      99
144.000       4
145.000     124
147.000      81
148.000      11
150.000    2018
151.000       6
152.000      98
154.000      56
155.000      89
156.000     248
158.000      79
159.000      92
160.000     258
162.000      20
163.000     422
165.000     134
166.000      16
167.000      15
169.000       8
170.000     424
171.000       5
173.000      10
174.000      26
175.000      31
177.000     252
178.000       8
179.000     344
181.000     100
182.000      34
184.000     315
185.000      59
186.000      29
188.000      32
189.000      11
190.000     790
192.000      21
193.000      70
194.000     143
196.000       1
197.000     205
199.000       6
200.000     460
201.000       6
203.000       9
204.000     234
205.000      19
207.000      26
208.000      14
209.000      49
211.000      79
212.000      13
213.000      27
215.000      19
218.000      65
219.000       2
220.000     116
222.000      21
223.000       1
224.000     130
226.000      13
227.000       5
228.000      13
230.000     103
231.000      27
234.000      11
235.000     249
237.000       6
238.000      25
239.000      49
241.000      36
242.000      15
243.000       1
245.000     130
247.000      11
249.000       1
250.000     138
252.000      35
253.000      25
254.000      14
256.000       9
257.000       2
258.000     119
260.000      30
261.000      42
262.000       5
264.000      53
265.000      61
266.000       4
269.000       9
271.000      20
272.000      41
273.000      13
275.000     129
276.000       6
279.000      20
280.000     224
281.000       8
283.000      13
284.000       2
286.000      34
288.000      10
290.000      81
291.000       4
292.000      37
294.000       3
295.000       1
296.000       3
299.000      19
300.000     234
302.000       2
303.000      60
305.000      43
306.000     104
309.000      15
310.000     105
311.000       3
313.000       5
314.000      28
315.000      24
317.000      43
318.000       1
320.000      20
321.000       1
322.000       1
324.000       1
325.000      10
326.000       7
328.000     117
329.000       1
330.000      79
332.000       2
333.000      76
334.000       4
337.000       5
340.000      81
341.000      37
344.000      22
345.000       1
347.000       1
349.000      18
351.000      11
360.000      36
362.000       3
363.000       2
367.000      86
368.000       6
373.000       2
379.000       4
381.000      32
386.000       1
387.000      24
389.000       5
390.000      64
392.000     155
394.000       2
397.000       2
398.000       3
400.000      12
401.000       6
402.000       1
405.000      17
407.000       7
408.000      50
412.000       1
417.000       6
419.000      14
420.000       4
421.000      99
423.000       2
424.000       2
426.000       4
430.000       2
435.000      55
441.000       8
442.000       1
445.000       1
446.000       1
449.000      39
450.000     170
451.000       1
455.000      19
457.000      47
460.000      45
461.000       4
462.000       4
464.000       1
465.000       1
466.000       9
469.000       7
470.000       2
476.000      51
480.000       6
481.000       2
485.000       5
487.000       2
489.000       5
494.000       2
496.000       1
500.000       6
503.000       7
506.000       1
507.000       1
510.000      51
514.000       1
517.000       7
522.000       1
523.000       8
525.000      11
526.000       3
530.000      10
533.000       6
544.000       4
548.000       1
549.000      14
551.000      11
556.000       1
557.000      24
560.000       2
570.000      34
571.000       4
585.000      43
600.000       4
612.000      30
630.000       2
639.000       7
640.000       1
650.000       1
658.000       3
659.000       1
662.000       4
670.000       1
674.000       1
678.000       1
717.000       1
721.000       1
730.000       1
749.000       1
751.000       2
760.000       9
771.000       3
775.000       1
799.000       3
816.000       1
900.000       2
903.000       1
904.000       1
Name: power_hp, dtype: int64

**The ``"hp"`` feature is dropped from the analysis and ``"kW"`` will be used for further steps since ``"kW"`` is used as the indicator of comsumption for electric vehicles.**

In [ ]:
df.shape

(28630, 32)

In [ ]:
df.drop("power_hp", axis=1, inplace=True)

In [ ]:
df.shape

(28630, 31)

## cons_avg

**Problem!!!**

We are all used to the fact that the fuel consumption of a petrol or diesel car is expressed in litres per hundred kilometres (l/100 km)...An electric car doesn’t use fuel but gets its energy from a battery. The maximum amount of energy the battery can store (capacity) is expressed in kWh (kilowatt-hour). Instead of the amount of fuel needed to cover hundred kilometres, the energy consumption of an electric car is (usually) expressed in the number of kilowatt-hours needed to drive a hundred kilometres (kWh/100 km).

**How do we deal with this issue?**

**🧐 [What is the equivalent fuel consumption of an electric car?](https://news.mgmotor.eu/what-is-the-equivalent-fuel-consumption-of-an-electric-car/)**

**🧐 [Energy consumption of full electric vehicles](https://ev-database.org/cheatsheet/energy-consumption-electric-car)**

**🧐 [HOW DO YOU CALCULATE KWH VS. KW?](https://www.directenergyregulatedservices.com/blog/kw-vs-kwh-whats-difference#:~:text=Divide%20the%20wattage%20by%201%2C000,days%20%3D%2090%20kWh%20per%20month)**

In [ ]:
first_looking("cons_avg")

COLUMN NAME    :  cons_avg
--------------------------------
per_of_nulls   :  % 18.32
num_of_nulls   :  5245
num_of_uniques :  161
--------------------------------
NaN       5245
5.000      831
4.900      812
4.500      690
0.000      652
5.100      647
4.700      618
5.400      609
4.800      609
5.600      594
4.300      564
5.300      558
5.200      552
4.600      550
4.200      539
4.100      518
3.800      516
5.700      504
5.500      503
5.900      498
4.000      484
4.400      442
6.400      438
6.000      430
6.300      414
5.800      399
3.700      360
3.900      353
3.600      327
7.000      312
3.400      296
6.500      292
6.100      282
6.200      278
6.600      274
6.900      270
7.400      265
7.100      253
6.700      251
6.800      226
7.300      220
7.200      202
8.400      194
8.000      194
7.600      181
3.500      180
8.200      166
7.700      165
7.800      165
7.500      156
12.000     110
3.300      109
9.000      107
9.200      103
12.500     102
8.600       95
9.800       93
8.900       92
8.300       88
3.000       84
7.900       83
9.600       79
8.700       79
1.700       77
9.500       77
1.500       73
9.400       72
9.700       69
8.800       69
8.500       67
10.100      66
1.800       66
10.600      66
3.200       64
8.100       64
11.800      62
11.400      62
9.100       61
9.900       55
10.900      52
12.100      51
2.100       49
1.900       47
10.000      46
1.400       44
10.500      44
12.400      41
9.300       40
1.200       40
11.000      39
12.800      37
10.300      36
10.400      35
12.200      34
2.800       33
1.600       30
11.200      28
2.000       27
1.100       26
10.800      25
12.300      23
11.700      23
13.600      22
11.500      22
11.900      22
10.200      21
3.100       19
13.500      19
2.400       16
1.300       15
11.600      14
12.600      14
2.200       13
11.100      13
11.300      13
10.700      12
1.000       11
2.500       11
14.000      10
2.300       10
13.800       9
13.000       8
0.800        8
2.900        7
12.900       7
13.100       7
2.600        6
12.700       6
0.600        5
13.400       5
13.900       5
13.200       5
0.700        5
99.900       4
14.300       3
0.900        3
16.700       3
14.400       3
14.100       3
2.700        2
16.500       2
14.900       2
53.000       2
15.600       2
93.000       2
14.200       1
14.700       1
15.000       1
16.800       1
18.300       1
23.000       1
16.400       1
15.500       1
15.100       1
15.900       1
56.000       1
0.500        1
16.000       1
57.000       1
61.000       1
14.500       1
44.000       1
Name: cons_avg, dtype: int64

**let us first examine how electric vehicles look like?**

In [ ]:
df.loc[df["fuel_type"] == "Electric"][["cons_avg"]]

       cons_avg
1           NaN
93          NaN
94          NaN
108         NaN
1213        NaN
1226        NaN
1271        NaN
1273        NaN
1281        NaN
1283        NaN
1303        NaN
1304        NaN
1307        NaN
1326        NaN
1331        NaN
1341        NaN
1350        NaN
1361        NaN
1364        NaN
1369        NaN
1400        NaN
1416        NaN
1425        NaN
1427        NaN
1436        NaN
1447        NaN
1458        NaN
1513        NaN
1575        NaN
1628        NaN
1641        NaN
1777        NaN
1798        NaN
1998        NaN
2000        NaN
2004        NaN
2015        NaN
2045        NaN
2082        NaN
2084        NaN
2086        NaN
2099        NaN
2130        NaN
2144        NaN
2156        NaN
2161        NaN
2166        NaN
2182        NaN
2192        NaN
2199        NaN
2230        NaN
2246        NaN
2255        NaN
2272        NaN
2276        NaN
2278        NaN
2301        NaN
2312        NaN
2317        NaN
2322        NaN
2328        NaN
2331        NaN
2355        NaN
2356        NaN
2360        NaN
2372        NaN
2713        NaN
3663        NaN
4810        NaN
4819        NaN
4823        NaN
4826        NaN
4838        NaN
4840        NaN
4873        NaN
4886        NaN
4914        NaN
4923        NaN
4929        NaN
4939        NaN
4943        NaN
4952        NaN
4957        NaN
4963        NaN
4972        NaN
4973        NaN
4985        NaN
4986        NaN
4989        NaN
4998        NaN
5002        NaN
5026        NaN
5028        NaN
5040        NaN
5045        NaN
5046        NaN
5047        NaN
5051        NaN
5054        NaN
5067        NaN
5071        NaN
5074        NaN
5075        NaN
5080        NaN
5087        NaN
5093        NaN
5097        NaN
5100        NaN
5102        NaN
5116        NaN
5117        NaN
5120        NaN
5122        NaN
5129        NaN
5134        NaN
5140        NaN
5143        NaN
5148        NaN
5149        NaN
5163        NaN
5166        NaN
5167        NaN
5199        NaN
5430        NaN
5748        NaN
5786        NaN
5816        NaN
5919        NaN
5936        NaN
6166        NaN
6205        NaN
6795        NaN
6803        NaN
6810        NaN
6811        NaN
6824        NaN
6830        NaN
6835        NaN
6837        NaN
6839        NaN
6847        NaN
6849        NaN
6852        NaN
6854        NaN
6860        NaN
6869        NaN
6870        NaN
6874        NaN
6876        NaN
6878        NaN
6879        NaN
6882        NaN
6896        NaN
6907        NaN
6909        NaN
6912        NaN
6916        NaN
6918        NaN
6943        NaN
6951        NaN
6952        NaN
6958        NaN
6982        NaN
7060        NaN
7071        NaN
7102        NaN
7103        NaN
7113        NaN
7114        NaN
7116        NaN
7124        NaN
7127        NaN
7132        NaN
7156        NaN
7232        NaN
7316        NaN
7335        NaN
7397        NaN
7408        NaN
7461        NaN
7480        NaN
7525        NaN
8400        NaN
8670        NaN
8876        NaN
8899        NaN
9005        NaN
9070        NaN
9079        NaN
9082        NaN
9087        NaN
9088        NaN
9089        NaN
9091        NaN
9102        NaN
9152        NaN
9154        NaN
9366        NaN
9426        NaN
9428        NaN
9448        NaN
9455        NaN
9473        NaN
9481        NaN
9487        NaN
9501        NaN
9514        NaN
9515        NaN
9522        NaN
9524        NaN
9527        NaN
9532        NaN
9538        NaN
9539        NaN
9540        NaN
9544        NaN
9545        NaN
9603        NaN
9608        NaN
9620        NaN
9654        NaN
9692        NaN
9699        NaN
9706        NaN
9716        NaN
9720        NaN
9795        NaN
9859        NaN
9889        NaN
9894        NaN
9918        NaN
9984        NaN
10023       NaN
10033       NaN
10039       NaN
10069       NaN
10074       NaN
10098       NaN
10104       NaN
10183       NaN
10215       NaN
10246       NaN
10258       NaN
10467       NaN
10566       NaN
10617       NaN
10625       NaN
10630       NaN
10631       NaN
10668       NaN
11467       NaN
11479       NaN
11544       NaN
11558       NaN
11572       NaN
11577       NaN
11578       NaN
11595       NaN
11619       NaN
11620       NaN
11632       NaN
11640       NaN
11641       NaN
11648       NaN
11653       NaN
11655       NaN
11665       NaN
11672       NaN
11673       NaN
11676       NaN
11690       NaN
11730       NaN
11776       NaN
11801       NaN
13978       NaN
13995       NaN
14055       NaN
14057       NaN
14066       NaN
14118       NaN
14188       NaN
14196       NaN
14212       NaN
14235       NaN
14248       NaN
14277       NaN
14284       NaN
14300       NaN
14316       NaN
14317       NaN
14952       NaN
15141       NaN
15143       NaN
15144       NaN
15145       NaN
15146       NaN
15147       NaN
15148       NaN
15149       NaN
15150       NaN
15151       NaN
15152       NaN
15153       NaN
15155       NaN
15156       NaN
15157       NaN
15158       NaN
15159       NaN
15161       NaN
15166       NaN
15181       NaN
15182       NaN
15183       NaN
15184       NaN
15185       NaN
15186       NaN
15187       NaN
15214       NaN
15648       NaN
15667       NaN
15903       NaN
16296       NaN
16312       NaN
16315       NaN
16319       NaN
16344       NaN
16351       NaN
16405       NaN
16416       NaN
16471       NaN
17699       NaN
17701       NaN
17718       NaN
17720       NaN
18114       NaN
18716       NaN
18725       NaN
18726       NaN
18730       NaN
18733       NaN
18742       NaN
18752       NaN
18759       NaN
18774       NaN
18779       NaN
18782       NaN
18784       NaN
18785       NaN
18786       NaN
18787       NaN
18789       NaN
18794       NaN
18795       NaN
18796       NaN
18807       NaN
18812       NaN
18816       NaN
18817       NaN
18819       NaN
18822       NaN
18836       NaN
18861       NaN
18866       NaN
18880       NaN
18917       NaN
18964       NaN
18990       NaN
19025       NaN
19080       NaN
20076       NaN
20414       NaN
20464       NaN
20480       NaN
20484       NaN
20487       NaN
20507       NaN
20516       NaN
20523       NaN
20533       NaN
20534       NaN
20535       NaN
20536       NaN
20537       NaN
20539       NaN
20540       NaN
20546       NaN
20551       NaN
20552       NaN
20557       NaN
20562       NaN
20563       NaN
20571       NaN
20582       NaN
20599       NaN
20600       NaN
20602       NaN
21623       NaN
21937       NaN
21948       NaN
21955       NaN
21957       NaN
21958       NaN
21960       NaN
21963       NaN
21966       NaN
21979       NaN
21986       NaN
21990       NaN
21994       NaN
22004       NaN
22008       NaN
22028       NaN
22029       NaN
22047       NaN
22048       NaN
22185       NaN
22247       NaN
22775       NaN
22783       NaN
22823       NaN
23379       NaN
23809       NaN
23870       NaN
23951       NaN
24051       NaN
24092       NaN
24099       NaN
24123       NaN
24170       NaN
24173       NaN
24832       NaN
24851       NaN
26952       NaN
26985       NaN
27338       NaN
27367       NaN
28340       NaN
28528       NaN

**No values seem to be entered for electric vehicles.**

### Domain Knowledge About Energy Consumption of Electric Cars

**According to the following cheatsheet as a quick reference which shows all-electric vehicles sorted by energy consumption, the average consumption of electric vehicles is ``201 Wh/km`` (20100 Wh/100km) - ``0.210 kWh/km`` (21 kWh/100km) (1 watt hour = 0.001 kilowatt hours). Data is based on real-world values. The average is corrected for multiple versions of the same model.**

Let’s take the ``MG5 Electric Long Range`` as an example, the world’s first all-electric station wagon. The battery offers a capacity of ``61.1 kWh``. With a fully charged battery, you can drive a distance up to ``400 km`` according to the European protocol for the measurement of energy consumption (WLTP). This means the average energy consumption of the MG5 Electric Long Range is ``15.3 kWh/100 km``.

Since electric driving is still unknown territory for many, the energy consumption of an electric car doesn’t mean much to most motorists. But to give you an idea, we can calculate the ‘equivalent fuel consumption’ of an electric car.

How? Well, we know a ``litre of petrol`` contains about ``8.9 kWh`` of energy. If we convert this and compare it with the energy consumption of the MG5 Electric Long Range (15.3 kWh/100 km divided by 8.9 kWh/litre), you have an equivalent fuel consumption of just ``1.7 l/100 km``. In other words, the MG5 Electric is considerably more energy efficient than any car with an internal Combustion Engine (ICE).

So, in our case, if the average consumption of electric vehicles, in general, is accepted as **``21 kWh/100km``**, then 21/8.9 is equal to **``2.359 l/100 km``**, which can be used to fill missing values for electric vehicles. 

**[Energy consumption of full electric vehicles](https://ev-database.org/cheatsheet/energy-consumption-electric-car)**


**It seems more sensible to fill missing values in two stages:**

- With the accepted ``Average`` consumption value of ``electric vehicles``.

- If it's posibble, with the a calculated ``Average`` value; otherwise, with the ``Median`` values of related make_model, body_type and fuel_type features for the ``others``.

In [ ]:
df.loc[df["fuel_type"] == "Electric", "cons_avg"] = 2.359
df.loc[df["fuel_type"] == "Electric"][["cons_avg"]]

       cons_avg
1         2.359
93        2.359
94        2.359
108       2.359
1213      2.359
1226      2.359
1271      2.359
1273      2.359
1281      2.359
1283      2.359
1303      2.359
1304      2.359
1307      2.359
1326      2.359
1331      2.359
1341      2.359
1350      2.359
1361      2.359
1364      2.359
1369      2.359
1400      2.359
1416      2.359
1425      2.359
1427      2.359
1436      2.359
1447      2.359
1458      2.359
1513      2.359
1575      2.359
1628      2.359
1641      2.359
1777      2.359
1798      2.359
1998      2.359
2000      2.359
2004      2.359
2015      2.359
2045      2.359
2082      2.359
2084      2.359
2086      2.359
2099      2.359
2130      2.359
2144      2.359
2156      2.359
2161      2.359
2166      2.359
2182      2.359
2192      2.359
2199      2.359
2230      2.359
2246      2.359
2255      2.359
2272      2.359
2276      2.359
2278      2.359
2301      2.359
2312      2.359
2317      2.359
2322      2.359
2328      2.359
2331      2.359
2355      2.359
2356      2.359
2360      2.359
2372      2.359
2713      2.359
3663      2.359
4810      2.359
4819      2.359
4823      2.359
4826      2.359
4838      2.359
4840      2.359
4873      2.359
4886      2.359
4914      2.359
4923      2.359
4929      2.359
4939      2.359
4943      2.359
4952      2.359
4957      2.359
4963      2.359
4972      2.359
4973      2.359
4985      2.359
4986      2.359
4989      2.359
4998      2.359
5002      2.359
5026      2.359
5028      2.359
5040      2.359
5045      2.359
5046      2.359
5047      2.359
5051      2.359
5054      2.359
5067      2.359
5071      2.359
5074      2.359
5075      2.359
5080      2.359
5087      2.359
5093      2.359
5097      2.359
5100      2.359
5102      2.359
5116      2.359
5117      2.359
5120      2.359
5122      2.359
5129      2.359
5134      2.359
5140      2.359
5143      2.359
5148      2.359
5149      2.359
5163      2.359
5166      2.359
5167      2.359
5199      2.359
5430      2.359
5748      2.359
5786      2.359
5816      2.359
5919      2.359
5936      2.359
6166      2.359
6205      2.359
6795      2.359
6803      2.359
6810      2.359
6811      2.359
6824      2.359
6830      2.359
6835      2.359
6837      2.359
6839      2.359
6847      2.359
6849      2.359
6852      2.359
6854      2.359
6860      2.359
6869      2.359
6870      2.359
6874      2.359
6876      2.359
6878      2.359
6879      2.359
6882      2.359
6896      2.359
6907      2.359
6909      2.359
6912      2.359
6916      2.359
6918      2.359
6943      2.359
6951      2.359
6952      2.359
6958      2.359
6982      2.359
7060      2.359
7071      2.359
7102      2.359
7103      2.359
7113      2.359
7114      2.359
7116      2.359
7124      2.359
7127      2.359
7132      2.359
7156      2.359
7232      2.359
7316      2.359
7335      2.359
7397      2.359
7408      2.359
7461      2.359
7480      2.359
7525      2.359
8400      2.359
8670      2.359
8876      2.359
8899      2.359
9005      2.359
9070      2.359
9079      2.359
9082      2.359
9087      2.359
9088      2.359
9089      2.359
9091      2.359
9102      2.359
9152      2.359
9154      2.359
9366      2.359
9426      2.359
9428      2.359
9448      2.359
9455      2.359
9473      2.359
9481      2.359
9487      2.359
9501      2.359
9514      2.359
9515      2.359
9522      2.359
9524      2.359
9527      2.359
9532      2.359
9538      2.359
9539      2.359
9540      2.359
9544      2.359
9545      2.359
9603      2.359
9608      2.359
9620      2.359
9654      2.359
9692      2.359
9699      2.359
9706      2.359
9716      2.359
9720      2.359
9795      2.359
9859      2.359
9889      2.359
9894      2.359
9918      2.359
9984      2.359
10023     2.359
10033     2.359
10039     2.359
10069     2.359
10074     2.359
10098     2.359
10104     2.359
10183     2.359
10215     2.359
10246     2.359
10258     2.359
10467     2.359
10566     2.359
10617     2.359
10625     2.359
10630     2.359
10631     2.359
10668     2.359
11467     2.359
11479     2.359
11544     2.359
11558     2.359
11572     2.359
11577     2.359
11578     2.359
11595     2.359
11619     2.359
11620     2.359
11632     2.359
11640     2.359
11641     2.359
11648     2.359
11653     2.359
11655     2.359
11665     2.359
11672     2.359
11673     2.359
11676     2.359
11690     2.359
11730     2.359
11776     2.359
11801     2.359
13978     2.359
13995     2.359
14055     2.359
14057     2.359
14066     2.359
14118     2.359
14188     2.359
14196     2.359
14212     2.359
14235     2.359
14248     2.359
14277     2.359
14284     2.359
14300     2.359
14316     2.359
14317     2.359
14952     2.359
15141     2.359
15143     2.359
15144     2.359
15145     2.359
15146     2.359
15147     2.359
15148     2.359
15149     2.359
15150     2.359
15151     2.359
15152     2.359
15153     2.359
15155     2.359
15156     2.359
15157     2.359
15158     2.359
15159     2.359
15161     2.359
15166     2.359
15181     2.359
15182     2.359
15183     2.359
15184     2.359
15185     2.359
15186     2.359
15187     2.359
15214     2.359
15648     2.359
15667     2.359
15903     2.359
16296     2.359
16312     2.359
16315     2.359
16319     2.359
16344     2.359
16351     2.359
16405     2.359
16416     2.359
16471     2.359
17699     2.359
17701     2.359
17718     2.359
17720     2.359
18114     2.359
18716     2.359
18725     2.359
18726     2.359
18730     2.359
18733     2.359
18742     2.359
18752     2.359
18759     2.359
18774     2.359
18779     2.359
18782     2.359
18784     2.359
18785     2.359
18786     2.359
18787     2.359
18789     2.359
18794     2.359
18795     2.359
18796     2.359
18807     2.359
18812     2.359
18816     2.359
18817     2.359
18819     2.359
18822     2.359
18836     2.359
18861     2.359
18866     2.359
18880     2.359
18917     2.359
18964     2.359
18990     2.359
19025     2.359
19080     2.359
20076     2.359
20414     2.359
20464     2.359
20480     2.359
20484     2.359
20487     2.359
20507     2.359
20516     2.359
20523     2.359
20533     2.359
20534     2.359
20535     2.359
20536     2.359
20537     2.359
20539     2.359
20540     2.359
20546     2.359
20551     2.359
20552     2.359
20557     2.359
20562     2.359
20563     2.359
20571     2.359
20582     2.359
20599     2.359
20600     2.359
20602     2.359
21623     2.359
21937     2.359
21948     2.359
21955     2.359
21957     2.359
21958     2.359
21960     2.359
21963     2.359
21966     2.359
21979     2.359
21986     2.359
21990     2.359
21994     2.359
22004     2.359
22008     2.359
22028     2.359
22029     2.359
22047     2.359
22048     2.359
22185     2.359
22247     2.359
22775     2.359
22783     2.359
22823     2.359
23379     2.359
23809     2.359
23870     2.359
23951     2.359
24051     2.359
24092     2.359
24099     2.359
24123     2.359
24170     2.359
24173     2.359
24832     2.359
24851     2.359
26952     2.359
26985     2.359
27338     2.359
27367     2.359
28340     2.359
28528     2.359

In [ ]:
first_looking("cons_avg")

COLUMN NAME    :  cons_avg
--------------------------------
per_of_nulls   :  % 16.79
num_of_nulls   :  4807
num_of_uniques :  162
--------------------------------
NaN       4807
5.000      831
4.900      812
4.500      690
0.000      652
5.100      647
4.700      618
5.400      609
4.800      609
5.600      594
4.300      564
5.300      558
5.200      552
4.600      550
4.200      539
4.100      518
3.800      516
5.700      504
5.500      503
5.900      498
4.000      484
4.400      442
2.359      438
6.400      438
6.000      430
6.300      414
5.800      399
3.700      360
3.900      353
3.600      327
7.000      312
3.400      296
6.500      292
6.100      282
6.200      278
6.600      274
6.900      270
7.400      265
7.100      253
6.700      251
6.800      226
7.300      220
7.200      202
8.000      194
8.400      194
7.600      181
3.500      180
8.200      166
7.800      165
7.700      165
7.500      156
12.000     110
3.300      109
9.000      107
9.200      103
12.500     102
8.600       95
9.800       93
8.900       92
8.300       88
3.000       84
7.900       83
8.700       79
9.600       79
9.500       77
1.700       77
1.500       73
9.400       72
9.700       69
8.800       69
8.500       67
10.100      66
1.800       66
10.600      66
8.100       64
3.200       64
11.800      62
11.400      62
9.100       61
9.900       55
10.900      52
12.100      51
2.100       49
1.900       47
10.000      46
10.500      44
1.400       44
12.400      41
1.200       40
9.300       40
11.000      39
12.800      37
10.300      36
10.400      35
12.200      34
2.800       33
1.600       30
11.200      28
2.000       27
1.100       26
10.800      25
12.300      23
11.700      23
11.900      22
11.500      22
13.600      22
10.200      21
3.100       19
13.500      19
2.400       16
1.300       15
11.600      14
12.600      14
2.200       13
11.100      13
11.300      13
10.700      12
2.500       11
1.000       11
2.300       10
14.000      10
13.800       9
0.800        8
13.000       8
2.900        7
12.900       7
13.100       7
12.700       6
2.600        6
0.600        5
13.200       5
13.400       5
13.900       5
0.700        5
99.900       4
14.100       3
14.400       3
0.900        3
16.700       3
14.300       3
2.700        2
16.500       2
14.900       2
53.000       2
15.600       2
93.000       2
23.000       1
15.100       1
14.700       1
15.000       1
16.800       1
18.300       1
14.500       1
14.200       1
15.500       1
61.000       1
16.400       1
56.000       1
0.500        1
16.000       1
57.000       1
15.900       1
44.000       1
Name: cons_avg, dtype: int64

**Let us calculate the average consumption of fuel for vehicles according to values at hand:**

In [ ]:
df[(df["cons_avg"].isnull()) & (df["cons_city"].notnull()) & (df["cons_country"].notnull())]

Empty DataFrame
Columns: [make_model, make, location, price, body_type, type, doors, warranty, mileage, gearbox, fuel_type, seller, seats, engine_size, gears, co_emissions, drivetrain, comfort_&_convenience, entertainment_&_media, safety_&_security, extras, empty_weight, full_service_history, upholstery, previous_owner, energy_efficiency_class, age, power_kW, cons_avg, cons_city, cons_country]
Index: []

In [ ]:
cons_avg2 = (df["cons_country"] + df["cons_city"])/2
cons_avg2.value_counts(dropna=False)

NaN       8530
0.000      379
5.100      335
5.650      331
5.150      317
4.500      295
5.350      287
5.000      280
4.750      264
5.500      261
4.900      261
4.350      251
6.250      247
5.250      244
5.200      236
5.600      233
5.400      229
6.000      227
7.000      225
6.350      223
3.450      218
4.600      215
5.750      213
5.050      212
4.400      210
4.650      206
5.850      205
4.850      196
4.800      192
8.000      187
4.250      186
5.900      183
5.700      177
6.400      177
6.600      175
4.550      170
4.700      170
4.150      161
6.100      160
4.300      160
5.300      157
6.150      157
3.900      151
7.500      147
5.200      146
3.850      143
6.550      142
4.000      141
3.750      141
4.950      139
6.650      138
6.800      136
3.800      133
3.950      132
5.550      130
5.450      120
7.900      120
5.450      117
4.200      116
6.850      112
6.500      109
4.950      109
5.950      107
5.050      106
8.350      106
4.450      103
5.950       99
7.700       99
7.650       97
7.400       93
6.300       92
5.800       92
3.550       91
5.300       91
6.050       90
4.100       90
7.150       88
7.250       87
7.100       87
4.450       85
3.900       85
3.700       82
5.700       81
7.350       81
7.600       81
8.850       80
3.850       80
7.050       78
3.500       78
6.750       78
6.900       73
6.700       72
8.650       71
4.800       70
9.950       69
5.800       69
10.450      69
6.200       68
10.000      68
8.150       67
9.750       65
13.550      65
7.750       64
7.200       64
3.300       62
4.700       62
6.300       61
6.900       61
3.700       61
11.000      61
6.700       59
8.400       59
9.100       59
8.300       58
10.400      58
6.050       58
7.050       56
8.500       56
8.450       55
10.350      55
9.050       55
7.800       53
8.050       53
4.200       52
4.050       50
8.250       50
6.200       49
6.450       49
11.550      49
7.850       48
12.400      46
12.000      46
8.900       45
9.350       45
6.950       44
8.100       44
6.950       43
8.700       43
7.700       43
3.650       43
10.850      43
6.550       43
9.800       43
8.200       43
8.950       42
13.300      42
9.000       42
4.300       41
7.400       40
13.050      40
8.150       39
9.500       39
3.600       39
6.450       38
12.900      38
4.550       37
7.450       37
8.550       37
6.850       37
7.300       36
13.600      36
9.700       36
8.800       35
9.150       35
12.050      34
8.750       34
3.950       34
14.050      34
7.850       33
3.000       33
6.800       33
9.200       32
10.900      30
9.250       30
7.600       30
7.350       30
10.700      29
14.300      29
9.300       28
9.550       28
7.550       28
11.650      28
5.550       27
8.600       27
7.300       26
7.950       25
7.200       24
7.150       24
13.200      24
7.450       23
9.600       23
10.300      23
11.100      22
9.450       22
11.950      21
10.200      21
3.600       21
11.600      20
10.750      20
9.650       20
3.800       20
10.650      19
7.800       19
12.500      18
12.250      18
7.550       18
3.200       18
10.500      18
11.250      17
10.100      17
3.350       16
7.950       16
3.400       16
9.850       15
12.700      15
9.900       15
14.500      15
14.000      14
10.800      14
12.550      13
14.800      13
4.050       12
6.650       12
11.150      12
13.400      12
11.450      12
12.300      12
10.150      12
13.800      11
13.350      11
7.900       11
13.750      11
11.200      11
14.100      11
3.250       11
9.150       10
8.850       10
12.650      10
12.800      10
13.700      10
6.600       10
12.950       9
10.600       9
11.300       9
8.100        9
9.350        9
11.850       9
10.250       8
14.950       8
35.350       8
12.200       8
12.850       8
11.700       8
11.800       8
7.650        8
11.050       7
12.650       7
9.400        7
9.900        7
13.150       7
11.400       7
13.000       7
9.400        7
8.400        6
15.000       6
11.900       6
12.750       5
8.350        5
10.050       5
12.700       5
11.400       5
13.350       5
13.800       5
13.600       5
9.600        5
8.650        5
8.600        5
14.950       5
10.150       4
9.650        4
8.900        4
3.650        4
7.100        4
12.100       4
0.750        4
11.850       4
11.600       4
12.200       4
13.100       4
10.550       4
10.900       4
2.700        3
14.150       3
11.150       3
13.250       3
9.100        3
9.850        3
10.850       3
14.850       3
1.000        3
12.150       3
12.350       3
15.050       2
12.350       2
2.750        2
1.100        2
12.450       2
16.700       2
17.150       2
10.650       2
13.100       2
10.400       2
14.400       2
17.750       2
1.800        2
15.400       2
0.850        2
3.350        2
11.650       2
34.350       2
15.700       2
13.450       2
13.500       2
11.500       2
18.150       2
3.400        2
1.850        2
13.850       2
15.850       2
13.900       2
15.550       2
3.150        2
14.600       2
16.650       1
14.650       1
16.000       1
10.950       1
6.100        1
14.750       1
1.200        1
14.300       1
2.150        1
6.400        1
12.600       1
0.800        1
15.350       1
15.950       1
14.700       1
12.450       1
13.200       1
15.350       1
15.450       1
11.750       1
98.950       1
12.600       1
64.000       1
25.650       1
14.650       1
1.750        1
25.900       1
16.250       1
49.000       1
2.900        1
17.050       1
10.100       1
15.650       1
11.950       1
14.900       1
10.600       1
16.400       1
4.900        1
11.350       1
14.550       1
14.100       1
40.500       1
dtype: int64

In [ ]:
df["cons_avg"] = df["cons_avg"].fillna(cons_avg2)

In [ ]:
first_looking("cons_avg")

COLUMN NAME    :  cons_avg
--------------------------------
per_of_nulls   :  % 16.79
num_of_nulls   :  4807
num_of_uniques :  162
--------------------------------
NaN       4807
5.000      831
4.900      812
4.500      690
0.000      652
5.100      647
4.700      618
5.400      609
4.800      609
5.600      594
4.300      564
5.300      558
5.200      552
4.600      550
4.200      539
4.100      518
3.800      516
5.700      504
5.500      503
5.900      498
4.000      484
4.400      442
2.359      438
6.400      438
6.000      430
6.300      414
5.800      399
3.700      360
3.900      353
3.600      327
7.000      312
3.400      296
6.500      292
6.100      282
6.200      278
6.600      274
6.900      270
7.400      265
7.100      253
6.700      251
6.800      226
7.300      220
7.200      202
8.000      194
8.400      194
7.600      181
3.500      180
8.200      166
7.800      165
7.700      165
7.500      156
12.000     110
3.300      109
9.000      107
9.200      103
12.500     102
8.600       95
9.800       93
8.900       92
8.300       88
3.000       84
7.900       83
8.700       79
9.600       79
9.500       77
1.700       77
1.500       73
9.400       72
9.700       69
8.800       69
8.500       67
10.100      66
1.800       66
10.600      66
8.100       64
3.200       64
11.800      62
11.400      62
9.100       61
9.900       55
10.900      52
12.100      51
2.100       49
1.900       47
10.000      46
10.500      44
1.400       44
12.400      41
1.200       40
9.300       40
11.000      39
12.800      37
10.300      36
10.400      35
12.200      34
2.800       33
1.600       30
11.200      28
2.000       27
1.100       26
10.800      25
12.300      23
11.700      23
11.900      22
11.500      22
13.600      22
10.200      21
3.100       19
13.500      19
2.400       16
1.300       15
11.600      14
12.600      14
2.200       13
11.100      13
11.300      13
10.700      12
2.500       11
1.000       11
2.300       10
14.000      10
13.800       9
0.800        8
13.000       8
2.900        7
12.900       7
13.100       7
12.700       6
2.600        6
0.600        5
13.200       5
13.400       5
13.900       5
0.700        5
99.900       4
14.100       3
14.400       3
0.900        3
16.700       3
14.300       3
2.700        2
16.500       2
14.900       2
53.000       2
15.600       2
93.000       2
23.000       1
15.100       1
14.700       1
15.000       1
16.800       1
18.300       1
14.500       1
14.200       1
15.500       1
61.000       1
16.400       1
56.000       1
0.500        1
16.000       1
57.000       1
15.900       1
44.000       1
Name: cons_avg, dtype: int64

**However, this approach could NOT work and impact on decreasing the number of missing values in ``cons_avg``**

In [ ]:
df["cons_avg"].fillna("-", inplace=True)

In [ ]:
df.groupby(["make_model", "body_type", "fuel_type", "cons_avg"]).price.describe()

                                                  count      mean      std  \
make_model   body_type        fuel_type cons_avg
Dacia        Compact          Benzine   -         3.000 21431.000 1661.744
             Sedan            Benzine   -         1.000  9999.000      NaN
             Station wagon    Benzine   5.6       1.000 21799.000      NaN
Dacia Break  Station wagon    Benzine   -         1.000 20500.000      NaN
Dacia Dokker Compact          Diesel    4.2       1.000 11930.000      NaN
...                                                 ...       ...      ...
Volvo XC90   Off-Road/Pick-up Electric  2.359     4.000 64400.000 9814.955
             Sedan            Diesel    6.7       2.000 48100.000  565.685
                                        -         1.000 84900.000      NaN
             Station wagon    Diesel    5.7       2.000 29500.000    0.000
                                        5.8       2.000 36000.000    0.000

                                                       min       25%  \
make_model   body_type        fuel_type cons_avg
Dacia        Compact          Benzine   -        19515.000 20907.000
             Sedan            Benzine   -         9999.000  9999.000
             Station wagon    Benzine   5.6      21799.000 21799.000
Dacia Break  Station wagon    Benzine   -        20500.000 20500.000
Dacia Dokker Compact          Diesel    4.2      11930.000 11930.000
...                                                    ...       ...
Volvo XC90   Off-Road/Pick-up Electric  2.359    55900.000 55900.000
             Sedan            Diesel    6.7      47700.000 47900.000
                                        -        84900.000 84900.000
             Station wagon    Diesel    5.7      29500.000 29500.000
                                        5.8      36000.000 36000.000

                                                       50%       75%       max
make_model   body_type        fuel_type cons_avg
Dacia        Compact          Benzine   -        22299.000 22389.000 22479.000
             Sedan            Benzine   -         9999.000  9999.000  9999.000
             Station wagon    Benzine   5.6      21799.000 21799.000 21799.000
Dacia Break  Station wagon    Benzine   -        20500.000 20500.000 20500.000
Dacia Dokker Compact          Diesel    4.2      11930.000 11930.000 11930.000
...                                                    ...       ...       ...
Volvo XC90   Off-Road/Pick-up Electric  2.359    64400.000 72900.000 72900.000
             Sedan            Diesel    6.7      48100.000 48300.000 48500.000
                                        -        84900.000 84900.000 84900.000
             Station wagon    Diesel    5.7      29500.000 29500.000 29500.000
                                        5.8      36000.000 36000.000 36000.000

[7388 rows x 8 columns]

In [ ]:
df["cons_avg"].replace("-", np.nan, inplace=True)

In [ ]:
fill_median(df, "make_model", "body_type", "fuel_type", "cons_avg")

column name    :  cons_avg
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  219
--------------------------------
4.900     1043
5.000      966
4.500      889
5.100      887
5.300      887
0.000      721
4.700      710
5.400      706
4.600      683
5.600      675
4.800      670
4.300      641
5.200      615
5.900      612
3.800      612
4.100      606
4.200      605
5.700      595
5.500      569
4.000      552
4.400      523
6.300      513
6.000      500
3.700      475
5.800      467
6.400      452
2.359      443
3.600      394
3.900      393
6.500      344
6.900      334
7.000      333
7.400      323
6.100      306
3.400      302
6.600      302
6.200      300
6.700      269
7.100      267
12.000     266
6.800      248
7.300      246
8.400      229
7.700      220
7.600      208
7.500      206
7.200      204
8.000      203
3.500      194
12.100     192
7.800      184
8.200      170
9.800      138
8.300      128
8.900      119
3.300      115
9.200      115
9.000      111
9.600      105
12.500     103
8.600       96
3.000       91
8.500       89
10.100      86
8.700       84
7.900       83
9.500       83
9.400       82
10.000      81
9.700       80
1.700       77
1.500       74
8.800       73
3.200       72
10.600      67
1.800       66
8.100       65
11.400      64
9.100       64
4.150       62
10.300      62
11.800      62
9.900       59
10.900      58
2.100       54
1.400       52
9.300       49
1.900       47
12.400      46
10.500      44
10.400      42
1.200       40
11.000      40
11.200      39
12.800      37
4.050       35
5.650       35
12.200      34
6.150       33
2.800       33
7.700       30
4.650       30
1.600       30
4.300       29
10.800      29
11.500      29
2.000       27
1.100       26
11.700      26
12.300      25
8.250       25
11.900      24
7.250       22
11.600      22
13.600      22
10.200      21
3.100       20
7.150       20
13.500      19
3.950       19
14.000      17
4.950       17
2.400       16
13.000      15
1.300       15
10.700      15
11.300      14
2.300       14
2.200       14
2.500       14
12.600      14
4.350       13
11.100      13
6.800       12
6.700       12
13.800      11
1.000       11
0.800       10
13.900      10
5.050        9
2.900        8
3.850        8
5.250        8
16.200       8
4.850        8
5.850        8
0.600        7
5.350        7
13.100       7
3.750        7
5.150        7
14.800       7
11.850       7
12.900       7
13.200       6
12.700       6
2.600        6
4.750        5
6.250        5
10.750       5
0.700        5
13.400       5
7.350        4
5.800        4
99.900       4
5.450        4
6.450        3
16.700       3
14.100       3
14.400       3
0.900        3
14.300       3
16.500       2
15.600       2
6.650        2
5.300        2
7.300        2
5.950        2
53.000       2
14.900       2
6.350        2
2.700        2
5.750        2
93.000       2
4.550        2
15.000       1
18.300       1
16.800       1
15.900       1
57.000       1
14.700       1
3.950        1
0.850        1
9.250        1
7.800        1
3.150        1
61.000       1
10.350       1
23.000       1
15.500       1
15.100       1
14.500       1
16.000       1
16.400       1
9.150        1
8.550        1
0.500        1
8.650        1
6.200        1
4.250        1
3.900        1
5.550        1
0.650        1
56.000       1
6.850        1
6.050        1
44.000       1
7.050        1
14.200       1
Name: cons_avg, dtype: int64

## cons_city

In [ ]:
first_looking("cons_city")

COLUMN NAME    :  cons_city
--------------------------------
per_of_nulls   :  % 29.79
num_of_nulls   :  8530
num_of_uniques :  195
--------------------------------
NaN       8530
5.800      494
6.400      485
5.300      479
5.700      464
6.300      433
6.500      424
6.200      423
5.900      420
5.500      412
6.000      405
6.100      401
0.000      390
5.600      382
6.600      374
5.200      373
5.000      345
4.400      327
5.400      321
6.700      320
4.200      311
6.800      307
7.000      298
7.800      293
7.600      278
4.300      276
5.100      272
7.900      260
3.700      259
4.700      245
8.500      242
7.500      235
4.600      232
4.900      230
7.100      228
7.200      207
7.300      207
9.300      206
4.800      205
4.500      205
8.200      205
6.900      204
8.900      189
10.100     187
7.400      186
8.000      186
8.600      180
8.100      180
9.100      177
8.700      175
7.700      171
8.800      171
4.100      167
9.000      166
8.400      146
3.800      129
11.500     127
10.400     126
9.600      126
8.300      121
4.000      120
9.500      119
10.200     117
10.000     115
11.200     112
10.900     106
9.800      101
10.300      98
9.700       96
9.400       88
10.600      87
9.200       81
13.500      79
10.800      77
11.000      75
11.900      75
13.000      73
17.000      72
12.900      71
14.000      68
18.300      68
12.800      66
13.800      66
11.600      64
3.000       62
17.800      60
11.400      60
9.900       59
10.700      58
12.000      56
14.400      53
10.500      51
16.100      49
12.500      48
15.600      47
11.300      47
16.000      44
3.900       44
15.300      43
13.100      42
3.500       38
18.600      37
19.000      36
14.700      36
14.100      36
12.400      34
15.000      34
19.600      34
12.200      32
14.200      32
13.700      32
19.900      31
11.800      30
13.600      29
16.800      27
14.500      27
15.700      26
15.400      26
12.600      25
11.100      25
15.800      24
12.300      24
13.400      23
12.700      22
14.300      21
12.100      21
16.200      20
16.600      20
3.600       19
15.200      18
20.000      15
11.700      14
15.500      14
15.100      13
13.200      13
16.700      13
3.300       12
19.100      12
18.900      11
20.100      11
3.400       11
13.300      11
14.800      11
17.200      11
14.600      10
14.900       9
15.900       8
13.900       8
66.000       8
17.300       8
3.200        7
16.500       7
18.000       7
19.300       7
18.100       6
17.100       6
20.300       6
18.200       5
17.900       5
17.500       5
21.300       4
1.000        4
17.700       4
0.700        4
21.700       4
18.800       4
20.200       3
18.700       3
18.500       3
0.800        3
2.200        3
64.000       2
20.900       2
16.300       2
24.100       2
1.200        2
21.800       2
17.600       2
21.400       2
0.400        2
99.900       1
2.000        1
17.400       1
19.400       1
23.200       1
22.600       1
19.700       1
21.100       1
0.500        1
22.800       1
46.000       1
21.500       1
50.000       1
3.100        1
79.000       1
76.100       1
Name: cons_city, dtype: int64

In [ ]:
df.shape

(28630, 31)

In [ ]:
df.drop("cons_city", axis=1, inplace=True)

In [ ]:
df.shape

(28630, 30)

## cons_country

In [ ]:
first_looking("cons_country")

COLUMN NAME    :  cons_country
--------------------------------
per_of_nulls   :  % 29.79
num_of_nulls   :  8530
num_of_uniques :  114
--------------------------------
NaN       8530
4.300      884
4.000      804
4.200      750
4.700      730
5.000      725
3.600      679
4.600      668
4.900      663
3.800      660
4.500      659
3.900      640
4.100      632
5.100      598
4.400      587
3.700      520
5.700      474
4.800      460
5.400      445
5.200      443
5.300      413
5.600      394
5.500      383
0.000      379
5.800      376
3.400      341
3.200      334
3.300      327
3.500      304
5.900      301
6.500      289
6.200      261
6.000      242
6.700      239
6.100      229
7.000      205
6.400      202
6.300      199
3.000      163
6.900      150
6.800      139
3.100      136
7.400      113
8.700      108
6.600      108
7.800      105
8.100       98
7.600       98
7.100       98
7.700       94
9.100       84
7.300       78
8.300       77
7.200       77
8.000       77
8.500       75
8.200       69
8.800       65
2.900       62
7.900       62
9.300       53
9.600       44
7.500       42
8.900       36
9.000       34
8.400       33
9.800       25
8.600       22
9.200       22
9.500       20
11.000      15
10.500      13
10.900      12
9.400       12
10.000      12
2.800       12
11.200      11
10.300      10
9.700        9
10.400       8
2.700        6
12.000       6
1.000        5
0.800        5
11.800       5
10.200       5
11.100       5
13.700       4
9.900        4
12.900       4
2.600        2
0.900        2
12.200       2
11.900       2
10.600       2
13.400       2
2.400        1
12.100       1
0.600        1
14.700       1
11.400       1
48.000       1
12.400       1
10.100       1
13.000       1
44.900       1
49.000       1
98.000       1
1.900        1
14.000       1
18.000       1
11.700       1
14.400       1
11.500       1
12.700       1
Name: cons_country, dtype: int64

In [ ]:
df.shape

(28630, 30)

In [ ]:
df.drop("cons_country", axis=1, inplace=True)

In [ ]:
df.shape

(28630, 29)

## drivetrain

In [ ]:
first_looking("drivetrain")

COLUMN NAME    :  drivetrain
--------------------------------
per_of_nulls   :  % 41.0
num_of_nulls   :  11737
num_of_uniques :  3
--------------------------------
Front    12066
NaN      11737
4WD       3252
Rear      1575
Name: drivetrain, dtype: int64

In [ ]:
df["drivetrain"].fillna("-", inplace=True)

In [ ]:
df.groupby(["make_model", "body_type", "drivetrain"]).price.describe()

                                          count      mean       std       min  \
make_model  body_type        drivetrain
Dacia       Compact          -            2.000 22389.000   127.279 22299.000
                             Front        1.000 19515.000       NaN 19515.000
            Sedan            -            1.000  9999.000       NaN  9999.000
            Station wagon    -            1.000 21799.000       NaN 21799.000
Dacia Break Station wagon    -            1.000 20500.000       NaN 20500.000
...                                         ...       ...       ...       ...
Volvo XC90  Off-Road/Pick-up -           24.000 51277.083 18230.805 19975.000
                             4WD        167.000 52999.940 20131.833  6400.000
                             Front        8.000 30697.250 10639.354 13900.000
            Sedan            -            3.000 60366.667 21250.255 47700.000
            Station wagon    4WD          4.000 32750.000  3752.777 29500.000

                                              25%       50%       75%  \
make_model  body_type        drivetrain
Dacia       Compact          -          22344.000 22389.000 22434.000
                             Front      19515.000 19515.000 19515.000
            Sedan            -           9999.000  9999.000  9999.000
            Station wagon    -          21799.000 21799.000 21799.000
Dacia Break Station wagon    -          20500.000 20500.000 20500.000
...                                           ...       ...       ...
Volvo XC90  Off-Road/Pick-up -          38118.750 49842.500 63750.000
                             4WD        42500.000 49980.000 65145.000
                             Front      28967.500 34494.500 36224.250
            Sedan            -          48100.000 48500.000 66700.000
            Station wagon    4WD        29500.000 32750.000 36000.000

                                              max
make_model  body_type        drivetrain
Dacia       Compact          -          22479.000
                             Front      19515.000
            Sedan            -           9999.000
            Station wagon    -          21799.000
Dacia Break Station wagon    -          20500.000
...                                           ...
Volvo XC90  Off-Road/Pick-up -          83900.000
                             4WD        97450.000
                             Front      39900.000
            Sedan            -          84900.000
            Station wagon    4WD        36000.000

[2116 rows x 8 columns]

**The ``drivetrain`` of cars changes by their ``make_models`` & ``body_type`` most of the time. So it is more beneficial to decide to fill missing values with mode value of related group.**

In [ ]:
df[df["body_type"] == "Off-Road/Pick-up"][["make_model", "body_type", "fuel_type", "drivetrain"]].value_counts()

make_model                body_type         fuel_type           drivetrain
Volvo XC60                Off-Road/Pick-up  Diesel              4WD           138
Volvo XC90                Off-Road/Pick-up  Diesel              4WD           131
Fiat 500X                 Off-Road/Pick-up  Benzine             Front         114
                                            Diesel              Front          85
Volvo XC60                Off-Road/Pick-up  Benzine             4WD            78
Dacia Duster              Off-Road/Pick-up  Diesel              -              71
Skoda Kodiaq              Off-Road/Pick-up  Diesel              4WD            70
SEAT Arona                Off-Road/Pick-up  Benzine             -              68
Toyota C-HR               Off-Road/Pick-up  Benzine             -              68
Fiat 500X                 Off-Road/Pick-up  Benzine             -              67
Volvo XC60                Off-Road/Pick-up  Diesel              -              60
Peugeot 3008              Off-Road/Pick-up  Diesel              Front          59
Volvo XC40                Off-Road/Pick-up  Benzine             Front          57
Dacia Duster              Off-Road/Pick-up  Diesel              Front          57
SEAT Arona                Off-Road/Pick-up  Benzine             Front          57
Opel Crossland X          Off-Road/Pick-up  Benzine             -              56
Hyundai TUCSON            Off-Road/Pick-up  Benzine             Front          55
Renault Captur            Off-Road/Pick-up  Benzine             -              55
Volvo XC60                Off-Road/Pick-up  Diesel              Front          54
Peugeot 3008              Off-Road/Pick-up  Diesel              -              54
Dacia Duster              Off-Road/Pick-up  Benzine             Front          54
Nissan Qashqai            Off-Road/Pick-up  Diesel              Front          54
Hyundai TUCSON            Off-Road/Pick-up  Benzine             -              52
Nissan Qashqai            Off-Road/Pick-up  Benzine             -              51
Dacia Duster              Off-Road/Pick-up  Benzine             -              51
Toyota Land Cruiser       Off-Road/Pick-up  Diesel              4WD            51
Renault Captur            Off-Road/Pick-up  Benzine             Front          49
Nissan Qashqai            Off-Road/Pick-up  Benzine             Front          49
Volvo XC40                Off-Road/Pick-up  Benzine             -              48
Skoda Kamiq               Off-Road/Pick-up  Benzine             -              47
SEAT Ateca                Off-Road/Pick-up  Benzine             -              43
                                                                Front          42
Peugeot 3008              Off-Road/Pick-up  Benzine             Front          41
Ford Kuga                 Off-Road/Pick-up  Benzine             -              41
                                            Diesel              -              40
Toyota C-HR               Off-Road/Pick-up  Benzine             Front          40
Dacia Sandero             Off-Road/Pick-up  Benzine             -              40
Peugeot 2008              Off-Road/Pick-up  Benzine             Front          40
Ford Kuga                 Off-Road/Pick-up  Diesel              4WD            38
Skoda Karoq               Off-Road/Pick-up  Benzine             Front          37
Dacia Duster              Off-Road/Pick-up  Diesel              4WD            37
Fiat 500X                 Off-Road/Pick-up  Diesel              -              37
Ford Kuga                 Off-Road/Pick-up  Benzine             Front          36
Skoda Karoq               Off-Road/Pick-up  Benzine             -              36
Peugeot 5008              Off-Road/Pick-up  Diesel              Front          36
Volvo XC90                Off-Road/Pick-up  Benzine             4WD            36
Opel Grandland X          Off-Road/Pick-up  Benzine             -              36
Skoda Kodiaq              Off-Road/Pick-up  Benzine             4WD            35
Skoda Kamiq               Off-Road/Pick-up  Benzine             Front          35
Renault Kadjar            Off-Road/Pick-up  Benzine             -              35
Nissan Qashqai            Off-Road/Pick-up  Diesel              -              35
Volvo XC40                Off-Road/Pick-up  Diesel              4WD            34
Renault Kadjar            Off-Road/Pick-up  Benzine             Front          34
Opel Grandland X          Off-Road/Pick-up  Diesel              -              34
Ford Ranger               Off-Road/Pick-up  Diesel              4WD            32
Opel Grandland X          Off-Road/Pick-up  Benzine             Front          32
Toyota RAV 4              Off-Road/Pick-up  Benzine             4WD            31
Renault Kadjar            Off-Road/Pick-up  Diesel              Front          30
Hyundai KONA              Off-Road/Pick-up  Benzine             Front          30
Hyundai TUCSON            Off-Road/Pick-up  Benzine             4WD            30
Peugeot 2008              Off-Road/Pick-up  Diesel              Front          30
Ford Edge                 Off-Road/Pick-up  Diesel              4WD            29
Peugeot 2008              Off-Road/Pick-up  Diesel              -              29
Toyota Land Cruiser       Off-Road/Pick-up  Diesel              -              28
Toyota RAV 4              Off-Road/Pick-up  Benzine             -              28
SEAT Tarraco              Off-Road/Pick-up  Diesel              4WD            28
SEAT Ateca                Off-Road/Pick-up  Diesel              Front          28
Mercedes-Benz GLC 220     Off-Road/Pick-up  Diesel              4WD            27
Hyundai TUCSON            Off-Road/Pick-up  Diesel              -              27
Skoda Karoq               Off-Road/Pick-up  Diesel              4WD            27
Peugeot 3008              Off-Road/Pick-up  Benzine             -              26
Renault Arkana            Off-Road/Pick-up  Benzine             -              26
Hyundai TUCSON            Off-Road/Pick-up  Diesel              Front          26
Opel Mokka                Off-Road/Pick-up  Benzine             -              26
Volvo XC40                Off-Road/Pick-up  Diesel              -              26
Toyota RAV 4              Off-Road/Pick-up  Benzine             Front          25
Ford Kuga                 Off-Road/Pick-up  Diesel              Front          25
Nissan X-Trail            Off-Road/Pick-up  Diesel              -              24
Opel Grandland X          Off-Road/Pick-up  Benzine             4WD            24
SEAT Ateca                Off-Road/Pick-up  Benzine             4WD            24
                                            Diesel              -              23
Renault Captur            Off-Road/Pick-up  Diesel              Front          23
Dacia Duster              Off-Road/Pick-up  Benzine             4WD            23
Ford Kuga                 Off-Road/Pick-up  Benzine             4WD            23
Ford Puma                 Off-Road/Pick-up  Benzine             -              22
Nissan X-Trail            Off-Road/Pick-up  Diesel              4WD            22
Hyundai KONA              Off-Road/Pick-up  Benzine             -              21
SEAT Ateca                Off-Road/Pick-up  Diesel              4WD            20
Opel Crossland X          Off-Road/Pick-up  Benzine             Front          20
Renault Kadjar            Off-Road/Pick-up  Diesel              -              20
Peugeot 5008              Off-Road/Pick-up  Diesel              -              19
Opel Mokka X              Off-Road/Pick-up  Benzine             -              19
Nissan Juke               Off-Road/Pick-up  Benzine             -              19
Ford Puma                 Off-Road/Pick-up  Benzine             Front          19
Fiat 500X                 Off-Road/Pick-up  Diesel              4WD            19
Hyundai SANTA FE          Off-Road/Pick-up  Diesel              4WD            19
Renault Koleos            Off-Road/Pick-up  Diesel              -              18
                                                                4WD            18
Volvo XC90                Off-Road/Pick-up  Diesel              -              18
Opel Mokka                Off-Road/Pick-up  Benzine             Front          18
Peugeot 2008              Off-Road/Pick-up  Benzine             -              17
Mercedes-Benz G 63 AMG    Off-Road/Pick-up  Benzine             4WD            17
Skoda Kodiaq              Off-Road/Pick-up  Diesel              Front          17
Opel Crossland            Off-Road/Pick-up  Benzine             Front          17
Nissan Juke               Off-Road/Pick-up  Benzine             Front          17
Volvo XC40                Off-Road/Pick-up  Benzine             4WD            16
                                            Diesel              Front          16
Nissan Navara             Off-Road/Pick-up  Diesel              4WD            16
Dacia Duster              Off-Road/Pick-up  Liquid/Natural Gas  -              15
Toyota Hilux              Off-Road/Pick-up  Diesel              4WD            15
Mercedes-Benz EQC 400     Off-Road/Pick-up  Electric            4WD            15
Toyota Yaris Cross        Off-Road/Pick-up  Benzine             Front          15
Mercedes-Benz GLC 300     Off-Road/Pick-up  Benzine             4WD            15
Skoda Kodiaq              Off-Road/Pick-up  Diesel              -              14
Hyundai SANTA FE          Off-Road/Pick-up  Diesel              -              14
Skoda Karoq               Off-Road/Pick-up  Diesel              Front          13
Fiat 500X                 Off-Road/Pick-up  Benzine             4WD            13
Renault Arkana            Off-Road/Pick-up  Benzine             Front          13
Opel Mokka                Off-Road/Pick-up  Diesel              -              12
Nissan Qashqai            Off-Road/Pick-up  Diesel              4WD            12
Ford EcoSport             Off-Road/Pick-up  Benzine             Front          12
Dacia Duster              Off-Road/Pick-up  Liquid/Natural Gas  Front          12
SEAT Arona                Off-Road/Pick-up  Diesel              -              12
Opel Grandland            Off-Road/Pick-up  Benzine             -              12
Ford Mustang Mach-E       Off-Road/Pick-up  Electric            4WD            12
Mercedes-Benz GLC 63 AMG  Off-Road/Pick-up  Benzine             4WD            12
Hyundai TUCSON            Off-Road/Pick-up  Diesel              4WD            12
Nissan X-Trail            Off-Road/Pick-up  Diesel              Front          11
Hyundai BAYON             Off-Road/Pick-up  Benzine             Front          11
Ford Explorer             Off-Road/Pick-up  Benzine             4WD            11
Skoda Enyaq               Off-Road/Pick-up  Electric            Rear           11
Opel Crossland            Off-Road/Pick-up  Benzine             -              11
Opel Grandland X          Off-Road/Pick-up  Diesel              Front          10
Mercedes-Benz GLC 43 AMG  Off-Road/Pick-up  Benzine             4WD            10
Peugeot 5008              Off-Road/Pick-up  Benzine             -              10
                                                                Front          10
Mercedes-Benz GLE 350     Off-Road/Pick-up  Diesel              4WD            10
Renault Captur            Off-Road/Pick-up  Diesel              -              10
SEAT Arona                Off-Road/Pick-up  Liquid/Natural Gas  Front          10
Nissan X-Trail            Off-Road/Pick-up  Benzine             Front          10
Hyundai SANTA FE          Off-Road/Pick-up  Benzine             4WD            10
Peugeot 3008              Off-Road/Pick-up  Diesel              4WD             9
Mercedes-Benz GLE 400     Off-Road/Pick-up  Diesel              4WD             9
Nissan X-Trail            Off-Road/Pick-up  Benzine             -               9
Skoda Kodiaq              Off-Road/Pick-up  Benzine             -               9
Mercedes-Benz GLC 350     Off-Road/Pick-up  Diesel              4WD             9
Fiat Fullback             Off-Road/Pick-up  Diesel              4WD             9
Nissan Juke               Off-Road/Pick-up  Diesel              Front           9
Mercedes-Benz GLC 250     Off-Road/Pick-up  Diesel              4WD             9
Mercedes-Benz ML 350      Off-Road/Pick-up  Diesel              4WD             9
Skoda Karoq               Off-Road/Pick-up  Benzine             4WD             8
Renault Koleos            Off-Road/Pick-up  Diesel              Front           8
Hyundai BAYON             Off-Road/Pick-up  Benzine             -               8
Volvo XC90                Off-Road/Pick-up  Diesel              Front           8
Skoda Yeti                Off-Road/Pick-up  Diesel              4WD             8
Mercedes-Benz GLE 300     Off-Road/Pick-up  Diesel              4WD             8
Ford EcoSport             Off-Road/Pick-up  Benzine             -               8
Opel Mokka X              Off-Road/Pick-up  Benzine             Front           8
Skoda Karoq               Off-Road/Pick-up  Diesel              -               8
Mercedes-Benz G 500       Off-Road/Pick-up  Benzine             4WD             8
Mercedes-Benz G 350       Off-Road/Pick-up  Diesel              4WD             8
Hyundai                   Off-Road/Pick-up  Benzine             Front           7
Opel Mokka                Off-Road/Pick-up  Benzine             4WD             7
SEAT Arona                Off-Road/Pick-up  Liquid/Natural Gas  -               7
Toyota RAV 4              Off-Road/Pick-up  Diesel              4WD             7
Mercedes-Benz ML 63 AMG   Off-Road/Pick-up  Benzine             4WD             7
Opel Grandland            Off-Road/Pick-up  Benzine             Front           7
Toyota RAV 4              Off-Road/Pick-up  Diesel              -               7
Mercedes-Benz GLC 250     Off-Road/Pick-up  Benzine             4WD             7
SEAT Tarraco              Off-Road/Pick-up  Benzine             Front           7
Hyundai KONA              Off-Road/Pick-up  Benzine             4WD             7
Toyota Hilux              Off-Road/Pick-up  Diesel              -               7
Hyundai KONA              Off-Road/Pick-up  Electric            Front           7
Hyundai iX35              Off-Road/Pick-up  Benzine             -               7
Opel Crossland X          Off-Road/Pick-up  Diesel              -               7
Toyota Land Cruiser       Off-Road/Pick-up  Benzine             -               7
Mercedes-Benz GLA 45 AMG  Off-Road/Pick-up  Benzine             4WD             7
Mercedes-Benz GLE 53 AMG  Off-Road/Pick-up  Benzine             4WD             6
Ford Bronco               Off-Road/Pick-up  Benzine             4WD             6
Toyota Highlander         Off-Road/Pick-up  Benzine             4WD             6
Fiat Freemont             Off-Road/Pick-up  Diesel              4WD             6
Mercedes-Benz GLA 200     Off-Road/Pick-up  Benzine             -               6
Volvo XC60                Off-Road/Pick-up  Benzine             Front           6
Toyota Yaris Cross        Off-Road/Pick-up  Benzine             -               6
Mercedes-Benz GLC 300     Off-Road/Pick-up  Diesel              4WD             6
SEAT Tarraco              Off-Road/Pick-up  Benzine             -               6
Mercedes-Benz GLC 220     Off-Road/Pick-up  Diesel              -               6
Volvo XC60                Off-Road/Pick-up  Benzine             -               6
SEAT Tarraco              Off-Road/Pick-up  Diesel              Front           6
Hyundai KONA              Off-Road/Pick-up  Diesel              Front           6
Renault Kadjar            Off-Road/Pick-up  Diesel              4WD             6
Dacia Sandero             Off-Road/Pick-up  Liquid/Natural Gas  -               6
Volvo                     Off-Road/Pick-up  Benzine             4WD             6
Hyundai iX35              Off-Road/Pick-up  Diesel              Front           6
Opel Grandland            Off-Road/Pick-up  Diesel              Front           5
Mercedes-Benz GLS 400     Off-Road/Pick-up  Diesel              4WD             5
Mercedes-Benz GLS 350     Off-Road/Pick-up  Diesel              4WD             5
Mercedes-Benz GLE 63 AMG  Off-Road/Pick-up  Benzine             4WD             5
Mercedes-Benz ML 500      Off-Road/Pick-up  Benzine             4WD             5
Mercedes-Benz GLC 400     Off-Road/Pick-up  Diesel              4WD             5
Mercedes-Benz GLA 200     Off-Road/Pick-up  Diesel              Front           5
Fiat 500L                 Off-Road/Pick-up  Benzine             Front           5
Toyota Yaris Cross        Off-Road/Pick-up  Benzine             4WD             5
Ford F 150                Off-Road/Pick-up  Benzine             4WD             5
Toyota FJ Cruiser         Off-Road/Pick-up  Benzine             -               5
Skoda Kodiaq              Off-Road/Pick-up  Benzine             Front           5
Hyundai iX35              Off-Road/Pick-up  Diesel              4WD             5
Mercedes-Benz EQB 350     Off-Road/Pick-up  Electric            4WD             5
Mercedes-Benz G 400       Off-Road/Pick-up  Diesel              4WD             5
SEAT Tarraco              Off-Road/Pick-up  Diesel              -               5
Mercedes-Benz GLC 200     Off-Road/Pick-up  Benzine             4WD             5
Renault                   Off-Road/Pick-up  Benzine             Front           5
Mercedes-Benz GLA 220     Off-Road/Pick-up  Diesel              -               5
Nissan Juke               Off-Road/Pick-up  Benzine             4WD             5
Mercedes-Benz GLA 220     Off-Road/Pick-up  Diesel              4WD             5
Opel Mokka                Off-Road/Pick-up  Diesel              4WD             4
Renault Alaskan           Off-Road/Pick-up  Diesel              4WD             4
Skoda Enyaq               Off-Road/Pick-up  Electric            -               4
SEAT Tarraco              Off-Road/Pick-up  Benzine             4WD             4
Peugeot 508               Off-Road/Pick-up  Diesel              4WD             4
Toyota Land Cruiser       Off-Road/Pick-up  Benzine             4WD             4
Toyota RAV 4              Off-Road/Pick-up  Electric            -               4
Opel Mokka X              Off-Road/Pick-up  Diesel              -               4
Nissan Patrol             Off-Road/Pick-up  Diesel              4WD             4
Volvo C40                 Off-Road/Pick-up  Benzine             4WD             4
Volvo V60 Cross Country   Off-Road/Pick-up  Diesel              Front           4
Volvo V90 Cross Country   Off-Road/Pick-up  Diesel              4WD             4
Opel Mokka                Off-Road/Pick-up  Diesel              Front           4
Renault Captur            Off-Road/Pick-up  Liquid/Natural Gas  Front           4
Volvo XC90                Off-Road/Pick-up  Electric            -               4
Mercedes-Benz GLE 580     Off-Road/Pick-up  Benzine             4WD             4
Mercedes-Benz GLS 400     Off-Road/Pick-up  Benzine             4WD             4
Mercedes-Benz GLB 35 AMG  Off-Road/Pick-up  Benzine             4WD             4
Fiat 500X                 Off-Road/Pick-up  Liquid/Natural Gas  Front           4
Mercedes-Benz G 230       Off-Road/Pick-up  Benzine             4WD             4
Fiat 500                  Off-Road/Pick-up  Benzine             Front           4
Mercedes-Benz G           Off-Road/Pick-up  Diesel              4WD             4
Mercedes-Benz X 250       Off-Road/Pick-up  Diesel              4WD             3
Opel Antara               Off-Road/Pick-up  Diesel              4WD             3
Fiat Panda                Off-Road/Pick-up  Diesel              4WD             3
Mercedes-Benz GLK 250     Off-Road/Pick-up  Diesel              4WD             3
Renault Captur            Off-Road/Pick-up  Liquid/Natural Gas  -               3

### Domain Knowledge About Drivetrain of Some Electric Cars

The **``Škoda Enyaq iV``** is a battery electric compact crossover SUV manufactured by Škoda Auto. It was introduced in September 2020 in Prague, while mass production commenced in November 2020...The Enyaq iV will be available either as **``rear-wheel drive``** or **``all-wheel drive``**, with three different battery capacities and five performance versions...

The **``Hyundai Kona``** is a subcompact crossover SUV (B-segment) produced by the South Korean manufacturer Hyundai. The Kona debuted in June 2017 and the production version was revealed later that year...While it is developed as an urban-oriented crossover SUV, the Kona is available in **``front-wheel-drive``** and **``all-wheel-drive``** variants...

The **``Ford Mustang Mach-E``** is a battery electric compact crossover SUV produced by Ford. The vehicle was introduced on November 17, 2019, and went on sale in December 2020 as a 2021 model...Its Layout is either **``Rear-motor``** with **``rear-wheel drive``** or **``Dual-motor``** with **``all-wheel-drive``**...

This Domain Knowledge demonstrates that the newest car technology breaks through some major trends impacting automotive manufacturing, particularly for electric vehicles. Eventually, this comes up with a new terminology. Therefore, there is a conceptual confusion in the automative sector, since the technology used in the production of electric batteries is different and there is no standardization in terms of concepts yet.

In [ ]:
df["drivetrain"] = df["drivetrain"].replace('-', np.nan)

In [ ]:
fill(df, "make_model", "body_type", "drivetrain", "mode")

COLUMN NAME    :  drivetrain
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  3
--------------------------------
4WD       4321
Front    21492
Rear      2817
Name: drivetrain, dtype: int64

## empty_weight

In [ ]:
first_looking("empty_weight")

COLUMN NAME    :  empty_weight
--------------------------------
per_of_nulls   :  % 37.97
num_of_nulls   :  10872
num_of_uniques :  1218
--------------------------------
NaN         10872
1395.000      233
1055.000      224
1423.000      216
1165.000      200
            ...
1877.000        1
1011.000        1
1069.000        1
983.000         1
1391.000        1
Name: empty_weight, Length: 1219, dtype: int64

In [ ]:
df["empty_weight"].fillna("-", inplace=True)

In [ ]:
df.groupby(["make_model", "body_type", "empty_weight"]).price.describe()

                                           count      mean       std  \
make_model  body_type        empty_weight
Dacia       Compact          1045.0        1.000 19515.000       NaN
                             -             2.000 22389.000   127.279
            Sedan            935.0         1.000  9999.000       NaN
            Station wagon    -             1.000 21799.000       NaN
Dacia Break Station wagon    -             1.000 20500.000       NaN
...                                          ...       ...       ...
Volvo XC90  Off-Road/Pick-up 2395.0        2.000 76930.000     0.000
                             -            72.000 49016.861 19176.635
            Sedan            -             3.000 60366.667 21250.255
            Station wagon    1931.0        2.000 29500.000     0.000
                             2028.0        2.000 36000.000     0.000

                                                min       25%       50%  \
make_model  body_type        empty_weight
Dacia       Compact          1045.0       19515.000 19515.000 19515.000
                             -            22299.000 22344.000 22389.000
            Sedan            935.0         9999.000  9999.000  9999.000
            Station wagon    -            21799.000 21799.000 21799.000
Dacia Break Station wagon    -            20500.000 20500.000 20500.000
...                                             ...       ...       ...
Volvo XC90  Off-Road/Pick-up 2395.0       76930.000 76930.000 76930.000
                             -             7500.000 38865.000 48150.000
            Sedan            -            47700.000 48100.000 48500.000
            Station wagon    1931.0       29500.000 29500.000 29500.000
                             2028.0       36000.000 36000.000 36000.000

                                                75%       max
make_model  body_type        empty_weight
Dacia       Compact          1045.0       19515.000 19515.000
                             -            22434.000 22479.000
            Sedan            935.0         9999.000  9999.000
            Station wagon    -            21799.000 21799.000
Dacia Break Station wagon    -            20500.000 20500.000
...                                             ...       ...
Volvo XC90  Off-Road/Pick-up 2395.0       76930.000 76930.000
                             -            60367.500 83900.000
            Sedan            -            66700.000 84900.000
            Station wagon    1931.0       29500.000 29500.000
                             2028.0       36000.000 36000.000

[7397 rows x 8 columns]

**The ``empty_weight`` of cars changes by their ``make_models`` & ``body_type`` most of the time. So it is more beneficial to decide to fill missing values with mode value of related group.**

In [ ]:
df["empty_weight"].replace("-", np.nan, inplace=True)

In [ ]:
fill(df, "make_model", "body_type", "empty_weight", "mode")

COLUMN NAME    :  empty_weight
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  1218
--------------------------------
75.000       1
347.000      1
375.000      1
473.000      4
474.000      1
            ..
2750.000     1
2900.000     1
3150.000     1
11246.000    1
15590.000    1
Name: empty_weight, Length: 1218, dtype: int64

## previous_owner

In [ ]:
first_looking("previous_owner")

COLUMN NAME    :  previous_owner
--------------------------------
per_of_nulls   :  % 51.05
num_of_nulls   :  14615
num_of_uniques :  13
--------------------------------
NaN       14615
1.000      9746
2.000      3221
3.000       699
4.000       184
5.000        69
6.000        37
7.000        22
8.000        16
9.000        14
12.000        3
10.000        2
14.000        1
13.000        1
Name: previous_owner, dtype: int64

In [ ]:
df["previous_owner"].fillna("-", inplace = True)

In [ ]:
df.groupby(['make_model', 'body_type', 'age', 'previous_owner']).price.describe()

                                                    count      mean      std  \
make_model  body_type        age    previous_owner
Dacia       Compact          0.000  1.0             2.000 22389.000  127.279
                             1.000  1.0             1.000 19515.000      NaN
            Sedan            47.000 -               1.000  9999.000      NaN
            Station wagon    0.000  1.0             1.000 21799.000      NaN
Dacia Break Station wagon    0.000  -               1.000 20500.000      NaN
...                                                   ...       ...      ...
Volvo XC90  Off-Road/Pick-up 18.000 -               2.000  6799.000    0.000
            Sedan            1.000  -               1.000 84900.000      NaN
                             3.000  -               1.000 48500.000      NaN
                             4.000  -               1.000 47700.000      NaN
            Station wagon    6.000  1.0             4.000 32750.000 3752.777

                                                         min       25%  \
make_model  body_type        age    previous_owner
Dacia       Compact          0.000  1.0            22299.000 22344.000
                             1.000  1.0            19515.000 19515.000
            Sedan            47.000 -               9999.000  9999.000
            Station wagon    0.000  1.0            21799.000 21799.000
Dacia Break Station wagon    0.000  -              20500.000 20500.000
...                                                      ...       ...
Volvo XC90  Off-Road/Pick-up 18.000 -               6799.000  6799.000
            Sedan            1.000  -              84900.000 84900.000
                             3.000  -              48500.000 48500.000
                             4.000  -              47700.000 47700.000
            Station wagon    6.000  1.0            29500.000 29500.000

                                                         50%       75%  \
make_model  body_type        age    previous_owner
Dacia       Compact          0.000  1.0            22389.000 22434.000
                             1.000  1.0            19515.000 19515.000
            Sedan            47.000 -               9999.000  9999.000
            Station wagon    0.000  1.0            21799.000 21799.000
Dacia Break Station wagon    0.000  -              20500.000 20500.000
...                                                      ...       ...
Volvo XC90  Off-Road/Pick-up 18.000 -               6799.000  6799.000
            Sedan            1.000  -              84900.000 84900.000
                             3.000  -              48500.000 48500.000
                             4.000  -              47700.000 47700.000
            Station wagon    6.000  1.0            32750.000 36000.000

                                                         max
make_model  body_type        age    previous_owner
Dacia       Compact          0.000  1.0            22479.000
                             1.000  1.0            19515.000
            Sedan            47.000 -               9999.000
            Station wagon    0.000  1.0            21799.000
Dacia Break Station wagon    0.000  -              20500.000
...                                                      ...
Volvo XC90  Off-Road/Pick-up 18.000 -               6799.000
            Sedan            1.000  -              84900.000
                             3.000  -              48500.000
                             4.000  -              47700.000
            Station wagon    6.000  1.0            36000.000

[8487 rows x 8 columns]

In [ ]:
df.groupby(['make_model', 'body_type', 'age', 'previous_owner']).mileage.describe()

                                                    count       mean      std  \
make_model  body_type        age    previous_owner
Dacia       Compact          0.000  1.0             2.000    110.000    0.000
                             1.000  1.0             1.000   2376.000      NaN
            Sedan            47.000 -               1.000  59098.000      NaN
            Station wagon    0.000  1.0             1.000   2000.000      NaN
Dacia Break Station wagon    0.000  -               1.000    999.000      NaN
...                                                   ...        ...      ...
Volvo XC90  Off-Road/Pick-up 18.000 -               2.000 237102.000    0.000
            Sedan            1.000  -               1.000  20635.000      NaN
                             3.000  -               1.000  68940.000      NaN
                             4.000  -               1.000  86709.000      NaN
            Station wagon    6.000  1.0             4.000 146775.000 3723.909

                                                          min        25%  \
make_model  body_type        age    previous_owner
Dacia       Compact          0.000  1.0               110.000    110.000
                             1.000  1.0              2376.000   2376.000
            Sedan            47.000 -               59098.000  59098.000
            Station wagon    0.000  1.0              2000.000   2000.000
Dacia Break Station wagon    0.000  -                 999.000    999.000
...                                                       ...        ...
Volvo XC90  Off-Road/Pick-up 18.000 -              237102.000 237102.000
            Sedan            1.000  -               20635.000  20635.000
                             3.000  -               68940.000  68940.000
                             4.000  -               86709.000  86709.000
            Station wagon    6.000  1.0            143550.000 143550.000

                                                          50%        75%  \
make_model  body_type        age    previous_owner
Dacia       Compact          0.000  1.0               110.000    110.000
                             1.000  1.0              2376.000   2376.000
            Sedan            47.000 -               59098.000  59098.000
            Station wagon    0.000  1.0              2000.000   2000.000
Dacia Break Station wagon    0.000  -                 999.000    999.000
...                                                       ...        ...
Volvo XC90  Off-Road/Pick-up 18.000 -              237102.000 237102.000
            Sedan            1.000  -               20635.000  20635.000
                             3.000  -               68940.000  68940.000
                             4.000  -               86709.000  86709.000
            Station wagon    6.000  1.0            146775.000 150000.000

                                                          max
make_model  body_type        age    previous_owner
Dacia       Compact          0.000  1.0               110.000
                             1.000  1.0              2376.000
            Sedan            47.000 -               59098.000
            Station wagon    0.000  1.0              2000.000
Dacia Break Station wagon    0.000  -                 999.000
...                                                       ...
Volvo XC90  Off-Road/Pick-up 18.000 -              237102.000
            Sedan            1.000  -               20635.000
                             3.000  -               68940.000
                             4.000  -               86709.000
            Station wagon    6.000  1.0            150000.000

[8487 rows x 8 columns]

In [ ]:
df["previous_owner"].replace("-", np.nan, inplace=True)

In [ ]:
def fill_prop(df, group_col, col_name):
    '''Fills the missing values with "ffill and bfill method" according to single-stage grouping'''
    
    for group in df[group_col].unique():
        cond = df[group_col] == group
        df.loc[cond, col_name] = df.loc[cond, col_name].fillna(method="ffill").fillna(method="bfill")
    
    df[col_name] = df[col_name].fillna(method="ffill").fillna(method="bfill")
    
    print("column name    : ", col_name)
    print("--------------------------------")
    print("per_of_nulls   : ", "%", round(df[col_name].isnull().sum()*100 / df.shape[0], 2))
    print("num_of_nulls   : ", df[col_name].isnull().sum())
    print("num_of_uniques : ", df[col_name].nunique())
    print("--------------------------------")
    print(df[col_name].value_counts(dropna = False))

In [ ]:
fill_prop(df, "age", "previous_owner")

column name    :  previous_owner
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  13
--------------------------------
1.000     18703
2.000      7202
3.000      1756
4.000       500
5.000       206
6.000       100
8.000        71
7.000        57
9.000        25
12.000        6
10.000        2
14.000        1
13.000        1
Name: previous_owner, dtype: int64

## energy_efficiency_class

In [ ]:
first_looking("energy_efficiency_class")

COLUMN NAME    :  energy_efficiency_class
--------------------------------
per_of_nulls   :  % 72.74
num_of_nulls   :  20826
num_of_uniques :  2
--------------------------------
NaN            20826
efficient       5308
unefficient     2496
Name: energy_efficiency_class, dtype: int64

In [ ]:
df["energy_efficiency_class"].fillna("-", inplace = True)

In [ ]:
df.groupby(['energy_efficiency_class', 'make_model', 'body_type', 'age']).mileage.describe()

                                                              count  \
energy_efficiency_class make_model   body_type        age
-                       Dacia        Sedan            47.000  1.000
                        Dacia Break  Station wagon    0.000   1.000
                        Dacia Dokker Compact          4.000   1.000
                                     Off-Road/Pick-up 4.000   2.000
                                     Sedan            5.000   1.000
...                                                             ...
unefficient             Volvo XC70   Station wagon    14.000  2.000
                        Volvo XC90   Off-Road/Pick-up 1.000   2.000
                                                      2.000   4.000
                                                      3.000   6.000
                                                      14.000  4.000

                                                                   mean  \
energy_efficiency_class make_model   body_type        age
-                       Dacia        Sedan            47.000  59098.000
                        Dacia Break  Station wagon    0.000     999.000
                        Dacia Dokker Compact          4.000  141100.000
                                     Off-Road/Pick-up 4.000  100000.000
                                     Sedan            5.000  149000.000
...                                                                 ...
unefficient             Volvo XC70   Station wagon    14.000 353453.000
                        Volvo XC90   Off-Road/Pick-up 1.000    1494.000
                                                      2.000   33315.500
                                                      3.000   47009.333
                                                      14.000 271343.500

                                                                   std  \
energy_efficiency_class make_model   body_type        age
-                       Dacia        Sedan            47.000       NaN
                        Dacia Break  Station wagon    0.000        NaN
                        Dacia Dokker Compact          4.000        NaN
                                     Off-Road/Pick-up 4.000      0.000
                                     Sedan            5.000        NaN
...                                                                ...
unefficient             Volvo XC70   Station wagon    14.000     0.000
                        Volvo XC90   Off-Road/Pick-up 1.000      0.000
                                                      2.000  10404.429
                                                      3.000  13221.929
                                                      14.000 21542.671

                                                                    min  \
energy_efficiency_class make_model   body_type        age
-                       Dacia        Sedan            47.000  59098.000
                        Dacia Break  Station wagon    0.000     999.000
                        Dacia Dokker Compact          4.000  141100.000
                                     Off-Road/Pick-up 4.000  100000.000
                                     Sedan            5.000  149000.000
...                                                                 ...
unefficient             Volvo XC70   Station wagon    14.000 353453.000
                        Volvo XC90   Off-Road/Pick-up 1.000    1494.000
                                                      2.000   24305.000
                                                      3.000   30028.000
                                                      14.000 252687.000

                                                                    25%  \
energy_efficiency_class make_model   body_type        age
-                       Dacia        Sedan            47.000  59098.000
                        Dacia Break  Station wagon    0.000     999.000
                        Dacia Dokker Compact          4.000  141100.000
                                     Off-Road/Pick-up 4.000  100000.000
                                     Sedan            5.000  149000.000
...                                                                 ...
unefficient             Volvo XC70   Station wagon    14.000 353453.000
                        Volvo XC90   Off-Road/Pick-up 1.000    1494.000
                                                      2.000   24305.000
                                                      3.000   36021.000
                                                      14.000 252687.000

                                                                    50%  \
energy_efficiency_class make_model   body_type        age
-                       Dacia        Sedan            47.000  59098.000
                        Dacia Break  Station wagon    0.000     999.000
                        Dacia Dokker Compact          4.000  141100.000
                                     Off-Road/Pick-up 4.000  100000.000
                                     Sedan            5.000  149000.000
...                                                                 ...
unefficient             Volvo XC70   Station wagon    14.000 353453.000
                        Volvo XC90   Off-Road/Pick-up 1.000    1494.000
                                                      2.000   33315.500
                                                      3.000   54000.000
                                                      14.000 271343.500

                                                                    75%  \
energy_efficiency_class make_model   body_type        age
-                       Dacia        Sedan            47.000  59098.000
                        Dacia Break  Station wagon    0.000     999.000
                        Dacia Dokker Compact          4.000  141100.000
                                     Off-Road/Pick-up 4.000  100000.000
                                     Sedan            5.000  149000.000
...                                                                 ...
unefficient             Volvo XC70   Station wagon    14.000 353453.000
                        Volvo XC90   Off-Road/Pick-up 1.000    1494.000
                                                      2.000   42326.000
                                                      3.000   56250.000
                                                      14.000 290000.000

                                                                    max
energy_efficiency_class make_model   body_type        age
-                       Dacia        Sedan            47.000  59098.000
                        Dacia Break  Station wagon    0.000     999.000
                        Dacia Dokker Compact          4.000  141100.000
                                     Off-Road/Pick-up 4.000  100000.000
                                     Sedan            5.000  149000.000
...                                                                 ...
unefficient             Volvo XC70   Station wagon    14.000 353453.000
                        Volvo XC90   Off-Road/Pick-up 1.000    1494.000
                                                      2.000   42326.000
                                                      3.000   57000.000
                                                      14.000 290000.000

[6833 rows x 8 columns]

In [ ]:
# df.loc[(df.energy_efficiency_class == "-") & (df.fuel_type == "Electric")][["make_model", "age", "body_type", "gearbox", "drivetrain", "gears", "engine_size", "fuel_type", "co_emissions", "cons_avg"]]
df.loc[(df.energy_efficiency_class == "-")][["make_model", "age", "body_type", "gearbox", "drivetrain", "gears", "engine_size", "fuel_type", "co_emissions", "cons_avg"]]

,make_model,age,body_type,gearbox,drivetrain,gears,engine_size,fuel_type,co_emissions,cons_avg
0,Mercedes-Benz A 160,6.000,Compact,Manual,Front,5.000,1595.000,Diesel,98.000,3.800
1,Mercedes-Benz EQE 350,0.000,Compact,Automatic,4WD,9.000,1.000,Electric,0.000,2.359
2,Mercedes-Benz A 45 AMG,2.000,Compact,Automatic,4WD,8.000,1991.000,Benzine,162.000,8.400
3,Mercedes-Benz A 35 AMG,2.000,Compact,Automatic,4WD,7.000,1991.000,Benzine,169.000,7.300
4,Mercedes-Benz A 45 AMG,7.000,Compact,Automatic,4WD,7.000,2143.000,Diesel,162.000,4.900
...,...,...,...,...,...,...,...,...,...,...
28625,Volvo S90,3.000,Sedan,Automatic,4WD,8.000,1969.000,Diesel,127.000,2.000
28626,Volvo S40,18.000,Sedan,Automatic,Front,5.000,2435.000,Benzine,217.000,9.100
28627,Volvo C30,11.000,Sedan,Manual,Front,6.000,1560.000,Diesel,99.000,3.800
28628,Volvo S90,5.000,Sedan,Automatic,4WD,8.000,1969.000,Benzine,149.000,6.500
28629,Volvo S80,20.000,Sedan,Automatic,Front,6.000,2922.000,Benzine,251.000,10.400

In [ ]:
df.loc[(df.energy_efficiency_class == "-")]["age"].value_counts()

4.000       2669
3.000       2332
5.000       1999
2.000       1492
1.000       1447
6.000       1248
7.000       1084
0.000       1082
8.000        823
9.000        630
11.000       603
10.000       594
12.000       525
15.000       484
14.000       415
13.000       407
16.000       389
17.000       277
18.000       244
19.000       208
21.000       189
20.000       183
22.000       159
23.000       140
24.000        89
28.000        79
25.000        79
27.000        78
26.000        69
31.000        62
30.000        59
32.000        54
29.000        54
56.000        40
55.000        34
57.000        32
34.000        32
49.000        29
50.000        28
54.000        27
35.000        26
44.000        23
36.000        22
33.000        20
52.000        19
51.000        18
37.000        18
53.000        17
43.000        17
39.000        16
47.000        14
45.000        13
58.000        11
46.000        11
40.000        11
38.000        10
48.000         9
41.000         9
59.000         9
60.000         8
61.000         7
67.000         6
42.000         6
68.000         4
64.000         4
65.000         4
62.000         4
90.000         3
63.000         2
85.000         2
69.000         2
92.000         2
70.000         2
-3.000         1
89.000         1
76.000         1
66.000         1
-1.000         1
93.000         1
72.000         1
94.000         1
-180.000       1
Name: age, dtype: int64

In [ ]:
df["energy_efficiency_class"].replace("-", np.nan, inplace=True)

In [ ]:
fill(df, "make_model", "age", "energy_efficiency_class", "mode")

COLUMN NAME    :  energy_efficiency_class
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  2
--------------------------------
efficient      18613
unefficient    10017
Name: energy_efficiency_class, dtype: int64

## upholstery

In [ ]:
first_looking("upholstery")

COLUMN NAME    :  upholstery
--------------------------------
per_of_nulls   :  % 35.0
num_of_nulls   :  10020
num_of_uniques :  6
--------------------------------
NaN             10020
Cloth            8736
Full leather     5439
Part leather     2835
alcantara         764
Other             628
Velour            208
Name: upholstery, dtype: int64

### Domain Knowledge ABout Velour & Alcantara

**``Velour``** is a traditional fabric cloth previously used on OE automotive seating. It features a durable construction and is finished with a 3.5mm foam and denier backing for ease of fabrication. Velour insert cloth is versatile and can be used on other general purpose upholstery applications.

**``Alcantara``** is an Italian-made synthetic fabric that is durable and feels like suede. Alcantara has a soft, suede-like microfiber pile and is renowned for its unmatched durability. Alcantara is commonly used in car interiors such as Alcantara car seats or Alcantara steering wheel covers.

In [ ]:
df["upholstery"].replace(["Velour", "alcantara", "Part leather", "Full leather"],
                         ["Cloth", "Part/Full Leather", "Part/Full Leather", "Part/Full Leather"], inplace=True)

df["upholstery"].replace("Other", np.nan, inplace=True)

df["upholstery"].value_counts(dropna=False)

NaN                  10648
Part/Full Leather     9038
Cloth                 8944
Name: upholstery, dtype: int64

In [ ]:
df["upholstery"].fillna("-", inplace=True)

In [ ]:
df.groupby(["make_model", "body_type", "age", "upholstery"]).price.describe()

                                                       count      mean  \
make_model  body_type        age    upholstery
Dacia       Compact          0.000  Cloth              2.000 22389.000
                             1.000  Part/Full Leather  1.000 19515.000
            Sedan            47.000 Cloth              1.000  9999.000
            Station wagon    0.000  Cloth              1.000 21799.000
Dacia Break Station wagon    0.000  -                  1.000 20500.000
...                                                      ...       ...
Volvo XC90  Off-Road/Pick-up 18.000 -                  2.000  6799.000
            Sedan            1.000  Part/Full Leather  1.000 84900.000
                             3.000  -                  1.000 48500.000
                             4.000  -                  1.000 47700.000
            Station wagon    6.000  Part/Full Leather  4.000 32750.000

                                                           std       min  \
make_model  body_type        age    upholstery
Dacia       Compact          0.000  Cloth              127.279 22299.000
                             1.000  Part/Full Leather      NaN 19515.000
            Sedan            47.000 Cloth                  NaN  9999.000
            Station wagon    0.000  Cloth                  NaN 21799.000
Dacia Break Station wagon    0.000  -                      NaN 20500.000
...                                                        ...       ...
Volvo XC90  Off-Road/Pick-up 18.000 -                    0.000  6799.000
            Sedan            1.000  Part/Full Leather      NaN 84900.000
                             3.000  -                      NaN 48500.000
                             4.000  -                      NaN 47700.000
            Station wagon    6.000  Part/Full Leather 3752.777 29500.000

                                                            25%       50%  \
make_model  body_type        age    upholstery
Dacia       Compact          0.000  Cloth             22344.000 22389.000
                             1.000  Part/Full Leather 19515.000 19515.000
            Sedan            47.000 Cloth              9999.000  9999.000
            Station wagon    0.000  Cloth             21799.000 21799.000
Dacia Break Station wagon    0.000  -                 20500.000 20500.000
...                                                         ...       ...
Volvo XC90  Off-Road/Pick-up 18.000 -                  6799.000  6799.000
            Sedan            1.000  Part/Full Leather 84900.000 84900.000
                             3.000  -                 48500.000 48500.000
                             4.000  -                 47700.000 47700.000
            Station wagon    6.000  Part/Full Leather 29500.000 32750.000

                                                            75%       max
make_model  body_type        age    upholstery
Dacia       Compact          0.000  Cloth             22434.000 22479.000
                             1.000  Part/Full Leather 19515.000 19515.000
            Sedan            47.000 Cloth              9999.000  9999.000
            Station wagon    0.000  Cloth             21799.000 21799.000
Dacia Break Station wagon    0.000  -                 20500.000 20500.000
...                                                         ...       ...
Volvo XC90  Off-Road/Pick-up 18.000 -                  6799.000  6799.000
            Sedan            1.000  Part/Full Leather 84900.000 84900.000
                             3.000  -                 48500.000 48500.000
                             4.000  -                 47700.000 47700.000
            Station wagon    6.000  Part/Full Leather 36000.000 36000.000

[8074 rows x 8 columns]

**Since it was NOT detected a clear relationship among features ffill/bfill methods to fill missing values would be prefered to maintain the current proportionality.**

In [ ]:
df["upholstery"].replace("-", np.nan, inplace=True)

In [ ]:
fill(df, "make_model", "body_type", "upholstery", "ffill")

COLUMN NAME    :  upholstery
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  2
--------------------------------
Cloth                15063
Part/Full Leather    13567
Name: upholstery, dtype: int64

## comfort_&_convenience

In [ ]:
first_looking("comfort_&_convenience")

COLUMN NAME    :  comfort_&_convenience
--------------------------------
per_of_nulls   :  % 11.17
num_of_nulls   :  3197
num_of_uniques :  14438
--------------------------------
NaN                                                                                                                                                                                                                                                                                                                                                                                                            3197
Air conditioning, Automatic climate control, Electrical side mirrors, Multi-function steering wheel, Power windows                                                                                                                                                                                                                                                                                              244
Air conditioning, Automatic climate control, Cruise control                                                                                                                                                                                                                                                                                                                                                     171
Air conditioning, Automatic climate control, Cruise control, Electrical side mirrors, Multi-function steering wheel, Power windows                                                                                                                                                                                                                                                                              168
Air conditioning                                                                                                                                                                                                                                                                                                                                                                                                157
                                                                                                                                                                                                                                                                                                                                                                                                               ...
Armrest, Automatic climate control, 2 zones, Cruise control, Fold flat passenger seat, Hill Holder, Leather steering wheel, Light sensor, Lumbar support, Multi-function steering wheel, Navigation system, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Split rear seats, Start-stop system                                                                                     1
Air conditioning, Armrest, Automatic climate control, Cruise control, Electric tailgate, Electrical side mirrors, Hill Holder, Keyless central door lock, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating                                               1
Armrest, Automatic climate control, 2 zones, Cruise control, Electrical side mirrors, Fold flat passenger seat, Hill Holder, Leather steering wheel, Light sensor, Lumbar support, Multi-function steering wheel, Navigation system, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Split rear seats, Start-stop system, Tinted windows       1
Armrest, Automatic climate control, 2 zones, Cruise control, Electrical side mirrors, Hill Holder, Keyless central door lock, Leather steering wheel, Light sensor, Multi-function steering wheel, Parking assist system camera, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Split rear seats, Start-stop system, Tinted windows           1
Air conditioning, Armrest, Cruise control, Electrical side mirrors, Leather steering wheel, Lumbar support, Multi-function steering wheel, Navigation system, Power windows, Seat heating, Tinted windows                                                                                                                                                                                                         1
Name: comfort_&_convenience, Length: 14439, dtype: int64

In [ ]:
fill(df, "make_model", "body_type", "comfort_&_convenience", "mode")

COLUMN NAME    :  comfort_&_convenience
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  14438
--------------------------------
360° camera                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    4
360° camera, Air conditioning, Air suspension, Armrest, Automatic climate control, 2 zones, Auxiliary heating, Cruise control, Electric tailgate, Electrical side mirrors, Electrically adjustable seats, Heads-up display, Heated steering wheel, Hill Holder, Keyless central door lock, Leather steering wheel, Light sensor, Lumbar support, Multi-function steering wheel, Navigation system, Panorama roof, Parking assist system camera, Parking assist system self-steering, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Start-stop system, Sunroof                                             1
360° camera, Air conditioning, Air suspension, Armrest, Automatic climate control, 2 zones, Auxiliary heating, Cruise control, Electric tailgate, Electrical side mirrors, Electrically adjustable seats, Heads-up display, Heated steering wheel, Hill Holder, Leather steering wheel, Light sensor, Lumbar support, Massage seats, Multi-function steering wheel, Navigation system, Panorama roof, Parking assist system camera, Parking assist system self-steering, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Seat ventilation, Split rear seats, Start-stop system, Sunroof, Tinted windows     3
360° camera, Air conditioning, Air suspension, Armrest, Automatic climate control, 2 zones, Auxiliary heating, Cruise control, Electric tailgate, Electrical side mirrors, Electrically adjustable seats, Heads-up display, Hill Holder, Keyless central door lock, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Panorama roof, Parking assist system camera, Parking assist system self-steering, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Seat ventilation, Start-stop system, Sunroof                                                                  1
360° camera, Air conditioning, Air suspension, Armrest, Automatic climate control, 2 zones, Auxiliary heating, Cruise control, Electric tailgate, Electrical side mirrors, Electrically adjustable seats, Hill Holder, Keyless central door lock, Leather steering wheel, Light sensor, Lumbar support, Multi-function steering wheel, Navigation system, Panorama roof, Parking assist system camera, Parking assist system self-steering, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Seat ventilation, Split rear seats, Start-stop system, Sunroof, Tinted windows                                  1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ..
Sunroof                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       19
Sunroof, Tinted windows                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
Sunroof, Wind deflector                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
Tinted windows                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                59
Wind deflector                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
Name: comfort_&_convenience, Length: 14438, dtype: int64

In [ ]:
# If you want to see more, full string for each row/observation, use the following
# pd.set_option('display.max_colwidth', -1)

# df['comfort_&_convenience']

**Let us define car ``"Comfort & Conveniance Packages"``**

In [ ]:
premium = ["Electrical side mirrors", "Parking assist", "Air conditioning", "Hill Holder", "Power windows"]
premium_plus = ["Multi-function", "Navigation ", "Keyless central door lock", "Heads-up", "Massage seats", "heating", "Automatic climate control", "Heated"]

comfort_package = df['comfort_&_convenience'].apply(lambda sentence: "Premium Plus" if all(word in sentence for word in premium_plus) else ("Premium" if all(word in sentence for word in premium) else "Standard"))
comfort_package.value_counts()

Standard        19707
Premium          8829
Premium Plus       94
Name: comfort_&_convenience, dtype: int64

**Let us assign each car to related ``"Comfort & Conveniance Packages"`` defined above:**

In [ ]:
# # To see maximum column width
# pd.set_option('display.max_colwidth', None)

# # To reset maximum column width OR all options
# pd.reset_option('display.max_colwidth', silent=True)
# pd.reset_option('^display.', silent=True)
# reset_option('all')

premium = ["Electrical side mirrors", "Parking assist", "Air conditioning", "Hill Holder", "Power windows"]
premium_plus = ["Multi-function", "Navigation ", "Keyless central door lock", "Heads-up", "Massage seats", "heating", "Automatic climate control", "Heated"]

df['comfort_&_convenience_Package'] = df['comfort_&_convenience'].apply(lambda sentence: "Premium Plus" if all(word in sentence for word in premium_plus) else ("Premium" if all(word in sentence for word in premium) else "Standard"))
df

,make_model,make,location,price,body_type,type,doors,warranty,mileage,gearbox,fuel_type,seller,seats,engine_size,gears,co_emissions,drivetrain,comfort_&_convenience,entertainment_&_media,safety_&_security,extras,empty_weight,full_service_history,upholstery,previous_owner,energy_efficiency_class,age,power_kW,cons_avg,comfort_&_convenience_Package
0,Mercedes-Benz A 160,Mercedes-Benz,"P.I. EL PALMAR C/FORJA 6, 11500 PUERTO DE SAN...",16950.000,Compact,Used,5.000,Yes,120200.000,Manual,Diesel,Dealer,5.000,1595.000,5.000,98.000,Front,"Air conditioning, Armrest, Automatic climate c...",NaN,NaN,NaN,1270.000,No,Cloth,2.000,efficient,6.000,75.000,3.800,Standard
1,Mercedes-Benz EQE 350,Mercedes-Benz,"APARTADO DE CORREOS 1032, 26140 LOGROÑO, ES",80900.000,Compact,Pre-registered,4.000,Yes,5000.000,Automatic,Electric,Dealer,5.000,1.000,9.000,0.000,4WD,"Air conditioning, Air suspension, Armrest, Aut...",NaN,NaN,NaN,2355.000,No,Part/Full Leather,1.000,efficient,0.000,215.000,2.359,Premium
2,Mercedes-Benz A 45 AMG,Mercedes-Benz,"PORT. TARRACO, MOLL DE LLEVANT, Nº 5, LOC. 6-8...",69900.000,Compact,Used,5.000,Yes,18900.000,Automatic,Benzine,Dealer,5.000,1991.000,8.000,162.000,4WD,"Air conditioning, Electrical side mirrors, Mul...",NaN,NaN,NaN,1555.000,No,Part/Full Leather,2.000,unefficient,2.000,310.000,8.400,Standard
3,Mercedes-Benz A 35 AMG,Mercedes-Benz,"Carrer de Provença, 31 Local, 8029 BARCELONA, ES",46990.000,Compact,Used,5.000,Yes,18995.000,Automatic,Benzine,Dealer,5.000,1991.000,7.000,169.000,4WD,"Air conditioning, Automatic climate control, P...",USB,"ABS, Central door lock, Driver-side airbag, El...",Sport seats,1455.000,No,Part/Full Leather,2.000,unefficient,2.000,225.000,7.300,Standard
4,Mercedes-Benz A 45 AMG,Mercedes-Benz,"CARRIL ARAGONES 4, 30007 CASILLAS, ES",16800.000,Compact,Used,5.000,Yes,197000.000,Automatic,Diesel,Dealer,5.000,2143.000,7.000,162.000,4WD,"Air conditioning, Electrical side mirrors, Mul...","Bluetooth, CD player, MP3, USB","ABS, Central door lock, Driver-side airbag, El...",NaN,1545.000,No,Part/Full Leather,2.000,unefficient,7.000,100.000,4.900,Standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28625,Volvo S90,Volvo,"HERMANOS LUMIERE Nº16, 29004 MALAGA, ES",37600.000,Sedan,Used,4.000,Yes,40345.000,Automatic,Diesel,Dealer,4.000,1969.000,8.000,127.000,4WD,"Air conditioning, Automatic climate control, M...","Bluetooth, USB","ABS, Central door lock, Driver-side airbag, El...",Alloy wheels,2077.000,No,Part/Full Leather,2.000,efficient,3.000,288.000,2.000,Standard
28626,Volvo S40,Volvo,"Stobbeweg 6, 2461 EX TER AAR, NL",5499.000,Sedan,Used,4.000,No,145000.000,Automatic,Benzine,Dealer,5.000,2435.000,5.000,217.000,Front,"Air conditioning, Armrest, Automatic climate c...","On-board computer, Radio","ABS, Central door lock, Central door lock with...","Alloy wheels (16""), Trailer hitch",1357.000,Yes,Cloth,3.000,efficient,18.000,125.000,9.100,Standard
28627,Volvo C30,Volvo,"Sur rendez-vous, 5060 Sambreville, BE",7300.000,Sedan,Used,3.000,Yes,96000.000,Manual,Diesel,Dealer,4.000,1560.000,6.000,99.000,Front,"Air conditioning, Armrest, Automatic climate c...","Bluetooth, CD player, Hands-free equipment, MP...","ABS, Alarm system, Central door lock with remo...","Alloy wheels, Automatically dimming interior m...",1356.000,Yes,Cloth,1.000,unefficient,11.000,84.000,3.800,Standard
28628,Volvo S90,Volvo,"Bergambachterstraat 5, 2871 JB SCHOONHOVEN, NL",29900.000,Sedan,Used,4.000,Yes,94343.000,Automatic,Benzine,Dealer,5.000,1969.000,8.000,149.000,4WD,"Air conditioning, Armrest, Automatic climate c...","Android Auto, Apple CarPlay, Bluetooth, Hands-...","Adaptive Cruise Control, Adaptive headlights, ...","Alloy wheels (18""), Automatically dimming inte...",1617.000,Yes,Part/Full Leather,1.000,efficient,5.000,187.000,6.500,Standard
28629,Volvo S80,Volvo,"Lage Ham 106, 5102 AE DONGEN, NL",4440.000,Sedan,Used,4.000,No,230047.000,Automatic,Benzine,Dealer,5.000,2922.000,6.000,251.000,Front,"Air conditioning, Armrest, Cruise control, Ele...",On-board computer,"ABS, Alarm system, Central door lock, Central ...","Alloy wheels, Automatically dimming interior m...",1573.000,No,Part/Full Leather,5.000,unefficient,20.000,147.000,10.400,Standard

In [ ]:
df['comfort_&_convenience_Package'].value_counts(dropna=False)

Standard        19707
Premium          8829
Premium Plus       94
Name: comfort_&_convenience_Package, dtype: int64

In [ ]:
df.shape

(28630, 30)

In [ ]:
df.drop("comfort_&_convenience", axis=1, inplace=True)

In [ ]:
df.shape

(28630, 29)

## entertainment_&_media

In [ ]:
first_looking("entertainment_&_media")

COLUMN NAME    :  entertainment_&_media
--------------------------------
per_of_nulls   :  % 17.42
num_of_nulls   :  4986
num_of_uniques :  1944
--------------------------------
NaN                                                                                                                                                                        4986
Bluetooth, USB                                                                                                                                                              753
Bluetooth                                                                                                                                                                   665
On-board computer                                                                                                                                                           662
CD player, On-board computer, Radio                                                                                                                                         644
                                                                                                                                                                           ...
Android Auto, Apple CarPlay, Bluetooth, Digital cockpit, Digital radio, Induction charging for smartphones, On-board computer, Radio, Sound system, WLAN / WiFi hotspot       1
Bluetooth, CD player, Digital cockpit, Digital radio, Hands-free equipment, Integrated music streaming, On-board computer, Sound system, USB, WLAN / WiFi hotspot             1
Digital cockpit, Digital radio, On-board computer, Radio                                                                                                                      1
Android Auto, Apple CarPlay, Digital radio, On-board computer, Radio, Sound system, USB, WLAN / WiFi hotspot                                                                  1
Hands-free equipment, Integrated music streaming, On-board computer, Radio, USB                                                                                               1
Name: entertainment_&_media, Length: 1945, dtype: int64

In [ ]:
fill(df, "make_model", "body_type", "entertainment_&_media", "mode")

COLUMN NAME    :  entertainment_&_media
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  1944
--------------------------------
Android Auto                                                                                                                                                                                                                                                    3
Android Auto, Apple CarPlay                                                                                                                                                                                                                                     9
Android Auto, Apple CarPlay, Bluetooth                                                                                                                                                                                                                          1
Android Auto, Apple CarPlay, Bluetooth, CD player, Digital cockpit, Digital radio, Hands-free equipment, Induction charging for smartphones, Integrated music streaming, MP3, On-board computer, Radio, Sound system, Television, USB                           1
Android Auto, Apple CarPlay, Bluetooth, CD player, Digital cockpit, Digital radio, Hands-free equipment, Induction charging for smartphones, Integrated music streaming, MP3, On-board computer, Radio, Sound system, Television, USB, WLAN / WiFi hotspot      4
                                                                                                                                                                                                                                                             ...
Sound system                                                                                                                                                                                                                                                   61
Sound system, USB                                                                                                                                                                                                                                               3
Sound system, WLAN / WiFi hotspot                                                                                                                                                                                                                               3
USB                                                                                                                                                                                                                                                           207
WLAN / WiFi hotspot                                                                                                                                                                                                                                             4
Name: entertainment_&_media, Length: 1944, dtype: int64

**Let us define car ``"Entertainment & Media Packages"``**

In [ ]:
media_plus = ["Digital", "Television"]

# media_plus = ["Digital radio", "Hands-free", "Television"]

entertainment_media_package = df['entertainment_&_media'].apply(lambda sentence: "Plus" if any(word in sentence for word in media_plus) else "Standard")
entertainment_media_package.value_counts()

Standard    17751
Plus        10879
Name: entertainment_&_media, dtype: int64

In [ ]:
# media_plus = ["Digital", "Television"]

media_plus = ["Digital radio", "Hands-free", "Television"]

entertainment_media_package = df['entertainment_&_media'].apply(lambda sentence: "Plus" if any(word in sentence for word in media_plus) else "Standard")
entertainment_media_package.value_counts()

Plus        16396
Standard    12234
Name: entertainment_&_media, dtype: int64

**Let us assign each car to related ``"Entertainment & Media Packages"`` defined above:**

In [ ]:
media_plus = ["Digital", "Television"]

df['entertainment_&_media_Package'] = df['entertainment_&_media'].apply(lambda sentence: "Plus" if any(word in sentence for word in media_plus) else "Standard")
df

,make_model,make,location,price,body_type,type,doors,warranty,mileage,gearbox,fuel_type,seller,seats,engine_size,gears,co_emissions,drivetrain,entertainment_&_media,safety_&_security,extras,empty_weight,full_service_history,upholstery,previous_owner,energy_efficiency_class,age,power_kW,cons_avg,comfort_&_convenience_Package,entertainment_&_media_Package
0,Mercedes-Benz A 160,Mercedes-Benz,"P.I. EL PALMAR C/FORJA 6, 11500 PUERTO DE SAN...",16950.000,Compact,Used,5.000,Yes,120200.000,Manual,Diesel,Dealer,5.000,1595.000,5.000,98.000,Front,"Bluetooth, CD player, Radio",NaN,NaN,1270.000,No,Cloth,2.000,efficient,6.000,75.000,3.800,Standard,Standard
1,Mercedes-Benz EQE 350,Mercedes-Benz,"APARTADO DE CORREOS 1032, 26140 LOGROÑO, ES",80900.000,Compact,Pre-registered,4.000,Yes,5000.000,Automatic,Electric,Dealer,5.000,1.000,9.000,0.000,4WD,"Android Auto, Apple CarPlay, Bluetooth, Digita...",NaN,NaN,2355.000,No,Part/Full Leather,1.000,efficient,0.000,215.000,2.359,Premium,Plus
2,Mercedes-Benz A 45 AMG,Mercedes-Benz,"PORT. TARRACO, MOLL DE LLEVANT, Nº 5, LOC. 6-8...",69900.000,Compact,Used,5.000,Yes,18900.000,Automatic,Benzine,Dealer,5.000,1991.000,8.000,162.000,4WD,"Bluetooth, CD player, MP3, USB",NaN,NaN,1555.000,No,Part/Full Leather,2.000,unefficient,2.000,310.000,8.400,Standard,Standard
3,Mercedes-Benz A 35 AMG,Mercedes-Benz,"Carrer de Provença, 31 Local, 8029 BARCELONA, ES",46990.000,Compact,Used,5.000,Yes,18995.000,Automatic,Benzine,Dealer,5.000,1991.000,7.000,169.000,4WD,USB,"ABS, Central door lock, Driver-side airbag, El...",Sport seats,1455.000,No,Part/Full Leather,2.000,unefficient,2.000,225.000,7.300,Standard,Standard
4,Mercedes-Benz A 45 AMG,Mercedes-Benz,"CARRIL ARAGONES 4, 30007 CASILLAS, ES",16800.000,Compact,Used,5.000,Yes,197000.000,Automatic,Diesel,Dealer,5.000,2143.000,7.000,162.000,4WD,"Bluetooth, CD player, MP3, USB","ABS, Central door lock, Driver-side airbag, El...",NaN,1545.000,No,Part/Full Leather,2.000,unefficient,7.000,100.000,4.900,Standard,Standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28625,Volvo S90,Volvo,"HERMANOS LUMIERE Nº16, 29004 MALAGA, ES",37600.000,Sedan,Used,4.000,Yes,40345.000,Automatic,Diesel,Dealer,4.000,1969.000,8.000,127.000,4WD,"Bluetooth, USB","ABS, Central door lock, Driver-side airbag, El...",Alloy wheels,2077.000,No,Part/Full Leather,2.000,efficient,3.000,288.000,2.000,Standard,Standard
28626,Volvo S40,Volvo,"Stobbeweg 6, 2461 EX TER AAR, NL",5499.000,Sedan,Used,4.000,No,145000.000,Automatic,Benzine,Dealer,5.000,2435.000,5.000,217.000,Front,"On-board computer, Radio","ABS, Central door lock, Central door lock with...","Alloy wheels (16""), Trailer hitch",1357.000,Yes,Cloth,3.000,efficient,18.000,125.000,9.100,Standard,Standard
28627,Volvo C30,Volvo,"Sur rendez-vous, 5060 Sambreville, BE",7300.000,Sedan,Used,3.000,Yes,96000.000,Manual,Diesel,Dealer,4.000,1560.000,6.000,99.000,Front,"Bluetooth, CD player, Hands-free equipment, MP...","ABS, Alarm system, Central door lock with remo...","Alloy wheels, Automatically dimming interior m...",1356.000,Yes,Cloth,1.000,unefficient,11.000,84.000,3.800,Standard,Standard
28628,Volvo S90,Volvo,"Bergambachterstraat 5, 2871 JB SCHOONHOVEN, NL",29900.000,Sedan,Used,4.000,Yes,94343.000,Automatic,Benzine,Dealer,5.000,1969.000,8.000,149.000,4WD,"Android Auto, Apple CarPlay, Bluetooth, Hands-...","Adaptive Cruise Control, Adaptive headlights, ...","Alloy wheels (18""), Automatically dimming inte...",1617.000,Yes,Part/Full Leather,1.000,efficient,5.000,187.000,6.500,Standard,Standard
28629,Volvo S80,Volvo,"Lage Ham 106, 5102 AE DONGEN, NL",4440.000,Sedan,Used,4.000,No,230047.000,Automatic,Benzine,Dealer,5.000,2922.000,6.000,251.000,Front,On-board computer,"ABS, Alarm system, Central door lock, Central ...","Alloy wheels, Automatically dimming interior m...",1573.000,No,Part/Full Leather,5.000,unefficient,20.000,147.000,10.400,Standard,Standard

In [ ]:
df['entertainment_&_media_Package'].value_counts(dropna=False)

Standard    17751
Plus        10879
Name: entertainment_&_media_Package, dtype: int64

In [ ]:
df.shape

(28630, 30)

In [ ]:
df.drop("entertainment_&_media", axis=1, inplace=True)

In [ ]:
df.shape

(28630, 29)

## extras

In [ ]:
first_looking("extras")

COLUMN NAME    :  extras
--------------------------------
per_of_nulls   :  % 17.99
num_of_nulls   :  5150
num_of_uniques :  9360
--------------------------------
NaN                                                                                                                                                                                                                                                                 5150
Alloy wheels                                                                                                                                                                                                                                                        3408
Alloy wheels, Roof rack                                                                                                                                                                                                                                              380
Alloy wheels, Sport seats                                                                                                                                                                                                                                            372
Alloy wheels, Touch screen                                                                                                                                                                                                                                           231
                                                                                                                                                                                                                                                                    ...
Alloy wheels (18"), Spoiler, Summer tyres, Trailer hitch                                                                                                                                                                                                               1
All season tyres, Alloy wheels, Automatically dimming interior mirror, Catalytic Converter, Headlight washer system, Ski bag, Sport seats, Trailer hitch, Winter tyres                                                                                                 1
Alloy wheels, Automatically dimming interior mirror, Headlight washer system, Sport package, Sport seats, Summer tyres                                                                                                                                                 1
Alloy wheels (19"), Ambient lighting, Automatically dimming interior mirror, Catalytic Converter, E10-enabled, Emergency tyre repair kit, Headlight washer system, Spoiler, Sport package, Sport seats, Sport suspension, Summer tyres, Tuned car, Voice Control       1
Alloy wheels, Automatically dimming interior mirror, Ski bag, Trailer hitch                                                                                                                                                                                            1
Name: extras, Length: 9361, dtype: int64

In [ ]:
fill(df, "make_model", "body_type", "extras", "mode")

COLUMN NAME    :  extras
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  9360
--------------------------------
All season tyres                                                           40
All season tyres, Alloy wheels                                             35
All season tyres, Alloy wheels (13"), Catalytic Converter, Touch screen     1
All season tyres, Alloy wheels (14")                                        1
All season tyres, Alloy wheels (14"), Emergency tyre, Smoker's package      2
                                                                           ..
Voice Control, Winter package                                               1
Voice Control, Winter tyres                                                 1
Winter package                                                              1
Winter package, Winter tyres                                                1
Winter tyres                                                               16
Name: extras, Length: 9360, dtype: int64

## safety_&_security

In [ ]:
first_looking("safety_&_security")

COLUMN NAME    :  safety_&_security
--------------------------------
per_of_nulls   :  % 11.23
num_of_nulls   :  3215
num_of_uniques :  12549
--------------------------------
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          3215
Isofix                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        380
ABS, Central door lock, Driver-side airbag, Electronic stability control, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag                                                                                                                                                                                                                                                                                                                                                                             328
ABS, Central door lock, Driver-side airbag, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Traction control                                                                                                                                                                                                                                                                                                                                                                                         125
ABS, Central door lock, Driver-side airbag, Electronic stability control, Fog lights, Isofix, Power steering, Side airbag                                                                                                                                                                                                                                                                                                                                                                                                     121
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ...
Daytime running lights, Emergency brake assistant, Fog lights, Isofix, LED Daytime Running Lights, Lane departure warning system, Power steering, Tire pressure monitoring system                                                                                                                                                                                                                                                                                                                                               1
ABS, Adaptive Cruise Control, Central door lock, Daytime running lights, Driver drowsiness detection, Driver-side airbag, Electronic stability control, Emergency brake assistant, Emergency system, Fog lights, Full-LED headlights, Glare-free high beam headlights, Immobilizer, Isofix, LED Headlights, Lane departure warning system, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control                                                                                1
ABS, Driver-side airbag, Electronic stability control, Emergency brake assistant, Immobilizer, LED Daytime Running Lights, Passenger-side airbag, Side airbag, Tire pressure monitoring system, Traction control                                                                                                                                                                                                                                                                                                                1
ABS, Blind spot monitor, Central door lock, Daytime running lights, Distance warning system, Driver drowsiness detection, Driver-side airbag, Electronic stability control, Emergency system, Fog lights, Full-LED headlights, Head airbag, High beam assist, Immobilizer, Isofix, LED Daytime Running Lights, LED Headlights, Lane departure warning system, Passenger-side airbag, Power steering, Side airbag, Speed limit control system, Tire pressure monitoring system, Traction control, Traffic sign recognition       1
ABS, Alarm system, Central door lock, Central door lock with remote control, Driver-side airbag, Electronic stability control, Fog lights, Head airbag, Immobilizer, Power steering, Side airbag, Traction control                                                                                                                                                                                                                                                                                                              1
Name: safety_&_security, Length: 12550, dtype: int64

In [ ]:
fill(df, "make_model", "body_type", "safety_&_security", "mode")

COLUMN NAME    :  safety_&_security
--------------------------------
per_of_nulls   :  % 0.0
num_of_nulls   :  0
num_of_uniques :  12549
--------------------------------
ABS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  17
ABS, Adaptive Cruise Control, Adaptive headlights, Alarm system, Bi-Xenon headlights, Blind spot monitor, Central door lock with remote control, Distance warning system, Driver-side airbag, Electronic stability control, Emergency brake assistant, Fog lights, Head airbag, High beam assist, Immobilizer, LED Daytime Running Lights, Lane departure warning system, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control                                                                                                                                                                                                                                                                                                       1
ABS, Adaptive Cruise Control, Adaptive headlights, Alarm system, Bi-Xenon headlights, Blind spot monitor, Central door lock with remote control, Distance warning system, Driver-side airbag, Electronic stability control, Emergency system, Head airbag, High beam assist, Immobilizer, Isofix, LED Daytime Running Lights, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control                                                                                                                                                                                                                                                                                                                                                   1
ABS, Adaptive Cruise Control, Adaptive headlights, Alarm system, Bi-Xenon headlights, Blind spot monitor, Central door lock, Central door lock with remote control, Daytime running lights, Distance warning system, Driver drowsiness detection, Driver-side airbag, Electronic stability control, Emergency brake assistant, Emergency system, Fog lights, Full-LED headlights, Glare-free high beam headlights, Head airbag, High beam assist, Immobilizer, Isofix, LED Daytime Running Lights, LED Headlights, Lane departure warning system, Laser headlights, Night view assist, Passenger-side airbag, Power steering, Rear airbag, Side airbag, Speed limit control system, Tire pressure monitoring system, Traction control, Traffic sign recognition, Xenon headlights     1
ABS, Adaptive Cruise Control, Adaptive headlights, Alarm system, Bi-Xenon headlights, Blind spot monitor, Central door lock, Central door lock with remote control, Daytime running lights, Distance warning system, Driver drowsiness detection, Driver-side airbag, Electronic stability control, Emergency brake assistant, Emergency system, Fog lights, Full-LED headlights, Glare-free high beam headlights, Head airbag, High beam assist, Immobilizer, Isofix, LED Daytime Running Lights, LED Headlights, Lane departure warning system, Laser headlights, Passenger-side airbag, Power steering, Rear airbag, Side airbag, Speed limit control system, Tire pressure monitoring system, Traction control, Traffic sign recognition, Xenon headlights                        2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ..
Side airbag                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           3
Speed limit control system                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            8
Tire pressure monitoring system                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       2
Traction control                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     18
Xenon headlights                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      2
Name: safety_&_security, Length: 12549, dtype: int64

**Let us define car ``"Safety & Security Packages"``**

In [ ]:
premium = ["Tire pressure", "Traction control", "Daytime running lights", "LED Headlight", "Tire pressure"]
premium_plus = ["Emergency brake assistant", "Electronic stability control"]

safety_security_package = df['safety_&_security'].apply(lambda sentence: "Safety Premium Package" if any(word in sentence for word in premium) else ("Safety Premium Plus Package" if any(word in sentence for word in premium_plus) else "Safety Standard Package"))
safety_security_package.value_counts()

Safety Premium Package         21270
Safety Standard Package         4883
Safety Premium Plus Package     2477
Name: safety_&_security, dtype: int64

In [ ]:
premium = ["Tire pressure", "Traction control", "Daytime running lights", "LED Headlight", "Tire pressure"]
premium_plus = ["Emergency brake assistant", "Electronic stability control"]

df['safety_&_security_Package'] = df['safety_&_security'].apply(lambda sentence: "Safety Premium Package" if any(word in sentence for word in premium) else ("Safety Premium Plus Package" if any(word in sentence for word in premium_plus) else "Safety Standard Package"))
df

,make_model,make,location,price,body_type,type,doors,warranty,mileage,gearbox,fuel_type,seller,seats,engine_size,gears,co_emissions,drivetrain,safety_&_security,extras,empty_weight,full_service_history,upholstery,previous_owner,energy_efficiency_class,age,power_kW,cons_avg,comfort_&_convenience_Package,entertainment_&_media_Package,safety_&_security_Package
0,Mercedes-Benz A 160,Mercedes-Benz,"P.I. EL PALMAR C/FORJA 6, 11500 PUERTO DE SAN...",16950.000,Compact,Used,5.000,Yes,120200.000,Manual,Diesel,Dealer,5.000,1595.000,5.000,98.000,Front,"ABS, Adaptive Cruise Control, Alarm system, Dr...",Alloy wheels,1270.000,No,Cloth,2.000,efficient,6.000,75.000,3.800,Standard,Standard,Safety Premium Package
1,Mercedes-Benz EQE 350,Mercedes-Benz,"APARTADO DE CORREOS 1032, 26140 LOGROÑO, ES",80900.000,Compact,Pre-registered,4.000,Yes,5000.000,Automatic,Electric,Dealer,5.000,1.000,9.000,0.000,4WD,"ABS, Adaptive Cruise Control, Adaptive headlig...","Alloy wheels (21""), Shift paddles, Sport packa...",2355.000,No,Part/Full Leather,1.000,efficient,0.000,215.000,2.359,Premium,Plus,Safety Premium Package
2,Mercedes-Benz A 45 AMG,Mercedes-Benz,"PORT. TARRACO, MOLL DE LLEVANT, Nº 5, LOC. 6-8...",69900.000,Compact,Used,5.000,Yes,18900.000,Automatic,Benzine,Dealer,5.000,1991.000,8.000,162.000,4WD,"ABS, Central door lock, Driver-side airbag, El...",Alloy wheels,1555.000,No,Part/Full Leather,2.000,unefficient,2.000,310.000,8.400,Standard,Standard,Safety Premium Plus Package
3,Mercedes-Benz A 35 AMG,Mercedes-Benz,"Carrer de Provença, 31 Local, 8029 BARCELONA, ES",46990.000,Compact,Used,5.000,Yes,18995.000,Automatic,Benzine,Dealer,5.000,1991.000,7.000,169.000,4WD,"ABS, Central door lock, Driver-side airbag, El...",Sport seats,1455.000,No,Part/Full Leather,2.000,unefficient,2.000,225.000,7.300,Standard,Standard,Safety Premium Package
4,Mercedes-Benz A 45 AMG,Mercedes-Benz,"CARRIL ARAGONES 4, 30007 CASILLAS, ES",16800.000,Compact,Used,5.000,Yes,197000.000,Automatic,Diesel,Dealer,5.000,2143.000,7.000,162.000,4WD,"ABS, Central door lock, Driver-side airbag, El...",Alloy wheels,1545.000,No,Part/Full Leather,2.000,unefficient,7.000,100.000,4.900,Standard,Standard,Safety Premium Plus Package
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28625,Volvo S90,Volvo,"HERMANOS LUMIERE Nº16, 29004 MALAGA, ES",37600.000,Sedan,Used,4.000,Yes,40345.000,Automatic,Diesel,Dealer,4.000,1969.000,8.000,127.000,4WD,"ABS, Central door lock, Driver-side airbag, El...",Alloy wheels,2077.000,No,Part/Full Leather,2.000,efficient,3.000,288.000,2.000,Standard,Standard,Safety Premium Plus Package
28626,Volvo S40,Volvo,"Stobbeweg 6, 2461 EX TER AAR, NL",5499.000,Sedan,Used,4.000,No,145000.000,Automatic,Benzine,Dealer,5.000,2435.000,5.000,217.000,Front,"ABS, Central door lock, Central door lock with...","Alloy wheels (16""), Trailer hitch",1357.000,Yes,Cloth,3.000,efficient,18.000,125.000,9.100,Standard,Standard,Safety Standard Package
28627,Volvo C30,Volvo,"Sur rendez-vous, 5060 Sambreville, BE",7300.000,Sedan,Used,3.000,Yes,96000.000,Manual,Diesel,Dealer,4.000,1560.000,6.000,99.000,Front,"ABS, Alarm system, Central door lock with remo...","Alloy wheels, Automatically dimming interior m...",1356.000,Yes,Cloth,1.000,unefficient,11.000,84.000,3.800,Standard,Standard,Safety Premium Package
28628,Volvo S90,Volvo,"Bergambachterstraat 5, 2871 JB SCHOONHOVEN, NL",29900.000,Sedan,Used,4.000,Yes,94343.000,Automatic,Benzine,Dealer,5.000,1969.000,8.000,149.000,4WD,"Adaptive Cruise Control, Adaptive headlights, ...","Alloy wheels (18""), Automatically dimming inte...",1617.000,Yes,Part/Full Leather,1.000,efficient,5.000,187.000,6.500,Standard,Standard,Safety Premium Package
28629,Volvo S80,Volvo,"Lage Ham 106, 5102 AE DONGEN, NL",4440.000,Sedan,Used,4.000,No,230047.000,Automatic,Benzine,Dealer,5.000,2922.000,6.000,251.000,Front,"ABS, Alarm system, Central door lock, Central ...","Alloy wheels, Automatically dimming interior m...",1573.000,No,Part/Full Leather,5.000,unefficient,20.000,147.000,10.400,Standard,Standard,Safety Premium Package

In [ ]:
df['safety_&_security_Package'].value_counts(dropna=False)

Safety Premium Package         21270
Safety Standard Package         4883
Safety Premium Plus Package     2477
Name: safety_&_security_Package, dtype: int64

**Let us assign each car to related ``"Safety & Security Packages"`` defined above:**

In [ ]:
df.shape

(28630, 30)

In [ ]:
df.drop("safety_&_security", axis=1, inplace=True)

In [ ]:
df.shape

(28630, 29)

## End of this phase

In [ ]:
df.head()

,make_model,make,location,price,body_type,type,doors,warranty,mileage,gearbox,fuel_type,seller,seats,engine_size,gears,co_emissions,drivetrain,extras,empty_weight,full_service_history,upholstery,previous_owner,energy_efficiency_class,age,power_kW,cons_avg,comfort_&_convenience_Package,entertainment_&_media_Package,safety_&_security_Package
0,Mercedes-Benz A 160,Mercedes-Benz,"P.I. EL PALMAR C/FORJA 6, 11500 PUERTO DE SAN...",16950.000,Compact,Used,5.000,Yes,120200.000,Manual,Diesel,Dealer,5.000,1595.000,5.000,98.000,Front,Alloy wheels,1270.000,No,Cloth,2.000,efficient,6.000,75.000,3.800,Standard,Standard,Safety Premium Package
1,Mercedes-Benz EQE 350,Mercedes-Benz,"APARTADO DE CORREOS 1032, 26140 LOGROÑO, ES",80900.000,Compact,Pre-registered,4.000,Yes,5000.000,Automatic,Electric,Dealer,5.000,1.000,9.000,0.000,4WD,"Alloy wheels (21""), Shift paddles, Sport packa...",2355.000,No,Part/Full Leather,1.000,efficient,0.000,215.000,2.359,Premium,Plus,Safety Premium Package
2,Mercedes-Benz A 45 AMG,Mercedes-Benz,"PORT. TARRACO, MOLL DE LLEVANT, Nº 5, LOC. 6-8...",69900.000,Compact,Used,5.000,Yes,18900.000,Automatic,Benzine,Dealer,5.000,1991.000,8.000,162.000,4WD,Alloy wheels,1555.000,No,Part/Full Leather,2.000,unefficient,2.000,310.000,8.400,Standard,Standard,Safety Premium Plus Package
3,Mercedes-Benz A 35 AMG,Mercedes-Benz,"Carrer de Provença, 31 Local, 8029 BARCELONA, ES",46990.000,Compact,Used,5.000,Yes,18995.000,Automatic,Benzine,Dealer,5.000,1991.000,7.000,169.000,4WD,Sport seats,1455.000,No,Part/Full Leather,2.000,unefficient,2.000,225.000,7.300,Standard,Standard,Safety Premium Package
4,Mercedes-Benz A 45 AMG,Mercedes-Benz,"CARRIL ARAGONES 4, 30007 CASILLAS, ES",16800.000,Compact,Used,5.000,Yes,197000.000,Automatic,Diesel,Dealer,5.000,2143.000,7.000,162.000,4WD,Alloy wheels,1545.000,No,Part/Full Leather,2.000,unefficient,7.000,100.000,4.900,Standard,Standard,Safety Premium Plus Package

In [ ]:
df.shape

(28630, 29)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28630 entries, 0 to 28629
Data columns (total 29 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   make_model                     28630 non-null  object
 1   make                           28630 non-null  object
 2   location                       28630 non-null  object
 3   price                          28630 non-null  float64
 4   body_type                      28630 non-null  object
 5   type                           28630 non-null  object
 6   doors                          28630 non-null  float64
 7   warranty                       28630 non-null  object
 8   mileage                        28630 non-null  float64
 9   gearbox                        28630 non-null  object
 10  fuel_type                      28630 non-null  object
 11  seller                         28630 non-null  object
 12  seats                          28630 non-null  float64
 13  engine_size                    28630 non-null  float64
 14  gears                          28630 non-null  float64
 15  co_emissions                   28630 non-null  float64
 16  drivetrain                     28630 non-null  object
 17  extras                         28630 non-null  object
 18  empty_weight                   28630 non-null  float64
 19  full_service_history           28630 non-null  object
 20  upholstery                     28630 non-null  object
 21  previous_owner                 28630 non-null  float64
 22  energy_efficiency_class        28630 non-null  object
 23  age                            28630 non-null  float64
 24  power_kW                       28630 non-null  float64
 25  cons_avg                       28630 non-null  float64
 26  comfort_&_convenience_Package  28630 non-null  object
 27  entertainment_&_media_Package  28630 non-null  object
 28  safety_&_security_Package      28630 non-null  object
dtypes: float64(12), object(17)
memory usage: 6.3+ MB

In [ ]:
class color:
    PURPLE = '\033[95m'
    CYAN = '\033[96m'
    DARKCYAN = '\033[36m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    END = '\033[0m'

def check_obj_columns(df):
    '''
    Returns NO PROBLEM or column/s which has/have mixed object types.
    '''    
    
    tdf = df.select_dtypes(include=['object']).applymap(type)
    for col in tdf:
        if len(set(tdf[col].values)) > 1:
            print("Column" + " " + color.BOLD + color.RED + col + color.END + " " + "has mixed object types." )
    else:
        if len(set(tdf[col].values)) == 1:
            print(color.BOLD + color.GREEN + " " + "NO PROBLEM" + " " + color.END + " " + "with the data types of Columns in the DataFrame.")

check_obj_columns(df)

 NO PROBLEM  with the data types of Columns in the DataFrame.

In [ ]:
df.isnull().sum()*100 / df.shape[0]

make_model                      0.000
make                            0.000
location                        0.000
price                           0.000
body_type                       0.000
type                            0.000
doors                           0.000
warranty                        0.000
mileage                         0.000
gearbox                         0.000
fuel_type                       0.000
seller                          0.000
seats                           0.000
engine_size                     0.000
gears                           0.000
co_emissions                    0.000
drivetrain                      0.000
extras                          0.000
empty_weight                    0.000
full_service_history            0.000
upholstery                      0.000
previous_owner                  0.000
energy_efficiency_class         0.000
age                             0.000
power_kW                        0.000
cons_avg                        0.000
comfort_&_convenience_Package   0.000
entertainment_&_media_Package   0.000
safety_&_security_Package       0.000
dtype: float64

In [ ]:
df.duplicated(keep=False).sum()

3806

In [ ]:
df[df.duplicated(keep=False)]

,make_model,make,location,price,body_type,type,doors,warranty,mileage,gearbox,fuel_type,seller,seats,engine_size,gears,co_emissions,drivetrain,extras,empty_weight,full_service_history,upholstery,previous_owner,energy_efficiency_class,age,power_kW,cons_avg,comfort_&_convenience_Package,entertainment_&_media_Package,safety_&_security_Package
142,Mercedes-Benz A 45 AMG,Mercedes-Benz,"RONDA PONENT 62, 8201 SABADELL, ES",72890.000,Compact,Used,5.000,Yes,12900.000,Automatic,Benzine,Dealer,5.000,1991.000,8.000,162.000,4WD,Alloy wheels,1555.000,No,Part/Full Leather,1.000,unefficient,1.000,310.000,8.400,Standard,Standard,Safety Premium Plus Package
237,Mercedes-Benz CL,Mercedes-Benz,"--, 77240 Vert St Denis, FR",39990.000,Compact,Used,5.000,No,8500.000,Automatic,Benzine,Dealer,5.000,1332.000,8.000,118.000,4WD,"Alloy wheels, Shift paddles, Sport package, Sp...",1705.000,No,Part/Full Leather,1.000,unefficient,0.000,87.000,8.400,Premium,Plus,Safety Premium Package
253,Mercedes-Benz CL,Mercedes-Benz,"--, 77240 Vert St Denis, FR",39990.000,Compact,Used,5.000,No,8500.000,Automatic,Benzine,Dealer,5.000,1332.000,8.000,118.000,4WD,"Alloy wheels, Shift paddles, Sport package, Sp...",1705.000,No,Part/Full Leather,1.000,unefficient,0.000,87.000,8.400,Premium,Plus,Safety Premium Package
263,Mercedes-Benz CL,Mercedes-Benz,"--, 77240 Vert St Denis, FR",39990.000,Compact,Used,5.000,No,8500.000,Automatic,Benzine,Dealer,5.000,1332.000,8.000,118.000,4WD,"Alloy wheels, Shift paddles, Sport package, Sp...",1705.000,No,Part/Full Leather,1.000,unefficient,0.000,87.000,8.400,Premium,Plus,Safety Premium Package
276,Mercedes-Benz A 45 AMG,Mercedes-Benz,"RONDA PONENT 62, 8201 SABADELL, ES",72890.000,Compact,Used,5.000,Yes,12900.000,Automatic,Benzine,Dealer,5.000,1991.000,8.000,162.000,4WD,Alloy wheels,1555.000,No,Part/Full Leather,1.000,unefficient,1.000,310.000,8.400,Standard,Standard,Safety Premium Plus Package
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28386,Volvo S90,Volvo,"Donnerwenge 2, 57439 Attendorn, DE",55470.000,Sedan,Employee's car,4.000,Yes,10000.000,Automatic,Diesel,Dealer,5.000,1969.000,8.000,127.000,4WD,"Alloy wheels, Touch screen, Trailer hitch, Voi...",1892.000,Yes,Part/Full Leather,1.000,efficient,1.000,173.000,4.800,Premium,Plus,Safety Premium Package
28556,Volvo S90,Volvo,"Von-Drais-Str. 2, 77855 Achern, DE",31488.000,Sedan,Used,4.000,No,84000.000,Automatic,Diesel,Dealer,5.000,1969.000,0.000,127.000,4WD,"Alloy wheels, Catalytic Converter, Sport suspe...",1892.000,No,Part/Full Leather,1.000,efficient,5.000,173.000,4.800,Standard,Standard,Safety Premium Package
28557,Volvo S90,Volvo,"Von-Drais-Str. 2, 77855 Achern, DE",31488.000,Sedan,Used,4.000,No,84000.000,Automatic,Diesel,Dealer,5.000,1969.000,0.000,127.000,4WD,"Alloy wheels, Catalytic Converter, Sport suspe...",1892.000,No,Part/Full Leather,1.000,efficient,5.000,173.000,4.800,Standard,Standard,Safety Premium Package
28593,Volvo V40,Volvo,"19 rue des Alliés, 57050 Metz, FR",18999.000,Sedan,Used,5.000,Yes,93257.000,Automatic,Diesel,Dealer,5.000,1969.000,6.000,108.000,Front,Emergency tyre,1546.000,No,Cloth,1.000,efficient,4.000,112.000,3.950,Standard,Standard,Safety Premium Package
28595,Volvo V40,Volvo,"19 rue des Alliés, 57050 Metz, FR",18999.000,Sedan,Used,5.000,Yes,93257.000,Automatic,Diesel,Dealer,5.000,1969.000,6.000,108.000,Front,Emergency tyre,1546.000,No,Cloth,1.000,efficient,4.000,112.000,3.950,Standard,Standard,Safety Premium Package

**Let us save our dataset with a csv extension for further analysis (Handling Outliers) in the following notebook:**

In [ ]:
df.to_csv("filled_scout2022.csv", index=False)

<a id="10"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:150%; text-align:center; border-radius:10px 10px;">The End of Handling with Missing Values (Part - 02)</p>


<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>

<a href="https://clarusway.com/"><img align="center" src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" alt="CLRSWY" title="Way to Reinvent Yourself"></a><br/>


## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:120%; text-align:center; border-radius:10px 10px;">Way to Reinvent Yourself</p>
___